### ISSUE TITLE
rail_ir_finder should take the gestures it finds and yield 2 IRs

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1007]
Right now, we find a group of inputs and turn it into a gesture. That gesture then is a single Response IR.

Actually, the first input latency event should be a Response IR. All the rest of the gesture should be an Animation IR.

rail_ir_finder.findResponseInteractionRecords should be the function to edit.

**Comment by natduca** [comment]
@benshayden fyi

**Comment by benshayden** [comment]
I'm looking at measurmt-traces/test_data/mobile/google_io_instrument_strumming.json. There's a TouchStart then a TouchEnd then a TouchStart. The TouchEnd overlaps with both TouchStarts,  so they're all merged into the same gesture, so the algorithm that you outline would only catch the first TouchStart but not the second. It also doesn't generate an Animation IR for the TouchMoves at all.

Q:
Why not take every TouchStart to be a ResponseIR, and merge TouchMoves starting from the end of the TouchStart through the end of the next TouchEnd to be the AnimationIR?

**Comment by natduca** [comment]
> There's a TouchStart then a TouchEnd then a TouchStart. The TouchEnd overlaps with both TouchStarts, so they're all merged into the same gesture
We could someday update the gesture finder to consider the up/down state of the fingers as part of this. It doesn't now but I'm not against it in the future.


> the algorithm that you outline would only catch the first TouchStart but not the second.
yes, agreed. we could perhaps improve gesture finding down the road. sounds like a bug to file.

> It also doesn't generate an Animation IR for the TouchMoves at all.
Why not? If you have touch start, touch move, touch move, touch move, touch end, then that should have animation. Or did  I miss something?

Maybe you can involve yuhao and yufeng and jared in a vc or in person whiteboard session... this would be a opportunity to pull folks together. :)

**Comment by benshayden** [comment]
I think RAILIRFinder address this basic issue. We can file more issues to refine specific aspects and edge cases. Feel free to re-open if you disagree.
