### ISSUE TITLE
Compute associatedEvents for Idle Interaction Records

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1010]
We want idle interaction records efficiency to go down as there is more work in the gap. This requires that we have associated events for idle IRs. But, the way we create idle IRs is through subtraction: we find all the non-idle records, then define idleness as the gaps. Given that, how do we get associatedEvents?

@yuhao @benshayden

**Comment by benshayden** [comment]
How do sites do work while the page is idle besides setTimeout()? Can we
just find all the dom timers in the idle interval and follow their flow
events?
