### ISSUE TITLE
BattOr importer will timeshift an existing power trace

### ISSUE THREAD

**Issue by aschulm** [google/trace-viewer#1012]
The BattOr importer should fail if there already is an existing power trace.

**Comment by fmeawad** [comment]
I think it should fail if there is another battor power trace, but how about we get input from a different source?

**Comment by aschulm** [comment]
Well right now there is only one "Power" counter in trace-viewer, and it's created by the battor-importer. We can consider renaming this to "BattOr Power" so it's clear where the power measurements are coming from, but it may complicate creating other counters that are based off the "Power" counter (e.g., energy per frame).

**Comment by dj2** [comment]
I think having this fail with a console.log is the right thing for now. If we add another power source in the future we'll see pretty quick (from the console) that something is wrong and we can come back to figuring out how to fix it. Until we have multiple power sources, I think this is the best approach.
