### ISSUE TITLE
CPU slices are shifted into negative time, by about negative 50000 seconds

### ISSUE THREAD

**Issue by ChrisCraik** [google/trace-viewer#1016]
Open android_systrace.html example files to see this. Fairly recent regression (past week or so?).

**Comment by dj2** [comment]
Bisected it back to 2e3f8980e61eaf51f01ac00a56e853bd92b2c516. Reverted with 6890d4ba71f33614ac5a5c5270d723e2cbbdcd7f. The CPU slices should be correct now.

@zeptonaut fyi.

**Comment by natduca** [comment]
Sounds like we have test coverage gaps. Lets add some tests that'd catch this when we re-land.
