### ISSUE TITLE
Document Interaction Records

### ISSUE THREAD

**Issue by dj2** [google/trace-viewer#1017]
As we're adding interaction records we should create a document somewhere that lists them, how we find them and what they mean. This will make it easier for people to figure out what we're reporting on.

@natduca

**Comment by natduca** [comment]
i'm hoping that go/railscore is that document, over time. What I've not decided on right now is if InteractionRecord should merge with RAILInteractionRecord. That is, is there any point in having an IR that isn't also a RAILIR?

**Comment by dj2** [comment]
Personally, I'd drop RAIL. Interaction records are still valid outside the RAIL model and I don't think they need to be tied to rail specifically.

By document, I must mean a document somewhere that has things like:

IR: Frame Time
Identified by: foo event start and blah event end
Meaning: Time to generate a frame.

Something that tells us, what we're looking for, how we find them and why we find them.

**Comment by natduca** [comment]
The purpose of the rail subclasses is to actually have different implementations of some of the IR methods. I'm not sure the data driven approach is really possible.

I do like the idea of better descriptions on slices down the road. Android added a neat mechanism on alerts called eventinfo i think? what if we generalized that for all events?
