### ISSUE TITLE
"Flow Big" no longer renders correctly.

### ISSUE THREAD

**Issue by philippebeaudoin** [google/trace-viewer#1020]
Select "Flow Big" and only some of events render.

Expected:
![image](https://cloud.githubusercontent.com/assets/11399419/8112417/9341d826-1035-11e5-818e-7833eb87a9f2.png)

Observed:
![image](https://cloud.githubusercontent.com/assets/11399419/8112448/b1be5716-1035-11e5-83ba-5a9135b0a4d3.png)

**Comment by philippebeaudoin** [comment]
I'm currently bisecting this.

**Comment by philippebeaudoin** [comment]
Bisected it down to one of these:

* 8f869da Fix tests that have no RAILInteractionRecords.
* 15d5a8e Added Time.currentDisplayUnit for for formatting time durations and stamps.
* baad499 Make generic_object_view use table builder.
* 493cd6a IdleInteractionRecord

**Comment by philippebeaudoin** [comment]
Confirmed it's 493cd6a basic fix in progress. (Reverting was too painful.)

**Comment by dj2** [comment]
Can we create a test case for this before we re-enable to code that caused the issue. Seems like a gap in our unit testing.

**Comment by natduca** [comment]
@benshayden

**Comment by philippebeaudoin** [comment]
Assigning to Ben. We should indeed have a unit test for this.

**Comment by dj2** [comment]
Can we check if we need a DEPs roll for this fix? Looks like it was picked up by telemetry crbug.com/499489 and is causing issues over there. If so, we should roll the fix into chromium sooner rather then later.

**Comment by dj2** [comment]
@benshayden can you check if telemetry is still effected by this? If not, please close this issue.

**Comment by benshayden** [comment]
Ned says the ref build might need to be updated.

**Comment by dj2** [comment]
K, @nedn can you close this bug when the telemetry side is fixed?

**Comment by nedn** [comment]
Since trace-viewer supports backward compat until stable, shouldn't this still need to be fixed?

**Comment by dj2** [comment]
This was fixed. The original breaking change was reverted and then the code was fixed and recommitted.
