### ISSUE TITLE
"k of n" data in search/filtering should be displayed when navigating with arrow buttons

### ISSUE THREAD

**Issue by randomascii** [google/trace-viewer#1021]
When doing a search/filter in chrome://tracing the filtering text box shows "k of n" on the right side - i.e.;  "3 of 157" and this updates every time you press 'Enter'. However if you click the arrows to the right of the text box then the numbers go away.

In addition to making it hard to know where you are it makes it less obvious what the two arrow buttons actually do - it took me a while to be certain that they were actually moving through the filtering results.

The arrows are particularly important because the 'f' shortcut to highlight the current results doesn't work when the text box is active. It would be nice if there was a shortcut to highlight the current results which would work always - perhaps ctrl+F.

**Comment by petrcermak** [comment]
This is related to #997 and #990.

**Comment by natduca** [comment]
@dj2 we're getting bugs at the rate of one or two a week in the current find system. what do you think the source of fragility is? should we do something drastic? i've been working on a keyboard handling fix and i'm finding surprising amounts of fragility in how it integrates with the rest of the world...

**Comment by dj2** [comment]
Mostly it's that it's > 2years old and no one has really touched it. I converted it to polymer but didn't get down into how it worked. I'm guessing it just isn't well built/integrated. I don't think anything drastic needs to happen, someone just has to sit down and figure out what's wrong and how best to fix it.
