### ISSUE TITLE
Fix sorting on category list in Record a new trace dialog, manually select settings

### ISSUE THREAD

**Issue by randomascii** [google/trace-viewer#1022]
The sorting of categories is currently case sensitive. This means we have:

Blob
CRLSet
...
WebCore
base
benchmark
...

I find this confusing. We should either fix the casing or just make the sort case insensitive.

**Comment by dj2** [comment]
Probably we should do both. I did a pass a while ago to lower case trace event categories. We had a bunch of duplicate ones like "blink" and "Blink" or "v8" and "V8". Getting them in a consistent state is probably a good idea.

But, we should also sort insensitive as they'll show up again in the future I'm sure (and we remember categories we've seen in the past so they're going to end up sticking around, sadly)

**Comment by fmeawad** [comment]
Added a CL that ingores case when sorting, there is still a few categories that use Upper case still.

At my last TOT, there was Blob, CacheStorage, ETW Trace Event, IndexedDB, ServiceWorker, ValueStoreFrontend::Backend.

Marking as Fixed, feel free to reopen if you want to use this bug to track those name changes as well.
