### ISSUE TITLE
Construct associated slices for fling events

### ISSUE THREAD

**Issue by yuhao** [google/trace-viewer#1024]
Fling events are a little bit different from other inputs since there is no direct flow events going into any of the associated renderer slices.
@natduca

**Comment by yuhao** [comment]
Again the heuristic could be get anything between flingstart and flingcancel?

**Comment by natduca** [comment]
There's some code for matching up a fling with the input events in rail ir finder's e60r code...

**Comment by natduca** [comment]
Is this done?
