### ISSUE TITLE
exception at the end of trace recording.

### ISSUE THREAD

**Issue by folded** [google/trace-viewer#1032]
Happens relatively reliably tracing the gmail webview:

* start tracing (all default + cc.debug)
* click reply
* dismiss keyboard
* scroll view up (but not to the point of overscroll)
* end tracing

Chrome version: 43.0.2357.125 ; webview version 44.0.2403.33

```
TypeError: Cannot read property 'intersectsExplicitRange' of undefined
    at chrome://tracing/tracing.js:31620:30
    at Object.AsyncSliceGroup.iterateAllEvents (chrome://tracing/tracing.js:8218:18)
    at Object.Thread.iterateAllEvents (chrome://tracing/tracing.js:8495:28)
    at chrome://tracing/tracing.js:31617:16
    at Array.forEach (native)
    at Object.ChromeBrowserAudit.getLatencyEventsInRange (chrome://tracing/tracing.js:31616:40)
    at Object.LayerTreeImplSnapshot._initializeTracedInputLatencies (chrome://tracing/tracing.js:32133:41)
    at Object.LayerTreeImplSnapshot.initialize (chrome://tracing/tracing.js:32124:16)
    at ObjectInstance.initialize (chrome://tracing/tracing.js:6800:27)
    at Object.<anonymous> (chrome://tracing/tracing.js:7220:18)
```

**Comment by dj2** [comment]
@natduca

**Comment by natduca** [comment]
I wonder if this is fixed on ToT? This looks like the empty ranges issue Ben had fixed last week. @benshayden look familiar?

**Comment by benshayden** [comment]
LayerTreeImplSnapshot._initializeTracedInputLatencies passes model.bounds
to getLatencyEventsInRange (which I moved to ChromeBrowserHelper) as
rangeOfInterest. The backtrace says rangeOfInterest is undefined. Why would
model.bounds be undefined?

**Comment by natduca** [comment]
I don't think the range has been calculated yet. That's done after object init.

I think the core bug here is that the layer tree impl shouldn't be instantiating an audit. Can it be using the helper directly?

**Comment by folded** [comment]
Is there anything more I can collect to help? Ideally it would be good to get the trace data as a file, I guess. Is there a way to do that, given that this exception means I can't use the standard save functionality?

**Comment by natduca** [comment]
@benshayden can you think up a quick fix?

**Comment by folded** [comment]
It turns out that even though nothing is displayed, post exception, it's still possible to save the trace in what seems like a meaningful format (if you load it, you get the same exception, so "meaningful" is open to interpretation).

I've attached a trace here. I'm not sure whether it contains sensitive information, so for the moment at least it's restricted to @google.com - hope that's not a problem.

https://drive.google.com/a/google.com/file/d/0B9pzqV1vAEdnZ0pZeV9sajh2djg/view

**Comment by benshayden** [comment]
When I load that trace with a ToT trace-viewer, I don't see any exceptions.
