### ISSUE TITLE
GenerateJSForHeadlessImport is not preserving line numbers

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1034]
It should.

**Comment by nedn** [comment]
I will change it so to js parser first (https://github.com/google/trace-viewer/issues/1030) then work on this.

**Comment by natduca** [comment]
Its going to be really hard for me to do the fixes to the modules without line numbers. I don't really see us beginning work on this in bulk without the line numbers working well... which route forward gives us working line numbers sooner? I'd love to bias your engineering time toward the line numbers showing up...

**Comment by nedn** [comment]
Hmhh, ok.
