### ISSUE TITLE
Broken event.html dependencies

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#1038]
model/event.html has a **hidden dependency** on core/selection.html as <tt>Event</tt> constructor does <tt>this.associatedAlerts = new tr.c.Selection();</tt>. This becomes apparent when you run <tt>extras.importer.trace_event_importer_test</tt> by itself (http://localhost:8003/base/tests.html?testSuiteName=extras.importer.trace_event_importer_test) — the following exception is thrown by almost all tests:

```
TypeError: undefined is not a function
    at Object.Event (http://localhost:8003/model/event.html:55:29)
    at Object.TimedEvent (http://localhost:8003/model/timed_event.html:25:20)
    at Object.Slice (http://localhost:8003/model/slice.html:26:25)
    at Object.ThreadSlice (http://localhost:8003/model/thread_slice.html:35:11)
    at Object.SliceGroup.beginSlice (http://localhost:8003/model/slice_group.html:140:19)
    at Object.TraceEventImporter.processDurationEvent (http://localhost:8003/extras/importer/trace_event_importer.html:274:39)
    at Object.TraceEventImporter.importEvents (http://localhost:8003/extras/importer/trace_event_importer.html:510:16)
    at Object.<anonymous> (http://localhost:8003/model/model.html:516:22)
    at Object.Task.run (http://localhost:8003/base/task.html:65:21)
    at Function.Task.RunSynchronously (http://localhost:8003/base/task.html:110:25)
```

When I tried to solve it by adding <tt>\<link rel="import" href="/core/selection.html"\></tt> to the top of model/event.html, the test completely fails with the following "Module loading failure":

```
Error: Uncaught TypeError: Cannot read property 'prototype' of undefined
http://localhost:8003/model/timed_event.html:33
    at Object.<anonymous> (http://localhost:8003/base/unittest/suite_loader.html:163:13)
```

It turns out that this creates an (explicit) dependency cycle:

> model/event.html → core/selection.html → model/model.html → model/kernel.html → model/cpu.html → model/thread_time_slice.html → model/slice.html → model/timed_event.html → model/event.html

I think that the solution is that **model/event.html should not depend on core/selection.html** because the dependency should always go in the following direction: **extras → core → model → base**.

This issue highlights one problem with testing — it **doesn't check that dependencies are correct** because all tests run in one shared environment. Is there any way we could change this? Ideally, each test should run in its own separate document.

**Comment by petrcermak** [comment]
It turns out that core/selection.html doesn't need the whole <tt>Model</tt>, but just <tt>FlowEvent</tt>. Unfortunately, this still doesn't solve the situation, because:

  1. **<tt>Event</tt> constructs a <tt>Selection</tt>** (in <tt>Event</tt> constructor) and
  2. **<tt>Selection</tt> checks if an event is an instance of <tt>FlowEvent</tt>** (in <tt>Selection.getShiftedSelection()</tt>).

Both relationships seem to break the software design of Trace Viewer to a certain degree:

  1. <tt>Event</tt> is a part of the <tt>model</tt> and so it shouldn't need to know anything about <tt>Selection</tt>, which is in <tt>core</tt> (maybe this shows that it should be in <tt>model</tt> as well?)
  2. Checking if an object is an *instance of* a class is usually a bad software design. This might also be indicating that <tt>Selection</tt> does too many things at the same time. Maybe it would be best to push some of its code into the events.

@natduca, @dj2 WDYT?

**Comment by dj2** [comment]
I believe Selection is to be renamed EventSet, at which point it probably also becomes part of the model.

The code to determine the previous/next slice could possible move up to the event code itself.

**Comment by petrcermak** [comment]
I tried solving the issue by splitting <tt>Event</tt> and <tt>EventRegistry</tt> into different files (as suggested in #1086), but that is still not good enough because <tt>EventRegistry</tt> depends (unsurprisingly) on <tt>Event</tt>.

Therefore, I think that the only solution is to **split the <tt>Selection</tt>** class into two parts:

  1. **<tt>EventSet</tt> class** (proposed in #1015) representing a generic set of events. I believe it should be a part of the model (i.e. <tt>tr.model.EventSet</tt>) and should copy *all* methods from the original <tt>Selection</tt> class which do *not* depend on <tt>EventRegistry</tt> (see the three methods mentioned in the next bullet point).
  2. **Utility file** defining the three static methods of the original <tt>Selection</tt> which *do* depend on <tt>EventRegistry</tt>, namely <tt>getEventsOrganizedByBaseType(eventSet, opt_pruneEmpty)</tt>, <tt>getEventsOrganizedByTitle(eventSet)</tt>, and <tt>getEventSetUserFriendlyName(eventSet)</tt>. Since all of these methods are used by <tt>analysis</tt> only, we could move them to <tt>tr.ui.analysis</tt>.

The selection.html file currently also defines <tt>RequestSelectionChangeEvent</tt> (two-line definition), which I believe could either be moved to selection_controller.html, or stay in its own file.

@zeptonaut @natduca @dj2: WDYT? Are there any plans to do the <tt>EventSet</tt> refactor in the near future?

**Comment by zeptonaut** [comment]
I know that @natduca mentioned that he'd like to get the `EventSet` refactor done soon, but it looks like it's a "first person to get to it" sort of refactor. This bug definitely seems to increase the urgency of the refactor, though.

**Comment by dj2** [comment]
I'm working on moving and renaming EventSet. I'll end up committing it in steps. The first one will move the file and get the name changed. Then need to cleanup the various variables named selection we assign it too and also need to cleanup a couple method names.

I'm working through some test failures in order to get the first part done now.

**Comment by zeptonaut** [comment]
SGTM. Thanks for taking care of this Dan!

**Comment by dj2** [comment]
The rename/move is landed. There is some cleanup but the initial test referenced seems to work on its own. I'm removing myself from the owner.

Should we close this and open more specific bugs for the cleanup @petrcermak mentioned above?

**Comment by petrcermak** [comment]
I agree that this should now be **closed** because all broken dependencies are now (hopefully) fixed.
