### ISSUE TITLE
Visualization of IPC flow events seems to be wrong

### ISSUE THREAD

**Issue by yuhao** [google/trace-viewer#1039]
Looks like another binding issue.

@natduca @dj2

**Comment by dj2** [comment]
Can you attach a picture or description of why it's wrong? There isn't much to go on here.

**Comment by yuhao** [comment]
Open the following trace: https://github.com/natduca/measurmt-traces/blob/master/mobile/ipcflow. Click MessageLoop::RunTask slice of Chrome_IOThread in the browser process, and select the Outgoing IPC flow on the bottom panel. The arrowing is point to MessagePumpLibevent::OnLibeventNotification slice of the Chrome_ChildIOThread of the renderer process. This is correct. But the binding point of the IPC is the MessageLoop::RunTask slice to the right of the OnLibeventNotification slice, and that is wrong.

Seems like we should always bind the IPC flow events to their parent instead of to the next. The CL is tracked at: https://codereview.appspot.com/248190043
