### ISSUE TITLE
Mouse wheel event under Idle IR.

### ISSUE THREAD

**Issue by dj2** [google/trace-viewer#1040]
Looking at the test_data/multiple_input_latency.json test. There is an Idle IR between 8.68s and 9.2s. Under that Idle IR there is a RenderWidgetHostImpl::ForwardMouseEvent at ~8918.6ms.

Should this mouse event fall under Response instead of Idle?

@benshayden @natduca

**Comment by benshayden** [comment]
I think mouse wheel events should be merged, then the first event of each sequence should be a Response and the rest should be an Animation.
I'm prototyping this kind of logic in https://codereview.appspot.com/248740043/ but there'll be a couple background CLs as Nat describes before I can mail out that logic.

**Comment by benshayden** [comment]
I looked at this again now that my CL is in. I'm confused.
Why is there a ForwardMouseEvent without an input latency event? Did the category-filter filter out MouseMoves?
It seems to me like RAILIRFinder should not need to go hunting for slices that are normally associated with an input latency event.
Thoughts?

**Comment by natduca** [comment]
@yufengshen may be able to advise on whether this file is just old and crusty, or if there's a useful case in this case.

**Comment by yufengshen** [comment]
Currently the LatencyInfo for mouse events (other than mouse wheel) and keyboard events which do not cause rendering damage (so their latency is from event creation to event acked back to browser) are not tracked.

**Comment by natduca** [comment]
How can we change that behavior?

**Comment by yufengshen** [comment]
I will put up a patch to make the latency tracking also works for mouse/keyboard events that don't cause any rendering.

crbug is here https://code.google.com/p/chromium/issues/detail?id=515553
