### ISSUE TITLE
Root-Relative Import URLs

### ISSUE THREAD

**Issue by shikexue** [google/trace-viewer#1041]
All of the import URLs are root-relative, which makes it much harder to move directories or use trace viewer in other projects. Is there any reason not to use relative URLs?

**Comment by natduca** [comment]
Does Polymer project have a convention in this regard?

**Comment by shikexue** [comment]
Yeah, everything in polymer uses relative imports as well.

**Comment by natduca** [comment]
I'm open to such a change in the future... I'd like to hear what @dj2 thinks of course.

The timing of this change, should we agree to do it, I think should carefully considered, however. Right now, we're having a lot of churn trying to prepare for node/d8 compatibility. I'd be hesitant to add more codereview burden to fixing our vulcanizer to handle relative imports properly, while also doing good reviews on the d8/node stuff. On the other hand, when d8/node compat is done, I could see this as being a nice healthy time to do the work [should we decide that it is the correct thing to do].

**Comment by dj2** [comment]
I'm fine with switching to relative as long as we can:

a- Make run_dev_server work properly. Absolute URLS made things easy here.
b- Make the vulcanizer work properly. (I think this should fall out of making run_dev_server work).
c- Figure out some kind of pre-submit so we don't accidentally add absolute URLs in the future.

**Comment by dj2** [comment]
I believe d8 already does absolute and relative URLs, so it should be fine going forward. @nedn is that correct?

**Comment by nedn** [comment]
The native load in d8 does relative path to the first file that get run. But it's simple to override load() so that it does the right thing.
load = function (file_path) {
var dir =...;
var filename = ...;
os.chdir(dir);
_actual_load(filename);
};

**Comment by Apeliotes** [comment]
As someone who has been doing a ton of refactoring recently, including moving directories around, I would actually caution against using relative imports. (Although keep in mind that this work has been in Python.)

I will agree that relative paths might make moving entire directories around easer when you have relative imports to files in said directory. But all of the imports from anything outside said directory would have to change if you were using relative imports for them, and anything importing from the directory being moved would have to be changed either way. Plus, when you move a single file that has relative imports, you then have to update all of the relative imports in said file when you wouldn't have had to do that work if they were absolute imports.

It's easier to write scripts or use search and replace for the files that are being moved if relative imports aren't being used.

This is a pretty easy topic to bikeshed about, and this isn't a topic that I feel particularly religious about. But considering how much of a trade off relative imports are, it might not be worth the work to support them.

**Comment by natduca** [comment]
I agree actually. Abs imports refactor more easily because they grep
cleanly. Thanks for pointing that out Kari!

**Comment by nedn** [comment]
This is won't fix according to Kari's comment.
