### ISSUE TITLE
Version / git tag for Homebrew

### ISSUE THREAD

**Issue by brentvatne** [google/trace-viewer#1042]
I'm trying to create a formula for the `trace2html` tool for Homebrew - we need to have a git tag or a release in order to be able to add it. See: https://github.com/Homebrew/homebrew/pull/40988

Is there any chance that we could get a quick tag thrown in with a version label so we can move forward?

Thanks for the fantastic tool!
Brent

**Comment by dj2** [comment]
Does the format of the tag matter? Like, can we just git tag 2015-06-22 or something?

@natduca

**Comment by brentvatne** [comment]
As far as I can tell, they don't have any requirements [except that it is not tagged as "unstable" or "beta"](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#stable-versions
), so a simple timestamp should be fine. /cc @DomT4

**Comment by DomT4** [comment]
> Like, can we just git tag 2015-06-22 or something?

This would be fine.

**Comment by dj2** [comment]
K, I pushed a 2015-06-23 tag up to github. It tags the code as of a4c4894801935627ff412c3cc6c3ddae96019cc5.

I wonder if we should start pushing a tag when we roll DEPS into Chromium. @natduca, @petrcermak thoughts?

**Comment by petrcermak** [comment]
I love the idea of having a tag when we roll DEPS into Chromium. Do you think it could be automatically updated?

**Comment by dj2** [comment]
Maybe, we'd have to write a script to do the DEPs update and push the tag at the same time. The DEPs and tagging would happen in different repos which makes it tricky to coordinate.

**Comment by petrcermak** [comment]
I guess this would also be complicated due to the commit queue and potential reverts. How about we have a script which **periodically polls the Chromium repository** (instead of pushing to the Trace Viewer repository)?

**Comment by natduca** [comment]
I'm not too wild about an Auto roller just for trace viewer. Catapult
should have one tho.

**Comment by brentvatne** [comment]
Thanks folks! The formula for `trace2html` is in Homebrew now

**Comment by paramaggarwal** [comment]
`brew install trace2html` works perfectly. Thanks!

**Comment by dj2** [comment]
I'm going to close this bug. If we decide to do an auto-roller that should be it's own bug. Lets keep it in mind that when we roll DEPs we should push a dated tag to github.

**Comment by brentvatne** [comment]
Thanks again for the rapid response @dj2! :tada:
