### ISSUE TITLE
Classification rule for "libc malloc" in Native heap never matches

### ISSUE THREAD

**Issue by navarroj** [google/trace-viewer#1043]
In `memory_dump_vm_regions_details_pane.html`, the part of the pattern for `'Native heap'` that tries to match `"\/dev\/ashmem\/libc malloc"` will never be triggered, since it's hidden by `"^\/dev\/ashmem"` matched by the `'Android'` case above.

**Comment by petrcermak** [comment]
This should now be **fixed**.
