### ISSUE TITLE
Text selection should be enabled for the details panel

### ISSUE THREAD

**Issue by RByers** [google/trace-viewer#1047]
It's annoying that I can't copy/paste function names out of the details panel.  Dan tells me we don't want to allow text selection generally, but should be trivial to re-enable (-webkit-user-select) on just the details panel.

**Comment by RByers** [comment]
Looks like there are a lot of 'body * { -webkit-user-select: none }' rules to work around.  I think that's overkill - can you just do 'body { -webkit-user-select: none }' and then override it later (since -webkit-user-select is inherited)?

**Comment by dj2** [comment]
You shouldn't have to work around them, the more specific selector should win. So, we just need to set it appropriately on the details panel. We do this in a few other places.

**Comment by natduca** [comment]
I wonder if this is the "cannot select across shadow dom boundaries" bug in blink?

**Comment by RByers** [comment]
> I wonder if this is the "cannot select across shadow dom boundaries" bug in blink?

I don't think so.  I was able to copy/paste just fine by disabling these CSS rules that were turning it off.

**Comment by simonhatch** [comment]
I can probably look at this, it's when you're looking at an object snapshot?

**Comment by randomascii** [comment]
This would be great to get fixed. I hit this frequently when I click on a box in the trace and then try to select the text in the details panel below. It seems odd that if I use the filter box to select all matching objects then text selection works fine.

**Comment by simonhatch** [comment]
This should be fixed, clicking on objects in the trace and the details are selectable now.

**Comment by natduca** [comment]
Thanks for fixing this, Simon!

**Comment by randomascii** [comment]
Fix looks good in canary. Thanks!
