### ISSUE TITLE
Some flow events arrows are point to the overhead slice

### ISSUE THREAD

**Issue by yuhao** [google/trace-viewer#1048]
![screen shot 2015-06-24 at 2 40 55 pm](https://cloud.githubusercontent.com/assets/989505/8342163/0e036b6c-1a7f-11e5-9b62-0b56a53221b3.png)

The flow event should be pointing to the MessageLoop::RunTask next to the overhead slice.

@dj2 @natduca

**Comment by yuhao** [comment]
What is an overhead slice, and why a flow event can point to an overhead slice?

**Comment by dj2** [comment]
The flow events don't point at anything. They're separate events. We do heuristics in trace-viewer to try to point them at things. Those heuristics don't always work correctly.

As to what an overhead slice is, you'll need grep the chromium and blink code for trace events with the name "overhead" to see what it's used for.

**Comment by yuhao** [comment]
Seems like the "overhead" thing is related to thread local event buffer. Is there a particular reason we want to report it? We could certainly keep it and deal with it when importing the trace.

**Comment by dj2** [comment]
Ah, yea, overhead is time taken for tracing to run. Yes we want to report it, but you can just turn the category off and not record it. I believe it has its own category you can disable.

**Comment by yuhao** [comment]
Yes it's trace_event_overhead. But I didn't find how to disable a particular option in command line? I am collecting for Android.

**Comment by dj2** [comment]
@skyostil is there a way to disable categories when tracing android?

**Comment by natduca** [comment]
Fixing this one seems hard. Maybe this is enough to prove that we need explicit flow events between specific slices? E.g. give slices ids, then have some other op that connects the enclosing slice to that id?

**Comment by yuhao** [comment]
Linking flow events with specific slices would make analysis way easier. The only concern is that is this nature to C++ developers who now have to explicitly worry about which slice it corresponds to when when add an flow event.

**Comment by natduca** [comment]
I'm confused. Are you saying such an api wouldn't work because of some issue with the message loop? Or are you commenting on the ergonomics of such an api?

I think its pretty clear now that next-slice matching isn't robust, ever, because it requires that you be sure that no event be placed between the end flow event and the slice start command. In practice, you can get a slice in between, so...

**Comment by yuhao** [comment]
This will be closed once #1079 is resolved, i.e., with the new flow event API, this shouldn't be an issue.
