### ISSUE TITLE
Add a "segmentation coverage" to railscore and railscore side panel

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1051]
@yuhao @benshayden wanna pick it up?

**Comment by natduca** [comment]
Lets do coverage as "amount of time"

**Comment by dj2** [comment]
Isn't amount of time traced just the model.bounds.max? We shift the timeline to zero, so the maximum of the model is the total time.

**Comment by natduca** [comment]
The purpose of segmentation is to associate each slice to an interaction record. The goal of a segmentation coverage metric is simply to monitor how many of the slices we've attributed to a given ir.

The problem with using bounds is that it has nothing to do with slices. If you have a sparse trace, but attribute everything to an IR, you'd get a low score. Or, if you had a dense trace with many threads but in a short period of time, attributing only a few slices would give you a high score.

My suggestion here is sum of time of all toplevel slices as the upper bound.

**Comment by benshayden** [comment]
Let me see if I get the idea and can communicate it or if I need some
coffee.
Take all the toplevel slices in all the threads in the entire trace. Take
the sum of their cpu time, call it totalTopLevelCpuTime.
Take all the toplevel slices that are in any IR's associatedEvents. Take
the sum of their cpu time, call it reachableTopLevelCpuTime.
Take reachableTopLevelCpuTime / totalTopLevelCpuTime, call it
RAILInteractionRecord.coverage. It'll be another number between 0 and 1,
like pain and efficiency.
Find traces where coverage is unusually low, look at the unreachable
slices, figure out what should be done with them. Maybe some of them should
be reachable but aren't, and the associatedEvents computation should find
them.
Timers will definitely not be reachable. Should we subtract them from
totalTopLevelCpuTime before computing RAILInteraction.coverage? Should we
add a T phase to RAIL for Timers? Should we add them to the
most-overlapping RAIL IR's associatedEvents? Can we trace a causal flow
event through JS to attribute each timer to a previous RAIL phase?

These are some of the questions that I imagine might be raised when we
compute and look at RAILInteractionRecord.coverage. Are they the right
questions to think about?

**Comment by natduca** [comment]
That sounds right! I like the idea of driving our work based on unusually low scores in this regard.

I'd consider duration instead of cpuDuration. I think that way if we have a giant slice that is mostly descheduled, it still counts against our score.

As far as dealing with "we can never reach X" events, lets deal with those as they arise. I think they're good individual questions to chase, and I think @yuhao is poking at them. I do hope that we'll be able to reach most events, eventually though. Again, thats a conversation for another bug, I think... :)

**Comment by natduca** [comment]
You'll want to hack rail_side_panel.html and rail_score.html
