### ISSUE TITLE
Move hooks and PRESUBMIT.py into correct folder

### ISSUE THREAD

**Issue by dj2** [google/trace-viewer#1056]
For catapult, these need to move into the tracing/ directory.

**Comment by natduca** [comment]
I've done a basic split, but think there is some important followup work here. @anniesullie @petrcermak @dj2  for advice.

There are a few lingering issues:
1. we need to stop using our own faked version of depot tools input_api. Petr, do you remember what blocks this? I've factored our wrapper into tv_input_api, which we need to ditch somehow.

2. some of the PRESUBMIT checking is still toplevel. Some of it is duplicative to depot tools "canned checks", but not all. Not sure what to do with it.

3. the one hook we have should stay toplevel: its a forced-push preventer. catapult will want to inherit this. probably the various run_tests wants to install the hook?
