### ISSUE TITLE
Move brushing_state from ui/base to ui/

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1061]
From my pov, ui/base has common stuff that isn't really tracing specific, just basic ui stuffs.

brushing_state is very tracing specific, so I tend to think it goes elsewhere. Since its part of selection controller, i'd just put it next to it, hence ui/.

@dj2 @petrcermak

**Comment by petrcermak** [comment]
Note that the selection controller is currently not in *ui/* but in *core/* instead.

**Comment by PhilBeaudoin** [comment]
I just did #1097 which is strongly related, I can do this after.
