### ISSUE TITLE
response IR mis-identifies facebook 1s navtap case

### ISSUE THREAD

**Issue by paulirish** [google/trace-viewer#1062]
There's a new trace_facebook-1s-nav-tap.json in measurmt-traces and our IRs arent' correct

![image](https://cloud.githubusercontent.com/assets/39191/8444400/f535ef4a-1f44-11e5-9e56-e5b25c87bbb9.png)

This recording was of me hitting the nav menu icon on mobile facebook.com

An early paint does happen (its the icon changing to active color), however the next paint takes ~1s. This should be a full response for that entire duration.

Most of the work is queued up by the touchend handler of the same touch.

**Comment by benshayden** [comment]
There's a single TouchStart and a single TouchEnd. My mega-CL will combine them into a single Response like you suggest. There'll still be a Load IR in parallel with that response.
Nice clean test case!

**Comment by paulirish** [comment]
> My mega-CL will combine them into a single Response like you suggest. There'll still be a Load IR in parallel with that response.

sweet. sgtm

> Nice clean test case!

I was showing one of the facebook engineers how tracing works and we randomly came across this.
