### ISSUE TITLE
Move units classes from ui/base/ to ui/units

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1064]
time span, time stamp span, etc should be in ui/units, so they can be logically visible as a module.

**Comment by natduca** [comment]
@dj2

**Comment by dj2** [comment]
You mean from ui/units to ui/base/units right? They're already in ui/units.

**Comment by natduca** [comment]
Ah, crap, you know I misunderstood this. Things are in the right place, and I got confused. I was reading table.html and thinking that it was a unit thing. Everythign is good and this bug is WontFix.
