### ISSUE TITLE
Move trace uploader to perf_insights

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1066]
Fady is on this: we're gonna move the uploader code into the insights code, per the design doc at https://docs.google.com/document/d/1-UsAgxNbu4v2TiFpOga_yAjfBm2bEbTk5MHMwz1Voig/edit?pli=1#

**Comment by fmeawad** [comment]
Working on it.

I will create a new app.yaml that belongs to performance-insights instead of just upload, and move everything else under /upload

**Comment by natduca** [comment]
Lets do /perf_insights/perf_insights/upload. This is like how we have dashboard/dashboard/, and tracing/tracing.

**Comment by fmeawad** [comment]
Fixed.
