### ISSUE TITLE
Changing TimelineView.model when something is selected doesn't clear the selection

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1067]
1. Go to http://localhost:8003/examples/trace_viewer.html and select something in the timeline.
2. Change the model being viewed using the dropdown box

Expected: the selection is cleared.
Actual: the analysis view still shows the old selection

**Comment by dj2** [comment]
If the alerts panel is open it stays open as well, even if the selected trace doesn't have that kind of analysis. It should be closed and reset as well.
