### ISSUE TITLE
Could Related Events View show related samples?

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1068]
Suppose we have this:
```
     |   |     |          |    |        <- samples
   [       a         ]
        [ b ]
```

Could the related events view have a hyperlink that allows selecting the three samples that intersect with [a]?

**Comment by natduca** [comment]
@philippebeaudoin interested?

**Comment by philippebeaudoin** [comment]
I have a working version of that but no good example trace to test it on. Is there one I'm missing in our collection of examples? If not, any hint on how I could generate one? Or should I just build a fake one by hand?

**Comment by natduca** [comment]
Try perf_sampling_trace_with_trace_events.json.gz

**Comment by PhilBeaudoin** [comment]
Works beautifully! Under review.
