### ISSUE TITLE
Increase robustness to import failures

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1069]
Right now, any failure during import prevents a user from saving a recorded trace.

This means that people can't actually give us traces that are failing to parse, when they're using chrome://tracing or chrome://inspect?tracing.

For instance, #1032 

Can we increase the robustness of profiling_view.html to this case somehow?

**Comment by natduca** [comment]
@vinterstum @anniesullie any idea who might take this? Not sure about priority relative to everything, but it'd be good to get it on someone's radar to fix in free cycles.

(@dj2 for fyi)

**Comment by anniesullie** [comment]
@fmeawad @zeptonaut do either of you have some cycles to take a look at this?
