### ISSUE TITLE
Polymerize and tidy up TimelineView

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1072]
I think its time.

**Comment by natduca** [comment]
We can avoid having to shadowify all its children by having the shadow conatin a <content> element and then continuing to attach most of the dom in the light part of the dom.

**Comment by natduca** [comment]
Next step is to convert the timeline view to be a polymer element. The initBlahButton methods can be simplified a lot.

To simplify this step, we can then put the non-polymer-ready elements [track view, basically] inside a <content> element, so shadow dom doesn't cause havoc.

**Comment by dj2** [comment]
Looks like we also need to polymerize tracing/trace-viewer.html as that inherits from TimlineView.

**Comment by dj2** [comment]
I think we need to * /deep/ even in this case. We'd need to move the timlineView and the analysis out and pull them in through <content>. But, that means we also have to duplicate that logic in the trace2html file and, probably in vulcanize.

We've got, like, half our css as * /deep/ and half that isn't at the moment ....

**Comment by natduca** [comment]
You don't need deep for elements that get projected into a shadow Dom via a
<content> element. That's the cool part that I didn't get once upon a time.

**Comment by dj2** [comment]
Yes, that part is easy.  The problem is it isn't just the track view we
need in content, it's also the analysis and the drag controller. So, we end
up taking all of the middle container and the following content. Which is
fine, except we then need to duplicate that chunk of code into
trace2html.html and probably into the vulxanize code. Which isn't good.

Dan

**Comment by natduca** [comment]
Isn't content's select argument useful here?

The analysis view is shadow Dom safe these days I fixed the issues these
back in April.

**Comment by dj2** [comment]
There are a lot of deep selectors on things like the frame viewer and the
picture debugger.

dan

**Comment by dj2** [comment]
This is now a polymer component.
