### ISSUE TITLE
New flow event API

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1079]
It seems pretty clear that we need a better flow event api, to deal with precision, and to deal with priority. Doc:
https://docs.google.com/document/d/1La_0PPfsTqHJihazYhff96thhjPtvq1KjAUOJu0dvEg/edit?pli=1#heading=h.mlpdir2vdooz

@yuhao, @vmpstr who should I assign to this bug?

**Comment by yuhao** [comment]
Flow API v2.0 CL is landed. https://codereview.chromium.org/1239593002
Flow API roadmap is at: https://docs.google.com/a/google.com/document/d/1q6Ms285pCR4iet9OyGsb6tJxyR7Ld7IeZN8YiI4jPg4/edit?disco=AAAAAXzHyTs

**Comment by yuhao** [comment]
Will close this issue when PostTask, IPC, and LatencyInfo are all migrated to use Flow API v2.
