### ISSUE TITLE
d8 jsification can use parse_html_deps directly instead of HTMLModule/generate

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1080]
Might speed it up...

**Comment by nedn** [comment]
What is this? I am about to work on #1030

**Comment by natduca** [comment]
That's good. I think you're best off doing #1030. I just had a thought of doing a quick fix to speed things up without forcing us to do typ... I am kinda lukewarm about typ given that the compat unit tests are only shortlived anyway.

**Comment by natduca** [comment]
@nedn has made absurdly good progress on #1030 so wontfix this.
