### ISSUE TITLE
Traces using inspector client shouldn't have .gz appended.

### ISSUE THREAD

**Issue by simonhatch** [google/trace-viewer#1087]
Naming was recently changed to support compressed data coming from the xhr client, but the inspector client doesn't produce compressed data (yet), so saving the trace out (incorrectly with .gz) and then loading will fail.

https://code.google.com/p/chromium/issues/detail?id=507328

**Comment by natduca** [comment]
Who is owning this? Seems like this needs an owner and p1 resolution....

**Comment by simonhatch** [comment]
Sorry, not used to Github workflow, assumed this would get closed when I landed the fix.

https://codereview.appspot.com/252070043/

**Comment by anniesullie** [comment]
For future reference, here's how to close a github issue with a commit: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by simonhatch** [comment]
Awesome, thanks!
