### ISSUE TITLE
Presubmit script checks untracked files

### ISSUE THREAD

**Issue by yuhao** [google/trace-viewer#1089]
It seems to check all the files, even untracked ones.

**Comment by petrcermak** [comment]
I investigated the issue a little bit and the reason for this is that **some of our presubmit checks** (namely <tt>tracing.build.check_gypi.GypiCheck()</tt> and <tt>tracing.build.check_modules.CheckModules()</tt> called by tracing/PRESUBMIT.py) **do *not* take into account the presubmit <tt>InputApi</tt> object**, which has a list of *affected* and *tracked* files.

To avoid this, we would need to pass the list of tracked files to these checks, which would in turn need to pass the list to <tt>tracing.TracingProject</tt>, which is responsible for recursively calculating the load sequence. In addition, there are other parts of Trace Viewer, which depend on this calculation (running D8 tests, generating chrome://tracing, ...), so we would have to change them as well (to stay consistent).

To sum up, we're in a strange situation where **some things depend on tracked files and some don't**:

  1. Things that *do* depend on tracked files:
      * <tt>build.presubmit_checks.RunChecks()</tt> presubmit check (copyright checks)
      * <tt>tracing.build.js_checks.RunChecks()</tt> presubmit check

  2. Things that *don't* depend on tracked files:
      * <tt>tracing.build.check_gypi.GypiCheck()</tt> presubmit check
      * <tt>tracing.build.check_modules.CheckModules()</tt> presubmit check (load sequence check)
      * JavaScript unit tests
      * trace2html
      * vulcanize
      * why_imported
      * benchmarks
      * generating chrome://tracing

**Do we want to make everything depend on tracked files?** Note that as a result the tool would require to always run inside a git repository (which feels a little weird).

**Comment by dj2** [comment]
I don't think we want to make everything depend on the tracked files. GypiCheck for example we want to make sure doesn't so it can catch things you missed.

**Comment by petrcermak** [comment]
I've been thinking about this and <tt>GypiCheck</tt> in fact appears to be a good example of why we **do** want presubmit to depend on tracked files. Justification:

Consider the following scenario:

  1. Create a new HTML file in Trace Viewer (e.g. /ui/tracks/un_track.html)
  2. Add an import to an existing file (e.g. add <tt>\<link rel="import" href="/ui/tracks/un_track.html"\></tt> to /ui/tracks/chart_track.html).
  3. Forget to add the new file to the repository
  4. Commit the changes
  5. Run <tt>git cl presubmit</tt>

_Desired behavior:_ Generate an error message about a missing file
_Actual behavior:_ Presubmit checks pass

**Comment by dj2** [comment]
I believe the issue with gypi check isn't that the file is untracked. The issue is that the file isn't included from anything that's reachable from the root html file.

We don't look at all files, we look at all files we find when we walk the import tree.

**Comment by petrcermak** [comment]
In the scenario I described, the untracked file **was reachable** from the root html file (assuming chart_track.html was).

**Comment by dj2** [comment]
Ah, I mis-read step 2 thinking you added chart_track into un_track. That's a bug in CheckGypi then. It should find un_track and complain even if it's untracked.

**Comment by petrcermak** [comment]
Sorry, I forgot to mention the step where I added the file to trace_viewer.gypi. In that case <tt>CheckGypi</tt> doesn't show any errors, although they would be desirable in my opinion.

**Comment by yuhao** [comment]
This seems to be an issue still?

**Comment by natduca** [comment]
@yuhao can you provide an example file you have unstaged that is causing issues?

**Comment by dj2** [comment]
As @petrcermak mentioned, any new file that isn't added into git, but is in the module include chain, won't trigger an error from update_gypi.

**Comment by natduca** [comment]
I think I'm more wondering what Yuhao's typical workflow is that causes this to happen. Maybe there's a way he can use git/git stash/barnches/etc to avoid the situation in the first place...

**Comment by yuhao** [comment]
I checked out measurmt-traces into test_data, and I have new traces under measurmt-traces. Seems like measurmt-traces is tracked.

**Comment by dj2** [comment]
As a side note, you don't need to do that. You can pass the --data-dir flag to run_dev_server and give it a path and it will use that as the source for test data. So, you can just point it at your measuremt-traces folder outside of trace-viewer.
