### ISSUE TITLE
Gypi tests failing

### ISSUE THREAD

**Issue by dj2** [google/trace-viewer#1090]
======================================================================
FAIL: test_GypiTokenizer (tracing.build.update_gypi_unittest.UpdateGypiTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dj2/Development/trace-viewer/tracing/build/update_gypi_unittest.py", line 22, in test_GypiTokenizer
    "useless data\n'group1': [\ngi", gypi_files._tokens[0].data)
AssertionError: "useless data\n'group1': [\ngi" != "useless data\n'group1': [\n"

----------------------------------------------------------------------

**Comment by qeny** [comment]
https://codereview.appspot.com/250990043/ re-enabled a disabled broken test, and before submitting I ran the tests, but then apparently accidentally committed a broken version.

Fix is simple though: https://codereview.appspot.com/252160043/

**Comment by qeny** [comment]
After that commit I ran the tests again to confirm that it's fixed.
