### ISSUE TITLE
RecordingSelectionDialog presets are going the wrong direction

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1102]
![image](https://cloud.githubusercontent.com/assets/412396/8738880/bf5bef1c-2be9-11e5-9491-2ad810ffa49f.png)

**Comment by natduca** [comment]
@anniesullie @vinterstum @simonhatch

**Comment by anniesullie** [comment]
I only had a quick moment to look at this. It looks like the styles in layer_view.css are no longer being applied. Anyone know of any changes that might have broken an include? Backing up a bit, should the styles for the option group be in that file? And if so, should it be directly included by record_selection_dialog.html?

**Comment by dj2** [comment]
The layer_view.css file shouldn't be needed for record selection dialog. If the styles were leaking over that's a bug. We should put them in the record_selection css so it's self contained.

**Comment by anniesullie** [comment]
Thanks! I'll work on this.

**Comment by anniesullie** [comment]
What is the instantiate test for this dialog?

I tried to run ui.extras.about_tracing.profiling_view_test but I ran into some issues -- see #1106

**Comment by anniesullie** [comment]
I put up https://codereview.appspot.com/255310043 for this issue.
