### ISSUE TITLE
Vsync highlighter doesn't seem to work on osx canary

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1103]
When I turn on vsync checkbox, I don't see anythign on mac.
@zeptonaut @petrcermak  any ideas?

46.0.2457.0 (Official Build) canary (64-bit)

https://drive.google.com/file/d/0B2UAouCtyY6-QlI4eThJNEtnWEU/view?usp=sharing

**Comment by zeptonaut** [comment]
I'm almost certainly responsible for this. I'll look into it.

On Thu, Jul 16, 2015 at 9:41 PM, Nat Duca <notifications@github.com> wrote:

> When I turn on vsync checkbox, I don't see anythign on mac.
> @zeptonaut <https://github.com/zeptonaut> any ideas?
>
> 46.0.2457.0 (Official Build) canary (64-bit)
>
>
> https://drive.google.com/file/d/0B2UAouCtyY6-QlI4eThJNEtnWEU/view?usp=sharing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/trace-viewer/issues/1103>.
>



-- 

Charlie Andrews | Software Engineer | charliea@google.com

**Comment by zeptonaut** [comment]
Interesting... everything seems to be working at head. That makes me not quite as confident that I'm responsible. I'm downloading Chrome Canary right now to repro.

**Comment by zeptonaut** [comment]
It seems that vsync isn't working with traces recorded from Chrome. Using Chrome Canary...

<img width="250" alt="screen shot 2015-07-17 at 1 58 02 pm" src="https://cloud.githubusercontent.com/assets/1407397/8753732/02575e80-2c8c-11e5-8b9e-91af699acf0f.png">

and the android_systrace trace that comes stock with the trace viewer repo, I was able to get vsync highlights to show up:

<img width="649" alt="screen shot 2015-07-17 at 1 58 08 pm" src="https://cloud.githubusercontent.com/assets/1407397/8753748/229d76e8-2c8c-11e5-8756-e61438e80722.png">

Using Chrome Canary and recording the trace within Chrome (enabling all categories), I wasn't able to get the vsync highlights to show up:

<img width="586" alt="screen shot 2015-07-17 at 2 02 26 pm" src="https://cloud.githubusercontent.com/assets/1407397/8753790/80f294e4-2c8c-11e5-8600-21e4bfcd473c.png">

I've never tried to get vsync highlights to show up from a Chrome recorded trace before, though. Do Chrome and Android issue the same trace events to signal vsyncs? If so, that points to a problem on the Chrome side with actually issuing events.

**Comment by natduca** [comment]
In our end state, vsync should be "detected" for all platforms --- that is, no matter where the trace came from, we should figure out where the vsync is. brianderson@ is a good person to ask for advice on finding vsync in general, and ccameron almost certainly can point you at vsync data for mac.

The reason I filed this is because we want battor ui to work for mac. Presumably, us having the vsync signal on mac is important, therefore. :)

**Comment by zeptonaut** [comment]
Yep, totally agree! I'll get in touch with them and see what the status of vsync on various platforms is.
