### ISSUE TITLE
Inconsistent unit spans in single selection analysis sub-views

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#1105]
_[breaking this out of #1057]_

The style of different unit spans is now inconsistent in many single selection analysis sub-views:

![screenshot from 2015-07-17 14 01 27](https://cloud.githubusercontent.com/assets/2546601/8747659/b5c95b76-2c8c-11e5-9be2-2c5b1765c4de.png)

The reason for this is that, unlike all other fields/units, **<tt>\<tr-ui-u-time-duration-span\></tt> changes font and text alignment**. The unbounded right alignment is especially problematic when the window is maximized.

**Comment by philippebeaudoin** [comment]
Should be fixed on TOT.
