### ISSUE TITLE
Make the timeline viewport use the new resize sensor.

### ISSUE THREAD

**Issue by benshayden** [google/trace-viewer#1109]

**Comment by benshayden** [comment]
Related: https://github.com/google/trace-viewer/issues/402

**Comment by dj2** [comment]
What is the new resize sensor? A bit more description on the bug would be useful.

**Comment by benshayden** [comment]
https://codereview.appspot.com/248060043/

**Comment by dj2** [comment]
Why was this closed? The CL doesn't seem to be landed or hooked up?
