### ISSUE TITLE
Move measurmt and test_data/ to perf-insights server

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1110]
Lets ditch the measurmt repo and test data folders. Big files in git is always discouraged, and the perf insights repo is supposed to handle this automagically. I'm not quite sure how to make all the workflows work, but I think I can make this happen.

**Comment by natduca** [comment]
@fmeawad @anniesullie fyi

**Comment by natduca** [comment]
@yuhao @dj2 hopefully when this gets done we'll have a simpler workflow for working with test assets than we do today

**Comment by dj2** [comment]
I'm not sure about moving test_data. It's very useful to have along side trace-viewer without having to do anything. As far as I understand, large files are fine, large binary files are bad. But, they're only bad when they change a lot.

Our test files don't really change, so they shouldn't be causing repo bloat, I think.

**Comment by natduca** [comment]
I understand your point of view. I do want to move measurmt traces. Those are more mutable and more voluminuous. We can figure out what to do about test_data once i have the new thing in place.

**Comment by anniesullie** [comment]
@Apeliotes is working on binary file support, FYI. I agree we should probably figure it out once the new thing is in place.

**Comment by natduca** [comment]
I need to move the measurmt parts sooner than test_data because the workflow that people have to go through to get a working RAIL data set is really really bad (clone a random repository, put it somewhere, run the dev server differently).
