### ISSUE TITLE
chrome_config shouldn't include core items

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1111]
Chrome config starts off by including core items and shouldn't. Namely:
```
<link rel="import" href="/model/model.html">
<link rel="import" href="/ui/base/ui.html">
<link rel="import" href="/ui/timeline_view.html">
```

These items are core. They shouldn't have to be included. Why are they there? @dj2 this seemed to get added in 68b31b7a873249a2ec847b9fcde4a9a2e188df10...

https://github.com/google/trace-viewer/blob/master/tracing/tracing/extras/chrome_config.html#L17

**Comment by natduca** [comment]
@egonelbre fyi

**Comment by dj2** [comment]
They were originally pulled in transitively through tracing/trace-viewer.html which doesn't exist anymore so they had to go ... somewhere. This seemed like a good place at the time. They have to exist, somewhere, for tracing to work, not sure which config they should be in.

**Comment by egonelbre** [comment]
AFAIU they should be part of lean_config -- lean is the configuration that is able to display traces.

**Comment by natduca** [comment]
so now people use timeline_view, right? Presumably that should the core things it needs. The configs should only include the optional stuff.

**Comment by natduca** [comment]
Looks this code debt is leaking into systrace now: https://github.com/google/trace-viewer/commit/a7f1c1b3abecfcc64c7561ce933e406f4d47bc7b

Looks like it trippped up @ChrisCraik earlier. We have to make this work right.

**Comment by natduca** [comment]
I think its okay for timeline_view to include these things directly.
