### ISSUE TITLE
Lets add a trace to test_data/ called rail_example.json

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1113]
Right now there is no trace in test_data that has enough to show off the rail side panel  etc. You have to get measurmt traces, or scroll thorugh the big test data list to find something to use the rail score side panel.

Can we copy a canonical trace from measurmt to test_data? @yuhao @benshayden  can one of you drive?

@philippebeaudoin fyi

**Comment by benshayden** [comment]
sfgate.json has a bunch of Responses and Idles. Does that suffice?

**Comment by natduca** [comment]
Nope. The original request was for a file called rail_example. :)

**Comment by yuhao** [comment]
The Flow API v2 is landed (#1079). The roadblock is that PostTask does not always use unique ID for each flow (#1161). Once that's sorted out, we can collect "canonical" traces that all other people can use.
