### ISSUE TITLE
Line wrapping causes text to overlap in the track header.

### ISSUE THREAD

**Issue by philippebeaudoin** [google/trace-viewer#1115]
Use ellipsis and tooltip to show the full name of the track.
![screenshot from 2015-07-21 12 43 08](https://cloud.githubusercontent.com/assets/11399419/8806742/10d5742a-2fa6-11e5-87a6-50a2b092c570.png)

**Comment by natduca** [comment]
I suspect we want to hack heading_track.html to support ellipsizing.

**Comment by philippebeaudoin** [comment]
The problem seems to be specifically with track headers using <tr-ui-a-analysis-link>, which AFAICT are headers for sample tracks.

**Comment by philippebeaudoin** [comment]
Once analysis_results is gone solving this is probably only a matter of removing the white-space styling in analysis_link.html. This will not give us ellipsis or tooltips but should remove the offensive linewrap.

**Comment by dj2** [comment]
This is the analysis link specifically, no the header track.

Dan

**Comment by philippebeaudoin** [comment]
Indeed, but the analysis link forces "white-space: normal;" to solve a problem with AnalysisResult according to the comment. However, the header track sets its children to "white-space: nowrap;" which is why other header tracks dont wrap. Letting AnalysisLink inherit white-space from its parent (as it should) will solve the problem.
