### ISSUE TITLE
Fix sizing of table in analysis view.

### ISSUE THREAD

**Issue by philippebeaudoin** [google/trace-viewer#1116]
Left-hand side of table in analysis view is too wide and shrinks the related events table on the right-hand side too much causing undesirable line wrapping.
![screenshot from 2015-07-21 12 45 02](https://cloud.githubusercontent.com/assets/11399419/8806806/5bd588fc-2fa6-11e5-9f33-0d587dd4cba5.png)

**Comment by petrcermak** [comment]
What's even worse, **the left table sometimes completely pushes the right table off the screen** (even if the window is maximized):

![screenshot from 2015-07-21 17 52 02](https://cloud.githubusercontent.com/assets/2546601/8806978/58010398-2fd1-11e5-8efe-6fc147cca9c0.png)

**Comment by philippebeaudoin** [comment]
Yuck. Any way to quickly repro this worse case?

**Comment by petrcermak** [comment]
Yes:

  1. Go to <tt>http://localhost:8003/examples/trace_viewer.html#/test_data/multiple_input_latency.json</tt>.
  2. Select everything (just drag a rectangle across the whole screen).
  3. Select the "Slices" tab in the analysis view.
