### ISSUE TITLE
Highlighting selected events does not cause any visual change.

### ISSUE THREAD

**Issue by philippebeaudoin** [google/trace-viewer#1117]
With AnalysisLink now doing highlighting on hover it's possible for a selected event to be highlighted (in addition to being selected). This causes non-highlighted events to be dimmed out but the highlighted+selected event doesn't change color. This is an issue when multiple events are selected since it's impossible to distinguish which one is highlighted+selected.

A separate but related problem is that when moving the mouse over analysis links many of events quickly toggle between their "normal" and "dimmed" color which causes a lot of visual noise. It might be better to leave every event in "normal" color and make highlighted events "super-highlighted".

In the following screenshot:
- MessageLoop::RunTask and SyncChannel::SendWithTimeout are selected
- The (invisible) mouse cursor is hovering over MessageLoop::RunTask in the analysis view
- MessageLoop::RunTask is selected+highlighted but it's the same color as simply selected.
- This causes all other events to be dimmed out (Look at the text color for "MessageL...")
- If the mouse moves to SyncChannel::SendWithTimeout then all the other events flash to their normal color and then become dimmed again.
![screenshot from 2015-07-21 12 55 54](https://cloud.githubusercontent.com/assets/11399419/8807122/5728bc8c-2fa8-11e5-973f-2bd80161bba4.png)

**Comment by petrcermak** [comment]
I think **it would be great if we had a "super-highlighted" state**! I'm convinced it would solve all our issues with the sunburst chart (see #706).

**Comment by natduca** [comment]
Yuhsss
