### ISSUE TITLE
Regression: Focus issue is seen on 'chrome://tracing' page.

### ISSUE THREAD

**Issue by simonhatch** [google/trace-viewer#1130]
Copying this over from crbug.com/513126

Reported by dchaubey@etouch.net

Chrome Version: 45.0.2454.15 (Official Build) 3a1ba3bad4f392b9c08d4c20db31560fb377558d-refs/branch-heads/2454@{#102} 32/64-bit.
OS: All(Win 7-Aero Enabled)

What steps will reproduce the problem?
1. Launch chrome and go to 'chrome://tracing' page.
2. Now press the 'Tab' key from keyboard and observe the focus.

Focus doesn't go to 'Record' button.
Focus should go to 'Record' button.

**Comment by natduca** [comment]
Thanks! I'm a bit backed up so haven't been able to look at this...

**Comment by natduca** [comment]
Seems like its focusable but the focus ring isn't showing up...
