### ISSUE TITLE
RAIL score should consider checkerboarding.

### ISSUE THREAD

**Issue by vmpstr** [google/trace-viewer#1132]
When calculating RAIL score we should account for checkerboarding as a source of user unhappiness.

There's a couple of traces that have this information:

"cc", "PictureLayerImpl::AppendQuads checkerboard"
and "benchmark", "BenchmarkInstrumentation::ImplThreadRenderingStats",

seem to both provide this. If we need more, we can add more useful format/traces.

**Comment by natduca** [comment]
@benshayden can advise you on how to implement this if you two wanna chat a bit...

**Comment by benshayden** [comment]
AnimationInteractionRecord.normalizedUserPain is not implemented yet. When Ned ports the smoothness metric to javascript, then it'll use that.
The AIR's associatedEvents should contain the checkerboarding information.
I'm not sure exactly how the smoothness metric will work or how the checkerboarding information could be accounted for, but those are the puzzle pieces.
