### ISSUE TITLE
Naming conventions for catapult third_party folders: include version or not?

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1136]
trace-viewer third party libs (and chromium) do not include the version numbers in third_party folders. e.g. tracing/third_party/chai.

catapult/third_party seems to have a mix: google-api-python-client-1.4.0 but then polymer.

@qeny @anniesullie can we normalize?

**Comment by anniesullie** [comment]
Whoops! Thanks for pointing this out. @qeny can you take this one?

**Comment by qeny** [comment]
Yep -- I was wondering what is preferable.

Including version numbers allows keeping multiple versions at the same time, but no version numbers would look cleaner and would mean smaller changes whenever updating anything.

Removing version numbers OK?

**Comment by natduca** [comment]
Let's try for no numbers. If we have version conflicts we can do numbering
and have a tracing bug for deduping

**Comment by anniesullie** [comment]
sgtm
