### ISSUE TITLE
Remove comment recently added that may not be accurate

### ISSUE THREAD

**Issue by rathnaprabhu** [google/trace-viewer#1140]
I added this comment in a recent check-in. Thinking about it more, I'm not sure if the array is actually sorted by frequency. If in-fact it was based on frequency, it would be really hard to keep this statement true as there is no mechanism to monitor/measure the frequency & keep the array updated.
I suggest removing this comment - to avoid misleading the code-reader.

// Array sorted by frequency of occurrences - most frequent ones first.
      var knownFieldNames = ['traceEvents', 'systemTraceEvents', 'samples',
          'stackFrames', 'traceAnnotations', 'battorLogAsString'];

**Comment by dj2** [comment]
Just sort the items in the list. They were in order of when they were added.

**Comment by rathnaprabhu** [comment]
Dan, I made it a dict based on CL comments.
