### ISSUE TITLE
Remove trivial @fileoverview comments throughout codebase

### ISSUE THREAD

**Issue by zeptonaut** [google/trace-viewer#1142]
We have lots of trivial `@fileoverview` comments in the codebase. They look like the following:

In `selection_state.html`:
```javascript
/**
 * @fileoverview Provides the SelectionState class.
 */
```

These comments are unnecessary and should be removed.

This bug was suggested by @natduca.

**Comment by natduca** [comment]
This will be wonderful to purge.
