### ISSUE TITLE
RAILIRFinder: Compute IdleIR.normalizedEfficiency

### ISSUE THREAD

**Issue by benshayden** [google/trace-viewer#1149]
Maybe IdleIRs need some associatedEvents so that their cpuDurations can be summed and counted against the IdleIR's efficiency?
Should overlapping unassociated events be added to IdleIR.associatedEvents?

**Comment by natduca** [comment]
Yeah, I think thats the right idea. The key thing is coming up with an actual algorithm for finding the associated events for the idle...
