### ISSUE TITLE
TImeline track view selection drag box handle is broken

### ISSUE THREAD

**Issue by benshayden** [google/trace-viewer#1151]

**Comment by benshayden** [comment]
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
Polymer.setDragBoxPosition_ @ timeline_track_view.html:785
Polymer.onUpdateSelection_ @ timeline_track_view.html:981
Polymer.onMouseMove_ @ mouse_mode_selector.html:356

**Comment by natduca** [comment]
@dj2 i think this is fallout from removing the header track
