### ISSUE TITLE
analysis view no longer summarizes events matching search term

### ISSUE THREAD

**Issue by ChrisCraik** [google/trace-viewer#1152]
At one point, searches in the top right search box would populate the analysis view with the list of all slices/events, as though they had been selected.

Maybe we could bring this back at a lower priority than selection - if you search without a selection, the events matching the search populate as though they've been selected.

Was useful in seeing a lot of specific data about regular events without having to manually select them all.

**Comment by petrcermak** [comment]
I think this is a **duplicate** of #997.

**Comment by ChrisCraik** [comment]
Yep, thanks.
