### ISSUE TITLE
RAILIRFinder: MouseDown Responses

### ISSUE THREAD

**Issue by benshayden** [google/trace-viewer#1153]
Usually, MouseDowns and TouchStarts do not update the screen. However, it is possible for a page to hook these events and do something.

E.g. http://lushprojects.com/circuitjs/circuitjs.html
Edit the switch to be Momentary so that it changes state on mousedown and mouseup rather than just mouseup.

RAILIRFinder should look through MouseDowns' and TouchStarts' associatedEvents to see if a javascript listener or CSS :active style updates the page, and create a Response ProtoIR if it does.

A new method on InputLatencyAsyncSlice might be useful for searching associatedEvents for V8 and frame events.

**Comment by benshayden** [comment]
https://github.com/natduca/measurmt-traces/blob/master/desktop/trace_mousedown-response.json

data:text/html,<body style="background-color: blue;"><script>window.onmousedown=function(){document.body.style.backgroundColor='green';};window.onmouseup=function(){document.body.style.backgroundColor='blue';}</script>

**Comment by natduca** [comment]
To clarify, the situation here is that there isn't a latencynfo created for the mousedown case?

**Comment by benshayden** [comment]
No, MouseDowns do create InputLatencyAsyncSlices.
The issue is that RAILIRFinder ignores them because they usually do not cause any visual changes (click events are dispatched on MouseUp, not MouseDown), but it's possible for sites to script MouseDown to cause visual changes. So MouseDowns should sometimes be ignored and should sometimes translate into Responses.

**Comment by natduca** [comment]
Sounds like we should take #1040 and this bug and merge them together into a conversation amongst stakeholders about whether we're using the right event stream, and understand what "not causing rendering" means for RAIL. I tend to think the "Response" to a click handler is the acking of the event, even if it doesn't cause visual change.... meaning mousedown is always a response, but maybe I'm missing something.

**Comment by benshayden** [comment]
I thought RAIL was user-centric, not Chrome-centric. A Chrome-centric Response IR could mean that Chrome has finished acknowledging an input event, but a user-centric Response IR seems to imply that the screen has updated to reflect something the user did, so that if the screen doesn't update, then there was no Response IR.

**Comment by natduca** [comment]
Even if the screen didn't update, the mouse was clicked. The user did that for a reason, almost certainly. We should track the work for it.
