### ISSUE TITLE
Declutter trace-viewer visuals

### ISSUE THREAD

**Issue by egonelbre** [google/trace-viewer#1156]
Most of the UI has grown organically over time and it would look nicer if we "normalize" it.

This discussion started in issue https://github.com/google/trace-viewer/issues/906

Here's my mockup of the goal https://dl.dropboxusercontent.com/u/4300994/Go/trace-viewer/index.html (if you cannot access dropbox then https://drive.google.com/open?id=0BzlWdYwt6L4RR1FvUnd0c1dOM2s).

![2015-07-29 14_34_47-tracing](https://cloud.githubusercontent.com/assets/192964/8956481/010d69a8-35ff-11e5-9af8-f664fad640e6.png)

My plan is to piece by piece start normalizing the "UI" look and in the process create a short cheat-sheet for choosing colors and styles when creating new items.

**Comment by petrcermak** [comment]
I really like the mock (especially getting rid of the floating controls, which always seem to end up covering the most important part of the trace). My suggestion would be to move the search box to the top (to be consistent with Ctrl+F in Chrome).

**Comment by egonelbre** [comment]
@petrcermak adjusted
![2015-07-29 15_50_39-tracing](https://cloud.githubusercontent.com/assets/192964/8957804/9e66ad90-3609-11e5-9f78-0103e13f5088.png)

**Comment by petrcermak** [comment]
Thanks. It looks **perfect** now!

**Comment by natduca** [comment]
Copying the find box from chrome at first seems neat, but then over time you realize that that ui design does not provide us with a mechanism for options/etc. Its a minimalist find.

As @skyostil can testify, we're having problems with find performance. I'd vastly prefer we plan to make find be a side panel [think: web tracing framework], or an expandable thing like the console [think: sublime].

Try out find here: http://google.github.io/tracing-framework/bin/app/maindisplay.html?url=..%2F..%2Fresources%2Ftraces%2Fblk-server.wtf-trace

**Comment by egonelbre** [comment]
![2015-07-30 08_43_16-sublime](https://cloud.githubusercontent.com/assets/192964/8976545/1715629e-3697-11e5-802b-c8d1cb039d84.png) and 
![2015-07-30 08_53_23-side](https://cloud.githubusercontent.com/assets/192964/8976626/7dd65d66-3698-11e5-8c17-e14e74fce84b.png)

https://dl.dropboxusercontent.com/u/4300994/Go/trace-viewer/sublime.html and https://dl.dropboxusercontent.com/u/4300994/Go/trace-viewer/side.html

@natduca I definitely like the side-panel better. It can provide more use than either sublime or chrome search.

**Comment by anniesullie** [comment]
@zeptonaut FYI on UI mocks

**Comment by natduca** [comment]
@ChrisCraik fyi
