### ISSUE TITLE
Make it easy to manually generate regression test for rail_ir_finder based on real traces. 

### ISSUE THREAD

**Issue by philippebeaudoin** [google/trace-viewer#1157]
This should allow us to build regression tests from real traces encountered in the wild. Probably needs to extend rail_ir_finder_test.html.

@benshayden

**Comment by philippebeaudoin** [comment]
Or probably ir_verifier_test_helper.html which should land soon.

**Comment by natduca** [comment]
I'd be down with a button in railscoresidepanel saying "create bug" that creates some js as string then shows it in a overlay dialog.

**Comment by benshayden** [comment]
Started https://codereview.appspot.com/259050043
Not yet ready for review.
