### ISSUE TITLE
Flow IDs are not unique and some "f" flows do not have matching "s" phase and vice versa

### ISSUE THREAD

**Issue by yuhao** [google/trace-viewer#1161]
I reported it on Chromium code review, but thought it was worth cross-posting it here.

https://code.google.com/p/chromium/issues/detail?id=515720

**Comment by yuhao** [comment]
@natduca

**Comment by yuhao** [comment]
A few more investigations.

1. There is always only one repeated ID, with the name "TaskQueueManager::PostTask".

2. The repeated ID is used as the "s" phase (flow producer).

3. For those "f" phase flows that do not have a matching "s" phase, seems like they should have been matched by the repeated ID.

**Comment by natduca** [comment]
Did reverting the patch that @skyostil mentioned help?

**Comment by yuhao** [comment]
Automatic revert didn't work. Seems like a fix of that is forthcoming. If that doesn't happen today I will try to manually revert it (with care).
