### ISSUE TITLE
tracing python code adds toplevel to sys.path

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1162]
The tracing/ folder's python code points at the top of the repo, so to get to tracing/tracing_project.py, its referred to as tracing.tracing_project.

This is nice, in that tracing.build is unambiguous.

But, this also means that folders like perf_insights  (and dashboard) are no longer the "root" of their namespace. This poses issues, I think, for appengine integration: appengine seems to view the serving directory of app.yaml as the top_dir their python namespace. This means that perf_insights/perf_insights/__init__.py is "perf_insights" from the point of view of appengine. BUT, if we copy the tracing/ folders approach, then **this same directory is perf_insights.perf_insights from the perspective of local python code**. This is quite problematic.

My preference here is that our python modules do not start at the root, but down one. E.g. the toplevel directories are projects, not pieces of a global namespace. If telemetry and tracing want to talk to each other, then we have to put the different projects into the sys.path.

@dj2 @anniesullie is this consistent with your preferences?

**Comment by anniesullie** [comment]
This sounds like the right way to go. @nedn @Apeliotes do you see any potential issues for telemetry?

**Comment by nedn** [comment]
Telemetry has been using sys.path for a while, so I don't see any potential issues.
I like this also because it enforces clearer boundary between projects.
