### ISSUE TITLE
DEPS roll blocked on licensecheck issues

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1164]
Sigh.

@nedn how'd we fix the licensecheck stuff last time? suppressions?
@anniesullie one downside of being in chrome's third_party is the licensecheck script, which is meant for shipped code managment.

**Comment by nedn** [comment]
Yeah, https://code.google.com/p/chromium/codesearch#chromium/src/tools/checklicenses/checklicenses.py&l=105

**Comment by natduca** [comment]
Basically we need to modify that script so that it knows to ignore our various third_party directories.

**Comment by natduca** [comment]
@nedn can advise more but
i believe you cd third_party/trace-viewr  && git checkout origin/master
then you run $chrome/src/tools/checklicenses/checklicenses.py
and it'll scream about our stuff

**Comment by philippebeaudoin** [comment]
Fixed in:
https://codereview.chromium.org/1265043002
And DEPS rolled in:
https://codereview.chromium.org/1268493007/
Seems to be holding up, closing.
