### ISSUE TITLE
Selecting a slice in a trace with many flow events can be slow.

### ISSUE THREAD

**Issue by philippebeaudoin** [google/trace-viewer#1167]
In the attached trace [1] selecting almost any slice in the browser process will lead to a slight but noticeable slowdown from the click to the moment the slice is highlighted.

Possible ideas to improve that:
1) Remove the full transitive flow closure link in the analysis pane;
2) Process the closure in an async/idle job.

My favorite idea is (2) but I don't know how well this would work with AnalysisLink which expects an EventSet to be available synchronously. Maybe disable the link (or attach it to an empty EventSet) until the real EventSet is computed?

[1] https://drive.google.com/open?id=0Bwye9Aa8pAMnc3p2eE0tTGM2OWc

**Comment by natduca** [comment]
I'd have the whole panel construction be two step: one, figuring out
things, two creating the contents of the table. You could make a dumb
spinner to show while the panel is constructing.

**Comment by natduca** [comment]
One side comment: we probably have to keep this p2 compared to weather
report tasks.

**Comment by philippebeaudoin** [comment]
Spent some time Friday working on this and have a pretty neat working solution using approach (2). It's similar to what you propose above. I'll send it for review but will de-prioritize it if it blocks in any way.
