### ISSUE TITLE
system hang after open 2nd trace file

### ISSUE THREAD

**Issue by lindongw** [google/trace-viewer#1178]
repro step:
1. chrome://tracing/
2. click load and select 1 trace file
3. click load agai, system hang
env:
windows 10 
Version	10.0.17763 Build 17763

**Comment by randomascii** [comment]
What do you mean by a system hang? Do you mean that your whole computer hangs?
Does the system recover from the hang ever?
What type of computer (hard-drive type, amount of RAM) do you have?

I don't think that this is a tracing or a Chrome bug. I just tested repeatedly loading traces and saw no problems. It may be that you have a driver bug which Chrome is triggering (if it is a full system hang) or else you are running out of memory.

**Comment by lindongw** [comment]
probably my OS issue, i tried on other machine, it works fine.
closing
