### ISSUE TITLE
linux perf events need categories

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#126]
_From [sleffler@chromium.org](https://code.google.com/u/sleffler@chromium.org/) on September 12, 2012 10:33:30_

System trace events need to be created with a category.  Suggestion was to use kernel, possibly w/ a subcategory; e.g. kernel:gfx.

_Original issue: http://code.google.com/p/trace-viewer/issues/detail?id=120_

**Comment by dj2** [comment]
Is this still an issue with the way systrace events are created? Is it a bug in trace-viewer or the systrace script?

**Comment by natduca** [comment]
The importer just doesn't pass in categories

**Comment by fmeawad** [comment]
+ @wangzhen127
