### ISSUE TITLE
Scale canvas context to devicePixelRatio only once

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#356]
_From [egraet...@chromium.org](https://code.google.com/u/105935940897958904841/) on July 30, 2013 02:05:47_

When working on the ruler track recently, I had to deal with some hiDPI specific cases on the canvas. This is a pain, because I need to test on a hiDPI device separately.

I was wondering if it's possible to just scale the canvas context by device scale once. I found a nice article by @aerotwist: http://www.html5rocks.com/en/tutorials/canvas/hidpi/ Can we use this approach for trace-viewer?

_Original issue: http://code.google.com/p/trace-viewer/issues/detail?id=351_

**Comment by benshayden** [comment]
I don't see backingStorePixelRatio or anything like it on CanvasRenderingContext2D in chrome 45.0.2427.10 dev on a Pixel, where devicePixelRatio is 2. Was the feature removed?

**Comment by benshayden** [comment]
It was removed: https://codereview.chromium.org/215193002
What do you want to do?

**Comment by natduca** [comment]
Not sure what this bug is about. I think we should mark this bug closed... I believe in the medium term we should consider a rewrite of the tracks codebase to be 100% canvas, which would subsume this bug. But thats for another day.

**Comment by dj2** [comment]
When you say 100% canvas, do you mean the bits of DOM we draw on top to show like the process titles and things like that?

This bug was, I believe, about that fact that we multiple things by device scale in several places. It would be better to scale the canvas once and remove all of the other scallign calls.

**Comment by natduca** [comment]
Yes. The question is, should we keep this bug if we plan to do a bulk cleanup of the track implementation?

**Comment by dj2** [comment]
I think so, we're still going to have to deal with HiDPI. Would be nice if we could move that to one place and not have to think about it everywhere.

**Comment by paullewis** [comment]
Yeah, this approach has served me very well:

https://github.com/GoogleChrome/guitar-tuner/blob/master/src/elements/audio-visualizer/audio-visualizer.js#L99-126

Kind of glad we don't have to worry about the backingStoreRatio to devicePixelRatio conversion anymore! Well, it was only a Safari thing IIRC.
