### ISSUE TITLE
removeEventListener in camera.js

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#399]
_From [johnjbar...@chromium.org](https://code.google.com/u/102793569239199088523/) on August 15, 2013 15:00:35_

Nat says that
41     window.addEventListener('resize', function() {
  42       delete this.maximumPanRectCache_;
  43     }.bind(this)); https://codereview.appspot.com/12603050/diff/24001/src/ui/camera.js?column_width=80 can leak memory.

_Original issue: http://code.google.com/p/trace-viewer/issues/detail?id=394_

**Comment by dj2** [comment]
Looks like this isn't relevant anymore as I can't find that code.
