### ISSUE TITLE
Improve workflow for getting to about:tracing for WebView and Android

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#419]
_From [nd...@chromium.org](https://code.google.com/u/102435256078839283966/) on August 29, 2013 12:55:46_

Integrating with chrome://inspect  seems like the most promising avenue [despite my previous yammering otherwise].

_Original issue: http://code.google.com/p/trace-viewer/issues/detail?id=414_

**Comment by dj2** [comment]
This is done isn't it?

**Comment by natduca** [comment]
Yeah
