### ISSUE TITLE
Save trace data in a compressed file.

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#429]
_From [dsinclair@chromium.org](https://code.google.com/u/dsinclair@chromium.org/) on August 30, 2013 08:47:25_

Currently when you save a trace it dumps out the raw JSON data. We should instead compress that data to make it smaller.

_Original issue: http://code.google.com/p/trace-viewer/issues/detail?id=424_

**Comment by simonhatch** [comment]
Hey I added this recently, didn't see the bug associated with it though!
