### ISSUE TITLE
Error occured at /json/categories at chrome://tracing/tracing.js:5194:31

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#538]
_From [pasko@chromium.org](https://code.google.com/u/pasko@chromium.org/) on February 13, 2014 15:44:42_

I get the message as in the subject line when I click on "Record" in about:tracing.

Google Chrome	34.0.1825.4 (Official Build 249291) dev
OS	Linux 
Blink	537.36 (@166573)
JavaScript	V8 3.24.32
Flash	12.0.0.44
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1825.4 Safari/537.36
Command Line	 /usr/bin/google-chrome-unstable --user-data-dir=/home/pasko/.config/google-chrome-unstable --flag-switches-begin --ignore-gpu-blacklist --flag-switches-end

_Original issue: http://code.google.com/p/trace-viewer/issues/detail?id=533_

**Comment by ariccio** [comment]
I may have found something useful. On hitting `r` to start a trace, I saw this in `sawbuck`:

```
VERBOSE	49924	48704	13:35:53-569		0	Upload finished with net error 0 and HTTP response code 200
VERBOSE	49924	48704	13:35:54-342		0	OnResponseStarted: chrome://tracing/json/end_recording
VERBOSE	49924	48704	13:35:54-343		0	OnReadCompleted: "chrome://tracing/json/end_recording" bytes_read = 9
VERBOSE	49924	48704	13:35:54-343		0	OnReadCompleted: "chrome://tracing/json/end_recording" bytes_read = 0
VERBOSE	49924	48704	13:35:54-343		0	ResponseCompleted: chrome://tracing/json/end_recording
VERBOSE	49924	48704	13:35:54-345		0	OnResponseStarted: chrome://tracing/json/categories
VERBOSE	49924	48704	13:35:54-346		0	OnReadCompleted: "chrome://tracing/json/categories" bytes_read = 9
VERBOSE	49924	48704	13:35:54-346		0	OnReadCompleted: "chrome://tracing/json/categories" bytes_read = 0
VERBOSE	49924	48704	13:35:54-346		0	ResponseCompleted: chrome://tracing/json/categories
```

I think that means a `FAILED` path (via 230) through `OnBeginJSONRequest` ( notice that `"##ERROR##"` is exactly 9 characters/bytes long! ), followed by a second `FAILED` path (via 211) through `OnBeginJSONRequest`. 

I think that the offending function/class/object/whatever is `XhrBasedTracingControllerClient.prototype`. 


I set a few billion breakpoints, and stepped through in the debugger. Here are some screenshots of the process. They're (hopefully) in order:

![chrome_tracing_bug_good_breakpoints_1](https://cloud.githubusercontent.com/assets/2142308/6520423/7d139f2e-c393-11e4-81e0-870824e8929d.PNG)
![chrome_tracing_bug_good_breakpoints_2](https://cloud.githubusercontent.com/assets/2142308/6520429/83d5e8d0-c393-11e4-9e93-a8773613d59f.PNG)
![chrome_tracing_bug_good_breakpoints_5](https://cloud.githubusercontent.com/assets/2142308/6520435/8e149df0-c393-11e4-9d62-0c43a0a987ea.PNG)
![chrome_tracing_bug_good_breakpoints_6](https://cloud.githubusercontent.com/assets/2142308/6520441/98954a86-c393-11e4-88ec-e0a474f9ebdb.PNG)
![chrome_tracing_bug_good_breakpoints_8](https://cloud.githubusercontent.com/assets/2142308/6520444/a2ec5650-c393-11e4-8dd2-b265eeff7ed2.PNG)
![chrome_tracing_bug_good_breakpoints_9](https://cloud.githubusercontent.com/assets/2142308/6520445/abcdea72-c393-11e4-9de1-78b7d7199fee.PNG)
![chrome_tracing_bug_good_breakpoints_13](https://cloud.githubusercontent.com/assets/2142308/6520457/da3cbbb8-c393-11e4-94bd-18b1d6db55a1.PNG)
![chrome_tracing_bug_good_breakpoints_14](https://cloud.githubusercontent.com/assets/2142308/6520459/e5ec16e8-c393-11e4-9405-ef367af8ab42.PNG)
![chrome_tracing_bug_good_breakpoints_15](https://cloud.githubusercontent.com/assets/2142308/6520460/eb16d572-c393-11e4-9ff1-7a28e1ba9c7d.PNG)
![chrome_tracing_bug_good_breakpoints_16](https://cloud.githubusercontent.com/assets/2142308/6520465/fbcbb5f4-c393-11e4-9a28-37058736d369.PNG)
![chrome_tracing_bug_good_breakpoints_17](https://cloud.githubusercontent.com/assets/2142308/6520466/026d2cb2-c394-11e4-832a-ab46c2cbae50.PNG)

**Comment by ariccio** [comment]
### A word of warning for those who lack experience with the JS debugger in Chrome:

I was quite frustrated when my breakpoints were mysteriously failing, apparently because I'd clicked the Pretty print button.
![chrome_tracing_bug_bad_breakpoints](https://cloud.githubusercontent.com/assets/2142308/6520482/54d33c58-c394-11e4-9cd5-6b0d7d6fb8c6.png)
*.....I swear to god, after setting a million breakpoints in the formatted file, I was furious.*


( spec. thanks: @randomascii )

**Comment by natduca** [comment]
I think this is "working as intended"... in tracing, we actually stop tracing when you press 'r' in case it was previously left running:
https://github.com/google/trace-viewer/blob/master/trace_viewer/extras/about_tracing/record_and_capture_controller.html#L84

Does that make sense?

**Comment by natduca** [comment]
The original issue, I think is fixed... this was the mac nsplugin bug that was chased down by our devtools team. Or, ariccio, are you still seeing this issue manifesting?

**Comment by dj2** [comment]
I believe this is currently being seen by @randomascii but I'm not sure of the version in question.

**Comment by randomascii** [comment]
@ariccio is still seeing this bug, as of a week ago. I haven't seen it myself, just heard of it through him. @ariccio was seeing it on OSX. When was it fixed?

**Comment by ariccio** [comment]
I'm not sure [that](https://github.com/google/trace-viewer/issues/538#issuecomment-77707677) makes sense.

I've just checked, and can confirm that I can record multiple traces, by starting a trace, stopping it, and starting a new one... **BUT** if I close the tracing window (not sure if whole window or just tab) I hit the issue.

My build is `40.0.2214.115`, release.

**Comment by ariccio** [comment]
> @ariccio was seeing it on OSX.

Wait what? No, I wasn't.

Lol no idea where that one came from.

**Comment by natduca** [comment]
@ariccio, what os? Can you give specific steps for a repro up to the point that you get the error? We're always happy to fix something but I'm having trouble from the thread figuring out the exact sequence of things to do to get your issue...

**Comment by randomascii** [comment]
Apologies for the OSX claim. There was supposed to be a 'not' in there.

I just checked the ETW trace and @ariccio is running Windows 8.1 Pro.

**Comment by natduca** [comment]
Lets mark this fixed and open a fresh bug if we get new activity.
