### ISSUE TITLE
search box doesn't work for category names

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#539]
_From [fjhenig...@chromium.org](https://code.google.com/u/104377040047811835234/) on March 16, 2014 15:36:13_

e.g. TRACE_EVENT0("zcopy", "BindTexImage") is executed during a trace,
I type 'zcopy' in trace viewer search box and get zero hits, then type 'BindTexImage' and get some hits.

_Original issue: http://code.google.com/p/trace-viewer/issues/detail?id=534_

**Comment by kphanee** [comment]
Added a patch for it @ https://codereview.appspot.com/212290043. PTAL!

**Comment by kphanee** [comment]
@dj2 , @natduca : Time for small review @ https://codereview.appspot.com/212290043 ??

**Comment by dj2** [comment]
I believe this is now fixed.
