### ISSUE TITLE
linux_kernel_importer does not set cpuStart/cpuDuration values on slices

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#559]
_From [nd...@chromium.org](https://code.google.com/u/102435256078839283966/) on May 09, 2014 02:01:10_

Slices created by the linux importer only have all times. This breaks any math that is done based on thread times.

We should probably compute the cpu times based on the scheduler data as a new step in LinuxPerfImporter.finalize

_Original issue: http://code.google.com/p/trace-viewer/issues/detail?id=554_

**Comment by ChrisCraik** [comment]
Nat - now with https://github.com/google/trace-viewer/commit/2a96508384b0804e5ddda1c77e23dee56c7c214f, is there any more to do here ?

**Comment by natduca** [comment]
I think we can mark this fixed!
