### ISSUE TITLE
Make TraceViewer polymer component

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#583]
_From [nd...@chromium.org](https://code.google.com/u/102435256078839283966/) on August 01, 2014 15:51:36_

We should expose standalone_timeline_view.html as a polymer component. And maybe just rename it to be trace_viewer.html.

_Original issue: http://code.google.com/p/trace-viewer/issues/detail?id=578_

**Comment by dj2** [comment]
I'm going to close this. The timeline view is polymer and that can be embedded.
