### ISSUE TITLE
malformed HTML when thread names include double quotes

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#588]
_From [hasin...@google.com](https://code.google.com/u/104989367987927762730/) on August 12, 2014 18:40:55_

When thread name include double quotes ("), trace.html can't be opened, because the HTML is malformed. The messages from the Chrome developer console is:

Uncaught SyntaxError: Unexpected identifier /usr/local/google/home/tianxin/android/broken_trace.html:43781
Uncaught ReferenceError: linuxPerfData is not defined 

Example bad line:
           <...>-1214  (-----) [001] d..4  1532.059330: sched_wakeup: comm=Task system "AE pid=3317 prio=120 success=1 target_cpu=001\n\

Every single line where the thread name has double quotes seems to barf at the point where the quotes should've been terminated. What version of the product are you using? On what operating system? Android KK MR1

_Original issue: http://code.google.com/p/trace-viewer/issues/detail?id=583_

**Comment by nrichards** [comment]
Please let me know if this is not the repository for this issue. 

I have a similar issue as @natduca - just with _two_ quotes.

I systrace'd (write to trace_marker) some logs with two matching quotes ( "my_stuff" ) in them, create a trace.html with `android-sdk/platform-tools/systrace/systrace.py -t 5 -o ~/trace.html` and BOOM, no output plus a JavaScript exception talking about `Uncaught ReferenceError: linuxPerfData is not defined`.

Expected that the trace generator would sanitize the text before it writes to the HTML file.

Using Android Monitor from SDK Tools 24. UPSTREAM_REVISION = 775. systrace.py shasum of 9232ea19a8ec6d665129655c7e993e588a05954b.

**Comment by nrichards** [comment]
Note my use-case for this is to help correlate "what is happening when", by passing (tee'ing) existing debug log application messages into systrace of a foreign codebase. Existing debug log messages are a quick way to correlate to system activity graphs.

**Comment by natduca** [comment]
You're on the right repo, though fixing this short term is gonna take a while to roll into your sdk, this is the right place to begin fixing. Can you attach a file with a repro so I can write a fix and test and such?

**Comment by nrichards** [comment]
Thanks, great.

What kind of file to attach? I'm unsure since my SDK looks very different from the files I see here in `trace-viewer`.

A generated HTML? => https://gist.github.com/nrichards/14b04e336662c7bdae07 (see nearly the EOF)

**Comment by dj2** [comment]
This, typically, isn't fixable on the trace-viewer side. It will need to be fixed in the script which generates the HTML to go through and escape any " or ' character (and possibly others?).

**Comment by natduca** [comment]
Thanks for the repro! Dan, you're right that this is the wrong techncial
repo, but the other one is in aosp and I'm hacking on it anway so I figure
we can at least track this here for now...
