### ISSUE TITLE
Instant trace events disappear when you zoom in

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#601]
_From [danakj@chromium.org](https://code.google.com/u/danakj@chromium.org/) on August 22, 2014 08:28:05_

Capture a trace with instant events, as you zoom in they disappear entirely.

what labels/people do i add to this?

_Original issue: http://code.google.com/p/trace-viewer/issues/detail?id=596_

**Comment by randomascii** [comment]
Also a duplicate of #366

**Comment by dj2** [comment]
Closing as a dup of 366.
