### ISSUE TITLE
tvcm.unittest -> karma+mocha+chai for test harness

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#609]
_From [nd...@chromium.org](https://code.google.com/u/102435256078839283966/) on September 03, 2014 22:28:12_

This is emerging as the prevalent formula for infra projects, a la https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Tools/GardeningServer/README Lets switch to it.

_Original issue: http://code.google.com/p/trace-viewer/issues/detail?id=604_

**Comment by natduca** [comment]
@qeny fyi

**Comment by eakuefner** [comment]
Pre-emptively self-assigning for the hackathon

**Comment by natduca** [comment]
https://docs.google.com/a/chromium.org/document/d/1t8l1KbvAywkZrySpsrp7RBH5Xvm-KMPUxkR-QVooP-Y/edit
