### ISSUE TITLE
Loading v8.log no longer shows all the information

### ISSUE THREAD

**Issue by thlorenz** [google/trace-viewer#622]
In a previous version of Chrome I was able to load `v8.log` and see a callgraph similar to the below including v8 events like `GC::Scavenger` in the band at the bottom.

![](https://cloud.githubusercontent.com/assets/192891/3352533/218bc24a-fa4d-11e3-8b00-3eba3161a3f9.png)

[related info](https://github.com/thlorenz/v8-perf/issues/4)

I also was able to navigate/search the results and determine how often each function got called, how long each call took, etc.

Starting about 2 months ago loading the same `v8.log` files don't show the desired results anymore. It's not showing any v8 events and the callgraph display is jacked. 
Producing a fresh `v8.log` by rerunning the same script described in the above linked issue didn't help either.

Even loading the [`v8.log` found inside the tests](https://github.com/google/trace-viewer/blob/master/test_data/v8.log) of this repo yields an incomplete view as well.
It seems only v8.timers are shown. The band at the bottom that shows Events is totally missing. Interactions like zooming are not working properly with the mouse (via the DOOM keys works fine).

![screen shot 2014-09-29 at 2 12 47 pm](https://cloud.githubusercontent.com/assets/192891/4446811/97f9f81a-4805-11e4-8c8e-dd7e36136059.png)

Below is a screenshot of producing a fresh `v8.log` for the same app as was done to produce the screenshot at the very top.
However again the Events band is totally missing and interactions like zooming don't work as before.

![screen shot 2014-09-29 at 2 17 36 pm](https://cloud.githubusercontent.com/assets/192891/4446820/a12a38be-4805-11e4-8477-b7f5f468195e.png)

If you like I can provide that `v8.log` file which was produced with a `node.js` version running `v8: '3.25.30'`.

I'm on OSX `10.9.5` using Chrome `Version 37.0.2062.124`, but have also tried with Chromium `Version 39.0.2167.0
` with similar results.

**Comment by fmeawad** [comment]
This view has been replaced by a the sunburst in the analysis view, but we might bring it back in another form (unrelated to how it appears in dev-tools)

**Comment by fmeawad** [comment]
I am working on a tree-view representation (instead of the sunburst)

**Comment by natduca** [comment]
Awesome, lemme know if you need help with tree builder Fady. The tree_builder_test files should help but...
