### ISSUE TITLE
256MB file limit

### ISSUE THREAD

**Issue by dvyukov** [google/trace-viewer#627]
On some html files (result of trace2html) chrome says "Import error: invalid string length". After some painful debugging I've figured out that it's probably a 256MB limit on json file somewhere.
When I try to open it in firefox, it just says "TypeError: document.registerElement is not a function trace.html:4258", so I can't test what's the limit in firefox.
Does it sound plausible?
If so it would be nice if trace2html would fail with a reasonable error message.

**Comment by dvyukov** [comment]
Hi,

Any updates on this?

I've submitted tracing functionality into Go mainline. And I think this will be the most popular issue among Go users.

Can the resulting .html read the trace in streaming mode? I could feed it through http, for example.

**Comment by dvyukov** [comment]
Do I understand it correctly that trace2html packs a bunch of static files together and also embeds the json into the resulting file? If so it would be super awesome for us (super-super awesome), if we could pack the static part into an html, and then run it as:
trace.html?trace=http://localhost:12345
and serve json on the address.

Is it doable? I know nothing about your system, but it looks like it may be relatively easy to do.

I don't know whether it will help with the json size limitation or not. But maybe it will help, as you will not need to have json in a js string at all.

**Comment by natduca** [comment]
https://github.com/google/trace-viewer/wiki/Embedding may be useful...  you
definitely can turn trace viewer into a standalone.

As far as fixing the actual limit, I'm a bit unsure the right fixing
strategy. I know that if we could agree on a plan, we'd be happy to mentor
you in writing a fix for it...

**Comment by dvyukov** [comment]
Re Embedding: aha! nice!
trying now

**Comment by natduca** [comment]
Lets try using https://docs.google.com/document/d/11z5VYKup_PWI8-eBDhm0IDsToOpQ-0pFx8VhZwi21Mc/edit# to deal with size issues...

**Comment by dj2** [comment]
I think we can just leave this bug open as the 256 meg limit bug. No reason to create another and lose the discussion here.

**Comment by natduca** [comment]
My comment is that a lot of the conversation is obsolete. The remaining work is just the string parsing. If we had a person driving through looking for bugs, it wouldn't leap out at them what work needs doing. We could I suppose delete the parts of the thread that are obsolete... but thats funky...

**Comment by dj2** [comment]
Ah, I assume anyone that picks up the bug will, hopefully, read the comments and when we say the stack part of this is done and we need to figure out how to deal with importing large traces into trace-viewer they''ll see that.

But, if you feel like it, you can open a new bug and link to this one for some context.
