### ISSUE TITLE
Add an "All default categories" preset to record dialog

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#684]
@kphanee @pdr could you help?

We often ask people to do a pair of traces: one with "everything" on and "with frameviewer". That means * for the first, and *,cc.debug for the second. Can we figure out a pair of presets that cover this so I can give precise directions when asking for this?

**Comment by kphanee** [comment]
@natduca : I have a query - please refer to the comment in #705 . Do I make sense?
I require your inputs to iron out my query.
