### ISSUE TITLE
Remove highlightvsync keyboard shortcut or make the toggle more visible

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#698]
VSync highlighting should always be on, and be modified to be (a) efficient and (b) less visually intrusive so it can be always on.

Or, the toggle should be visually discoverable. E.g. like the flow events checkbox.

@petrcermak can you please take?

**Comment by petrcermak** [comment]
I personally vote for the second option (**discoverable checkbox**) but I would *keep the keyboard shortcut* as well (since it's much faster than ticking a checkbox). Is there a good reason to remove it?

**Comment by natduca** [comment]
I think this is done. Thanks Petr!
