### ISSUE TITLE
vsync highlighter should not draw if gap < 2px

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#700]
if you zoom out, vsync highlighter keeps drawing. the world effectively turns blue

lets have it either stop drawing, or simply merge the drawn rects together. fastRectRenderer does this...

otherwise, performance suffers.

@petrcermak can you please own?

**Comment by petrcermak** [comment]
Sure. I will look into it.

**Comment by petrcermak** [comment]
I think this issue has now been resolved.
