### ISSUE TITLE
Can't type 'v' into the filter text box

### ISSUE THREAD

**Issue by wangxianzhu** [google/trace-viewer#711]
1. Record or load a trace
2. Try to type 'v' into the filter text box (near the top-right corner)

Expected: 'v' should be inputted into the text box
Actual: 'v' is not inputted, but the VSync checkbox is toggled.

**Comment by petrcermak** [comment]
Sorry, this was 99% caused by 3e5cdc93780fcd2733c0f6361025241885536f5d. I will have a look at it today.
