### ISSUE TITLE
(nestable)_async_events rendered within one tree should be visually separated to other async tree

### ISSUE THREAD

**Issue by yufengshen** [google/trace-viewer#725]
Now that to support nested async events we stack the rendering of (nestable_)async_events.
Two top level (nestable_)async_events stacked together is confusing since they would be visually
considered to be one tree. 
We should have some mechanism to separate async event tree, e.g. adding a small gap between
them, or let them have different border color.

**Comment by natduca** [comment]
@xunjieli fyi

**Comment by xunjieli** [comment]
Why would we stack two top-level slices together? Could you attach a screenshot?

**Comment by yufengshen** [comment]
See the example posted here

https://code.google.com/p/chromium/issues/detail?id=434409

**Comment by xunjieli** [comment]
But in-between two top level events (InputLatency), there's the child event of the first InputLatency right? The old UI also aggressively puts events in adjacent rows.

**Comment by yufengshen** [comment]
In the old UI, we consider the child event is within the rect of its parent event, so leaving no space between 2 top level rects is OK. While in the new UI, it is hard to tell 2 adjacent rows are from the
same async tree or not.

**Comment by xunjieli** [comment]
Thanks for clarifying. This was not a problem for me, probably because netlog event tree can often go very deep. Agreed, it might not be obvious that the two InputLatency events are of different trees.
Maybe we can add an extra row between two top level events? The fix will invoke a few line change to buildSubRow in https://github.com/google/trace-viewer/blob/master/trace_viewer/core/tracks/async_slice_group_track.html

**Comment by xunjieli** [comment]
I tried the approach I suggested. https://github.com/xunjieli/trace-viewer/compare/hacky adds a row between two adjacent trees if they are too close. Seems too hacky to me, so I will abandon the fix. Leaving this issue open in case someone else comes up with a better solution.

**Comment by natduca** [comment]
How about just tweaking the drawing of the toplevel slices to but a 1 or 2px solid black line on the topmost event?

**Comment by xunjieli** [comment]
Thanks Nat for the suggestions! I think it'd work. I uploaded a CL. Mind taking a look?
I think the collapsed mode suggestion is a good one too, but I will tackle it in a different CL.
