### ISSUE TITLE
Clicking "Edit Categories" does not select "Manually select settings"

### ISSUE THREAD

**Issue by danakj** [google/trace-viewer#739]
This means you can check boxes for categories you want, and then tracing ignores it all because "Rendering" is still the chosen mode.

**Comment by natduca** [comment]
I think this is fixed ToT, are you sure you were using latest trace-viewer?

**Comment by danakj** [comment]
I did pull chrome/build today. Will try tomorrow.

**Comment by kphanee** [comment]
It was fixed sometime back and there should be no issue in the ToT builds.

**Comment by danakj** [comment]
Maybe it regressed then? Pulled/sycned multiple times today.

**Comment by natduca** [comment]
Did we roll DEPS Ravi?

**Comment by kphanee** [comment]
Yes, I rolled the deps after the change.

**Comment by danakj** [comment]
I just synced chrome to TOT and clicking on "edit categories" still does
not select "Manually select settings"

**Comment by natduca** [comment]
Ravi, can you investigate?

**Comment by kphanee** [comment]
@danakj : I just checked on ToT and it is working as per current design. I guess the confusion is when "Manually select" mode will get activated. To clarify, the current behavior is:
* If we are in any preset mode (other than "Manually select") and click 'Edit categories', we just open the manual selection dialog.
* Only the categories which are part of **currently selected preset**, will be selected in the opened manual selection dialog.
* We still remain in the preset mode (even after manual selection dialog is open) **unless** we modify the selected categories i.e. we select new category or de-select existing category.
* In case of above scenario, we automatically move the selection to "Manually select settings" mode.
* On next invocation of recording dialog, however, we are still select the previous selected preset mode.
* However, if we choose "Manually select settings" mode in the dialog, the last stored (in local db) category list is pre-selected. Any modification in "Manually selected settings" mode is stored to the local db. For next invocation of recording dialog, mode option selected would be "Manually select settings"

I hope I am clear in the explanation of current behavior. Please let me know if you have any further query.

**Comment by natduca** [comment]
Ravi, I think despite your explanation of why this is working as intended, its clear this UI is not good enough to be intuitive. We should be aspiring to having an intuitive UI for our users.

What would be a more intuitive UI?

Perhaps use tab_view.html? Tab 1, a list of presets, Tab 2 a "advanced" tab. Have a "customize..." button next to a given preset that switches to tab2 and sets the advanced categories to that preset.

**Comment by danakj** [comment]
Ah thanks. It's working well now, then.

**Comment by kphanee** [comment]
@natduca : Sure. I am ok with it. Let me try to hack the code to tabbed view using tab_view.html and see how it comes.

**Comment by kphanee** [comment]
@natduca : As you suggested, I have uploaded a patchset with your said UX #777. PTAL!.

**Comment by kphanee** [comment]
@natduca : I have updated the unit tests in #780. PTAL!
