### ISSUE TITLE
Trace with multiple categories needs ALL on instead of ONE on to be traced

### ISSUE THREAD

**Issue by danakj** [google/trace-viewer#743]
Example:

TRACE_EVENT1("cc,benchmark", "Scheduler::BeginFrame", "args", args.AsValue());

I thought this means "cc || benchmark".

But current implementation is "cc && benchmark". Turning either "cc" or "benchmark" on does not include it in the trace. Turning both on does.

**Comment by danakj** [comment]
// It is often the case that one trace may belong in multiple categories at the
// same time. The first argument to the trace can be a comma-separated list of
// categories, forming a category group, like:
//
// TRACE_EVENT_INSTANT0("input,views", "OnMouseOver", TRACE_EVENT_SCOPE_THREAD)
//
// We can enable/disable tracing of OnMouseOver by enabling/disabling either
// category.

Documentation supports this being an || operation.

**Comment by danakj** [comment]
BTW I am at 3470cc939061a9238695747557adc41eb35ed267

**Comment by danakj** [comment]
Maybe this is a bug with recording, not the viewer tho? Should I file somewhere else?

**Comment by dj2** [comment]
It's a bug in recording but filing here is fine. I thought I'd fixed this. CategoryFilters are their own special layer of hell.

**Comment by kphanee** [comment]
I will check the code and try to put a fix today. :)

**Comment by kphanee** [comment]
Raised a @ crbug.com/463385 and uploaded a patch @ crrev.com/971673004.
PTAL!
