### ISSUE TITLE
vulcanize does not work

### ISSUE THREAD

**Issue by dvyukov** [google/trace-viewer#747]
I am following instructions at:
https://github.com/google/trace-viewer/wiki/Embedding

I have the following html:

```html
<html>
<head>
<script>
function loaded() {
var viewer = new tv.TraceViewer('/jsontrace');
document.body.appendChild(viewer);
}
</script>
<link href="/trace_viewer_html" rel="import" onload="loaded()">
</head>
<body>
</body>
</html>
```

I see that /trace_viewer_html is requested on my server and loaded (it refers to trace_viewer_full.html).
However /jsontrace is not requested on my server.

In the console I see the following error message:
Uncaught ReferenceError: TracingFindControl is not defined

I've tried both on tip (30857b0a20829bf100beb8a44f538f2f6452343b) and on releases_chrome_m41.

What am I doing wrong?

**Comment by dvyukov** [comment]
Retried with 
./vulcanize_trace_viewer --config=lean
./vulcanize_trace_viewer --config=chrome
./vulcanize_trace_viewer --config=full
Result is the same.

**Comment by natduca** [comment]
You're running your script too early. Try waiting for domcontentloaded instead of waiting on the import loaded event.

**Comment by natduca** [comment]
Or after the import loaded, wait on Polymer.ready(function() { do your stuff here });

**Comment by dvyukov** [comment]
When I use the following html:

```html
<html>
<head>
<script>
function loaded() {
alert("loaded");
Polymer.ready(function() {
alert("Polymer.ready");
var viewer = new tv.TraceViewer('/jsontrace');
document.body.appendChild(viewer);
});
}
</script>
<link href="/trace_viewer_html" rel="import" onload="loaded()">
</head>
<body>
</body>
</html>
```

Console show the following error:
Uncaught TypeError: undefined is not a function
Source tab highlights the following line:
Polymer.ready(function() {

**Comment by dvyukov** [comment]
DOMContentLoaded seems to work to some degree. It took me some time to figure out how to wire it up. It is apparently not just s/loaded/domcontentloaded/.
Now I see that json file is requested from my server. However, no trace is rendered on the page... 
I would appreciate if you put a full working example on the wiki.

**Comment by dvyukov** [comment]
The trace was not rendered due to an issue on my side.
FTR, The following html now works for me:

```html
<html>
<head>
<link href="/trace_viewer_html" rel="import">
<script>
document.addEventListener("DOMContentLoaded", function(event) {
var viewer = new tv.TraceViewer('/jsontrace');
document.body.appendChild(viewer);
});
</script>
</head>
<body>
</body>
</html>
```

**Comment by natduca** [comment]
There is a full working example in bin/index.html

**Comment by dvyukov** [comment]
How is the next user supposed to find it after reading https://github.com/google/trace-viewer/wiki/Embedding?

**Comment by dj2** [comment]
Added Example section to bottom of wiki page. Thanks for pointing out it was missing.

**Comment by dvyukov** [comment]
Thanks!
