### ISSUE TITLE
Improve <tv-c-stack-frame> widget's display

### ISSUE THREAD

**Issue by dvyukov** [google/trace-viewer#753]
Followup to issue #752

Stack traces attached to events using sf attribute are shown reversed. The frame referenced from sf is shown at the bottom, while the parent is shown at the top. That's not how gdb, lldb, MSVC, Go, breakpad and AddressSanitizer show traces.
Stack traces should be shown the other way around.

@natduca

**Comment by natduca** [comment]
The stack frames are displayed with GenericObjectView. I think we'd be better off making span/table items to display the stack frames directly. It would be prettier.

**Comment by dvyukov** [comment]
@egonelbre This is another issue for Go trace viewer.

**Comment by egonelbre** [comment]
Both issues have been addressed :)
