### ISSUE TITLE
"Edit Categories" doesn't work properly

### ISSUE THREAD

**Issue by wangxianzhu** [google/trace-viewer#758]
Chrome version: ToT 2/13 (316234)

1. chrome://tracing, click Record
2. Select Frame Viewer
3. Edit categories, check 'blink.invalidation' (at this time, "Manual select settings" is automatically selected)
4. Record for several seconds, ensure there have been some blink invalidation
5. Check recorded trace: no 'blink.invalidation' events

If I click "Manual select settings" before check "blink.invalidation", it will work.

**Comment by dj2** [comment]
@kphanee

**Comment by kphanee** [comment]
@dj, @wangxianzhu : Sorry, I was on leave. I will check today itself and update on the issue.

**Comment by kphanee** [comment]
Added a pull request with the fix @ #762

**Comment by kphanee** [comment]
Can we close this issue? #762 is merged now.
