### ISSUE TITLE
TimelineView/TimelineTrackView/TimelineViewport class responsibilities are confusing

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#769]
There are a few things that are misplaced that makes everything more complicated than it should.  I think there are few cleanups we can do in advance of the hackathon that would make things a lot clearer.

**Comment by natduca** [comment]
This is what we have now 
![image](https://cloud.githubusercontent.com/assets/412396/6307805/c93bfaea-b8f3-11e4-8e83-370b44061853.png)

**Comment by dj2** [comment]
What is TimelineTrackView again? Can we just kill it or give it a better name?
