### ISSUE TITLE
TraceModelTrack out of sync with ruler in upper mode

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#771]
Here's a screenshot of the problem:

![upper_mode_ruler](https://cloud.githubusercontent.com/assets/2546601/6349989/d3be236c-bc27-11e4-84cf-a2e735c388a7.png)
The <tt>TraceModelTrack</tt> in *upper mode* is the white stripe in the middle. Note that the <tt>TraceModelTrack</tt> in *lower mode* (at the bottom) is *in sync* with the ruler.

**Comment by dj2** [comment]
That's awesome, rounding error somewhere?

**Comment by petrcermak** [comment]
No, the problem is that <tt>RulerTrack</tt> generates <tt>majorMarkPositions</tt> in the <tt>SLICE</tt> phase which happens *after* the <tt>GRID</tt> phase. This isn't a problem in the lower <tt>TraceModelTrack</tt> because it's in a different container in <tt>TimelineTrackView</tt>.

It's an easy fix that I already have prepared. I'm just trying to come up with a test right now.

**Comment by petrcermak** [comment]
There doesn't seem to be an easy way to *inject* a track to the upper <tt>TraceModelTrack</tt>, so I won't add a test (to check that the grids are in sync) now to avoid leaking implementation details into it.
