### ISSUE TITLE
Fix selection-via-mouse-cursor on upper container and move IR and memory dumps up

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#776]
Right now mose dragging that drives selection is owned by the ttv, and only works in the lower drawing container. We somehow need to make it work regardless of where the user selects

**Comment by natduca** [comment]
This is related to #769 though w could probably fix this bug without addressing all of the concerns in that broader bug

**Comment by dj2** [comment]
When you say dragging, do you mean for selection? Or something else?

**Comment by natduca** [comment]
I clarified the text, hopefully its clearer!
