### ISSUE TITLE
More data should be shown in flow events, including "s" versus "f"

### ISSUE THREAD

**Issue by randomascii** [google/trace-viewer#789]
The flow events shown in trace viewer are ambiguous to a new user, and are missing information that could be helpful to an expert.

A start event looks like this:

![image](https://cloud.githubusercontent.com/assets/10800041/6474082/b5912304-c1b2-11e4-9a50-f8b3ec34d5f8.png)

and a finish event looks like this:

![image](https://cloud.githubusercontent.com/assets/10800041/6474084/bd5441ac-c1b2-11e4-9568-dd70ae785673.png)

In both cases the time is labeled with "Start", which for the "f" event is confusing -- the start of the finish event? Hmmm. It would be helpful to rename "Start" to "Finish" for the finish events, or to explicitly list the phase. Right now the only indication of the phase is that "f" events have a queue_duration and "s" events do not -- that's too cryptic.

It would also be nice if it was clearer that src_file and src_func describe the place that called PostTask (it is odd that the PostTask details are shown in the RunTask). It could also be useful to record and display what function is being run, as well as what function posted the task. Ideally I'd like to have a summary for the task that told me where it was posted, and what it is.

**Comment by skyostil** [comment]
I also agree that showing the posting location more visually would be very useful, but I'm not quite sure how to visualize it. Here we hacked around just replacing the task name with the posting location, but I think we need to show both somehow: https://codereview.chromium.org/962273002/diff/20001/base/debug/task_annotator.cc

**Comment by natduca** [comment]
I wonder if the first piece here is figuring out how to connect up the flow events with slices. As I pointed out in the previous notes, in a trace, we have no connection between the end of a flow and the task running. Because of that weak connection, its very hard to build up a proper dag... if we could figure out a rational way to fix that connection up then we could maybe start parsing this as a dag and making proper UI...

**Comment by dj2** [comment]
Well, they aren't connected per-say, but they are connected in that it will be the next event after the flow event. The flow events are in the slice lists like anything else. The interval map is used to determine if the endpoints are on screen or not.

So, the task running should be the event immediately after the flow 't' or 'f' event in the slice list.

**Comment by dj2** [comment]
The one issue with trying to connect flow events to other slices around them is, you don't know if you should. You don't know if you're looking at a flow event for a task being executed, or one for input being passed around. There is no guarantee that the thing that happens after a flow event was triggered by the flow event.

**Comment by natduca** [comment]
I think we should enhance the flow event tracing api so that we don't have ambiguity here.

For instance, what if when you issue trace_event_flow_end call, you pass a flag saying NextSliceIsResult  (or EnclosingSliceIsResult, depending on the semantics you want... then we'd put that in the trace, tweak the importers, and we'd have a proper dag...

**Comment by natduca** [comment]
(Also, should we just kill 't' for flow events? I don't know of anyone who actually uses them...)

**Comment by dj2** [comment]
I'd check with input dev before killing it, although I guess you can just grep to see if the macro is used.

We could possibly add an extra param to the macros for ASSOCIATE_TO_ID and you pass in the flow ID or something, we then output an annotation in that event that it's associated to the thing that has the given ID.

**Comment by natduca** [comment]
That seems interesting. but how do we know which node in the flow you're binding to? That part is important in order to populate an "incomingFlows" and "outgoingFlows" on Slice objects.

**Comment by dj2** [comment]
Does it matter if you have the ID? If you want to flow into, you give an ID to the previous slice and tell the flow start to associate to that ID. If you want to flow out you associate the next slice to the flow ID.

Though, I'm guessing this would make the API kinda crappy.

**Comment by natduca** [comment]
I think the problem with associate_to_id is that you could associate with some random other thread. We really want the semantics to be tight... this flow ends in this slice, on the same thread. I'd love this to be rock solid so we could do stuff like critical path analysis....

**Comment by randomascii** [comment]
> You don't know if you're looking at a flow event for a task being executed, or one for input
> being passed around. There is no guarantee that the thing that happens after a flow event
> was triggered by the flow event.

Well that's unfortunate. Is there no current way of distinguishing those flow events that aren't triggers for the next event?

An alternate question is, we are clearly losing some value by not reliably hooking up tasks to the prior flow event. Would the inaccuracies that came from always hooking up a task to the prior flow event (if present) be any worse? We're getting lots of false negatives now, maybe false positives would be better?

FWIW, I found four uses of TRACE_EVENT_FLOW_STEP in Chromium.

**Comment by natduca** [comment]
Hmmm good point Bruce. Should we do the pragmatic thing for now and associate:
- the parent slice containing the start event as the flow event's start point
- the next slice after the end event as the flow event's end point?

(Btw it should be a quick patch to trace_event_impl.h to add flags if we want to make this more explicit: https://codereview.chromium.org/1004033003 ---- I'm not in a good position to make c++ changes as I'm travelling but if we do want to do the "designed" approach, thats kinda the places to edit. I can do the js frontend changes...)

**Comment by natduca** [comment]
#822 covers the infrastructure. Let focus discussions about format there.

**Comment by dj2** [comment]
But you don't know if the thing before or after the flow is associated. We'd need to update the C++ side first and then we'd know. Otherwise, this works for run task events but isn't necessarily valid for anything else.
