### ISSUE TITLE
Times should always be displayed with three digits after the period

### ISSUE THREAD

**Issue by randomascii** [google/trace-viewer#790]
It is slightly distracting to have the number of digits displayed after the decimal point in the trace viewer vary. Right now trailing zeroes are trimmed off, as shown here:

![image](https://cloud.githubusercontent.com/assets/10800041/6474221/e72e4526-c1b3-11e4-9d85-24d5489fb8a4.png)

Not a big deal, just a minor polish/consistency suggestion.

**Comment by dj2** [comment]
Would also be nice to humanify the numbers so 7,623.234 ms instead of 7623.234 ms. I find things much easer to parse when there are commas in there.

**Comment by randomascii** [comment]
Would also be nice to always display units. The queue_duration field is displayed without units. This is particularly confusing to anybody who looks at the .json data because the "ts" data has microseconds units:

![image](https://cloud.githubusercontent.com/assets/10800041/6491788/7751d09a-c264-11e4-844b-7f7bc16c76aa.png)

The args are almost certainly displayed generically without any special processing of their contents, but, still. Units would be nice. Perhaps insert them when creating the .json file?

**Comment by natduca** [comment]
The dirty fix for this is to grep for calls to tsRound (which is implemented core/analysis/analysis_results.html). If I was actually competent, I would have long ago made tsRound been more like timeToUserFriendlyString() that did the rounding + 'ms' suffixing. But I didn't. So now we have to change lots of places. Probably the grownup fix is implied here. Though I honestly have no problem kicking the proverbial can down the street a bit longer in this code. Anyone who cracks open analysis_results.html will witness the true pile that is the analysis system and suddenly realize how small the tsRound mess is in comparison. :)

**Comment by dj2** [comment]
Times are always in ms, right @natduca ?

**Comment by dj2** [comment]
That CL does the 3 digits of precision and the comma separator for things that call tsRound. There are other cases which don't use tsRound that will need to be hunted down and fixed.

**Comment by dj2** [comment]
I'm going to call this closed. If there are any that aren't formatted correctly please re-open and I'll fix them up.
