### ISSUE TITLE
Test system based entirely on filenames,  not module names

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#795]
Lets us move devserver out of tvcm

**Comment by dj2** [comment]
What is it you're trying to solve with the filename vs module name?

**Comment by natduca** [comment]
Ah, I want to thin tvcm down to be just "vulcanizing" and nothing else. That means that the devserver should not be part of tvcm.

But, the devserver uses a lot of the tvcm module objects right now. Especially, the unittest system gets the test list but as module names (dotted names), instead of absolute paths. Once I switch it to loading absolute paths, then I can remove one more dependency between devserver and tvcm.

**Comment by natduca** [comment]
The files to touch are
suite_loader.html -- loadmodule
trace_viewer_dev_server.py --- do_GET_json_tests

**Comment by eakuefner** [comment]
Reopening, still a little more cleanup to do. In particular:

1. Let's figure out the right name for relpath (might just be href)
2. Move slash-prepending into Python
3. hrefs everywhere (interactive_test_runner, more suite_loader mods)
