### ISSUE TITLE
Move single and multi slice sub view from analysis_results to analysis/table_builder

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#796]
We have a pretty decent replacement ready. Just have to switch it over.

Assigning to me unless someone wants to do it.

**Comment by dj2** [comment]
One thing missing from table_builder. It looks like in muti_slice analysis we generate statistics (min, max, avg time values). The current system puts those as a tooltip. There is no way, currently, to do that with table_builder.

Do we wan to add tooltips to table_builder, or move the current statistics into the table in some fashion? (They suffer from discoverability issues at the moment).

We could do something like put the stats under the table row, but that will make the table twice as large ....

**Comment by natduca** [comment]
I forget, can't a table_builder callback generate an element, instead of text? We could have an element which you construct and give an array of values, then it displays the tsString'd in its contents and inernally sets up a tooltip. That way down the road we can improve that element to support hover etc

**Comment by petrcermak** [comment]
<tt>TableBuilder</tt> can append an arbitrary *<tt>HTMLElement</tt>* (instead of a text element) if a column's <tt>value</tt> function returns an *<tt>HTMLElement</tt>* (instead of text).

See the if statement at the bottom of <tt>TableBuilder.generateRowNode_</tt>.

**Comment by natduca** [comment]
I added a time_span widget to analysis that might be a useful template for this. Maybe this is just a matter of augmenting time_span to understand duration as either an array or a scalar --- if array, it'd tweak its display...

**Comment by natduca** [comment]
Getting pretty close to v1... what remains:
- Add back in tooltips [or equivalent]
- Figure out why I see bizarre widths when some things selected
