### ISSUE TITLE
Define abstraction for domain-specific helpers in trace_model (aka ChromeAudit)

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#797]
ChromeAuditor is a good name.

But ChromeAudit is more like a ChromeSpecificTraceModel. Or a ChromeTraceModel. Or something like that. @dj2 halp!

**Comment by natduca** [comment]
@yufengshen do you have any suggestions?

**Comment by dj2** [comment]
So, the ChromeAuditor outputs a ChromeAudit which is tied to the TraceModel? What's the relationship here?

**Comment by natduca** [comment]
ChromeAuditor is just postprocessing of a trace to create alerts and interaction records. It therefore needs a way to find chrome browser, çhrome renderer, find frame records, input latency records, etc. That's a fair bit of domain-specific spaghetti code that has a lot of quirks (oh on this old chrome revision, also look for this old trace event name, etc). So, I have all that goup factored out to a ChromeAudit object.

A ChromeAudit object is constructed from a trace model It knows nothing about ChromeAuditor. All it does it is create a parallel process and threads tree to the trace model. E.g. ChromeAudit.browser is the chrome browser that we find in the trace, the renderers, etc.

If TraceModel had chrome-specific methods in it, then we'd have model.browser, model.renderProcesses, etc. But, we don't want the trace model to have domain-specific things in it.

So the question is, how do we add domain specific things?

In the past I've dealt with this by having the base model class, e.g. ObjectInstance, have a registry on it, where you can say "when you see an ObjectInstance called çc::Foo, then use this Foo constructor †o construct that type." That way the Foo constructor is a subclass of ObjectInstance but we have nice separation of domain-specific vs core/.

The problem in our code is that we don't know process names at construction time. So, we don't have a clear way to construct a process' subclass. Though maybe I could refactor the way importing works... hmmmmmmm.

**Comment by ChrisCraik** [comment]
Would love to make an Android equivalent to isolate the boilerplate work - find UI threads, RenderThreads, frames, SurfaceFlinger vsyncs, etc.

- Ideally, these annotators(?) would be compatible with one another - hopefully Chrome and Android versions could cooperate.
- Could potentially support https://github.com/google/trace-viewer/issues/818 - rewriting parts of a model for consistency.
- Annotator could tag processes / threads with priorities (clump rendering threads within app together, throw inactive apps with a single slice to the bottom of the process list)

**Comment by natduca** [comment]
I've added a few design options to the design doc here:
https://docs.google.com/a/chromium.org/document/d/1BH7b9-giXqoD511fC00oL9TiUsiOI83GbcMpr6xYOw8/edit 

Lets chat today about what feels least horrifying?

**Comment by natduca** [comment]
We've decided on option XModelHelper, ChromeModelHelper, AndroidModelHelper. The design doc is updated.
