### ISSUE TITLE
Stuff all the existing checkboxes into a dropdown widget

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#801]
We have vsync and flow events toggles. Lets make a dropdown widget (hover or click) and put the checkboxes inside...

**Comment by dj2** [comment]
https://www.polymer-project.org/docs/elements/core-elements.html#core-dropdown-menu

**Comment by natduca** [comment]
Are we in a position that we can reliably use core elements yet?

**Comment by dj2** [comment]
We haven't tried, but I don't see why not. Just bower install --save Polymer/core-dropdown-menu and then href="/components/<whatever the path is" and it should work.

**Comment by natduca** [comment]
I am reluctant to use more polymer widgets yet until we get moved over to 0.8 which is in turn blocked on them releasing 0.8 plus updated components --- for now lets do it ourselves and then move to it down the road?
