### ISSUE TITLE
Replace uses of process 0 with trace_model.kernel

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#802]
We have getOrCreateProcess[0] and processes[0] calls littered throughout the codebase. Lets switch this to using kernel.

**Comment by aschulm** [comment]
There seems to be a regression with this commit. Any trace that calls clock_parser.html is being drawn with blank tracks. This is test data that shows the problem https://drive.google.com/file/d/0B3Ar_Dp3eEnJNE92amRIUjVEYms/view?usp=sharing

**Comment by natduca** [comment]
Fixed by 16df9ad93705e60188dca98e377566549b27c2e5
