### ISSUE TITLE
Prepare trace_viewer folder layout for catapultization

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#805]
That might match our overall namespace structure of tv.b, tv.c, tv.TraceViewer, etc...

**Comment by natduca** [comment]
@dj2 wdyt?

**Comment by dj2** [comment]
I'd much sooner move it to src/ heh. I keep looking for a top level src folder and can never find it. We also use base/ core/ and extra/ not b, c, e.

**Comment by natduca** [comment]
I'm fine with src.

**Comment by dj2** [comment]
Sure, sounds good.

**Comment by natduca** [comment]
I'm thinking of holding this off until after the hackathon. I rather suspect a few things will go wrong with the rename and I don't want to block short term progress on it.

**Comment by natduca** [comment]
One thing we may want to do as part of this is move stuff from trace_viewer/build up to wherever the other toplevel scripts go. Right now we have a mix of maintenance scripts in trace_viewer/build/ and the toplevel directory. Its kinda awks.
