### ISSUE TITLE
Switch table builder from alternating row colors to grey-row-on-hover

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#808]

**Comment by natduca** [comment]
@petrcermak hmm

**Comment by petrcermak** [comment]
I came across this last week and I've been thinking about how to solve it, but there's one issue - **nested rows**. Suppose that you have the following situation:

    ### ▶ row 1 ########## (grey) ##########
          row 2            (white)
    ##### row 3 ############################
    ...

And then you expand the first row, which has an odd number of sub-rows:

    ### ▼ row 1 ############################
              row 1a
    ######### row 1b #######################
              row 1c
    ????? row 2 ????????????????????????????
    ????? row 3 ????????????????????????????
    ...

If we want to have two alternating colors in the whole table:

1. either <tt>row 2</tt>, <tt>row 3</tt>, ... will have to *change color* to grey (violate row color consistency), or
2. there will be two consecutive rows (<tt>row 1c</tt> and <tt>row 2</tt>) with the *same color*.

Neither approach seems ideal to me. Here are some ideas that we came up with:

1. Alternate colors at the *top level* only:

  ```
### ▼ row 1 ############################
######### row 1a #######################
######### row 1b #######################
######### row 1c #######################
          row 2
##### row 3 ############################
...
```

  This seems to be the right solution for *shallow* tables.

2. Use *different colors* at different levels:

  ```
### ▼ row 1 ############################
········· row 1a ·······················
********* row 1b ***********************
········· row 1c ·······················
          row 2
##### row 3 ############################
...
```

  This solution might work well with *both shallow and *deep* tables, but I'm afraid that there would be *too many colors*.

@natduca: What do you think?

**Comment by natduca** [comment]
Two options:

a) Have row 2 change color when you expand. Always alternating grey-white.
b) Do the devtools approach: the row under the mouse cursor gets lightly colored grey [while the selected row turns blue]:

![image](https://cloud.githubusercontent.com/assets/412396/6595805/290a0f06-c831-11e4-965f-a20136cf9768.png)

**Comment by petrcermak** [comment]
a) I think this could be quite confusing, because the color of rows could "randomly" change.
b) I'm working on implementing this behavior as part of the memory visualization :blush:

**Comment by natduca** [comment]
Sgtm. Lets update the bug title to match the plan..

**Comment by petrcermak** [comment]
As a follow-up, we should add **blue-on-select** #872.

**Comment by petrcermak** [comment]
I think we should re-consider this because there's currently no way to highlight rows when **cell selection** is enabled.

**Comment by petrcermak** [comment]
I propose adding a **lighter highlight** of the row containing the hovered/selected cell:

![row_highlight](https://cloud.githubusercontent.com/assets/2546601/8032858/8405b1e0-0dd1-11e5-9c69-05363785b5d5.png)

I would make it optional (e.g. <tt>table.rowHighlightEnabled = true</tt>).

@natduca: WDYT?

**Comment by natduca** [comment]
Sgtm. Wanna write the patch?

**Comment by petrcermak** [comment]
Good point. I split the proposal into a **new issue** (#1004).
