### ISSUE TITLE
Table builder isn't virtual: it expands rows even when they're collapsed

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#819]
Shouldn't expand until they're expanded. Makes it impossible to make virtual tables. Sadness.

**Comment by petrcermak** [comment]
By **virtual tables** do you mean nested tables where <tt>subRows</tt> is a *getter* rather than just a field (so they can be potentially infinite)?

**Comment by petrcermak** [comment]
I'll probably fix this together with #808 while working on memory visualization.

**Comment by natduca** [comment]
Sounds great. But please, separate patches :)

**Comment by natduca** [comment]
(And yeah, you can make subRows a property and awesomeness results)
