### ISSUE TITLE
Incorrect, huge time scale shown

### ISSUE THREAD

**Issue by nicolassatragno** [google/trace-viewer#827]
Running Chrome with Aura from tip of the tree, I see an issue where the timeline for chrome://trace spans way more time than it should. Attaching screenshot.
![screenshot from 2015-03-17 13 29 36](https://cloud.githubusercontent.com/assets/2953655/6693550/204b7454-ccaa-11e4-9ca1-e522d314d35b.png)
The actual time for which I was recording was about 2 seconds. Cheers!

**Comment by jackjyang** [comment]
I was helping Nicolas with this issue earlier. Here was the tracing file: https://drive.google.com/file/d/0B0-FfsfAGyirTEdKaGJNVUw2b0E/view?usp=sharing

There's also a text rendering issue on the slice as seen in the above screenshot. Both issues were seen on about://tracing on chrome stable - for some reason I can't even load the file on the local dev server - I get "Important Error - traceModel not defined"
