### ISSUE TITLE
Input latency and thread times side panels dont seem to work

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#828]
Saw it today during a demo against 
http://localhost:8003/examples/trace_viewer.html#measurmt-traces/desktop/cnn_load_and_scroll.json.gz against tot

**Comment by natduca** [comment]
@qeny maybe interesting...

**Comment by dj2** [comment]
These work in the example trace viewer. Viewing the Android Systrace they show up.

**Comment by natduca** [comment]
@yufengshen this is something i need you to help with. The branch in chrome helper for getting latency is exploding on "no valid begin latency component." :/


        var latency = 0;
        var endTime = data[END_COMP_NAME].time;
        if (ORIGINAL_COMP_NAME in data) {
          latency = endTime - data[ORIGINAL_COMP_NAME].time;
        } else if (UI_COMP_NAME in data) {
          latency = endTime - data[UI_COMP_NAME].time;
        } else if (BEGIN_COMP_NAME in data) {
          latency = endTime - data[BEGIN_COMP_NAME].time;
        } else {
          throw new Error('No valid begin latency component'); <-- here
        }

**Comment by natduca** [comment]
Still doesn't work on old files.
