### ISSUE TITLE
Observing "Aw, Snap!" while executing unit tests

### ISSUE THREAD

**Issue by kphanee** [google/trace-viewer#834]
In the latest revisions, I am observing frequent "Aw, Snap!" tab during unit tests execution. I have to execute the tests 4-5 times before all the unit tests are executed.

I have already tried clearing the user data, restarting dev_server (before each test invocation)  among other attempts to ensure there is no local setup issue. Anybody else observing similar errors? Am I missing something?

Chromium Version: 	43.0.2339.0 (Developer Build) (64-bit)
Revision	a24bf43bfb8ea6f75109ba9eea841f92c164e3ae-refs/heads/master@{#321518}
OS:	Linux Mint 17 64-bit
Blink	537.36 (@192193)
Trace-viewer revision: 8f04ee4ca080fa800a950cc5bcb2f18c65a5a5c6

**Comment by qeny** [comment]
I was also getting "Aw Snap" when running the tests; I think this is the same issue as [issue 831](https://github.com/google/trace-viewer/issues/831).

**Comment by natduca** [comment]
Can someone get a crashid?

**Comment by natduca** [comment]
This turns out to be https://code.google.com/p/chromium/issues/detail?id=464755 and we have a workaround coming in #831 so lets close and wait for 831
