### ISSUE TITLE
Create preset for "Performance bug"

### ISSUE THREAD

**Issue by anniesullie** [google/trace-viewer#844]
This should just be all the enabled categories.

**Comment by natduca** [comment]
Probably https://github.com/google/trace-viewer/blob/master/trace_viewer/extras/about_tracing/record_selection_dialog.html#L160 is a good place to start...

**Comment by anniesullie** [comment]
How does the the allCategories_ get populated? Can I access the full list to find the enabled ones on line 160, or do I need to do something closer to https://github.com/google/trace-viewer/blob/master/trace_viewer/extras/about_tracing/record_selection_dialog.html#L210 ?

**Comment by kphanee** [comment]
@anniesullie : You can refer to the idea that nat duca suggested for adding preset for bug reporting at https://github.com/google/trace-viewer/pull/705. Specifically comment 3 and 4.
