### ISSUE TITLE
Visualize memory dumps

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#849]
This is a *tracking bug* for implementing memory dump visualization in Trace Viewer.

**Comment by petrcermak** [comment]
The first step is to add a track showing global **used memory** (per process). Here's a screenshot:

![global_memory_dump_track](https://cloud.githubusercontent.com/assets/2546601/6902355/49dcbab0-d70b-11e4-82f5-c1a1f4641321.png)

*We still have to decide whether we keep the original dump track (blue dots with a letter "M") alongside the new one, or whether we remove it.*

**Comment by petrcermak** [comment]
The second step is to show the global **used memory** (per process) in **analysis view** (https://codereview.appspot.com/226290043). Here's a screenshot:

![single_global_dump_sub_view_table_builder](https://cloud.githubusercontent.com/assets/2546601/7183420/4516a8e6-e44f-11e4-9a0c-29ed740a3b3d.png)

**Comment by petrcermak** [comment]
The next patch adds a track showing global **allocated memory** (per allocator) (https://codereview.appspot.com/226380043). Here's a screenshot:

![allocated_track](https://cloud.githubusercontent.com/assets/2546601/7207290/313cea92-e530-11e4-8442-82247e9a45e0.png)

**Comment by petrcermak** [comment]
Another patch adding **allocated memory** to the **analysis view**, namely one column for each allocator (https://codereview.appspot.com/227350043):

![allocators_columns](https://cloud.githubusercontent.com/assets/2546601/7228042/4d46060a-e74d-11e4-8732-586d557551ac.png)

**Comment by petrcermak** [comment]
Adding a **process pane** to <tt>tv-c-single-global-memory-dump-sub-view</tt> (https://codereview.appspot.com/232810043):

![two_columns](https://cloud.githubusercontent.com/assets/2546601/7248211/fb7210b4-e808-11e4-9281-653667b016a3.png)

**Comment by petrcermak** [comment]
Here's a proposal for the (software) design of <tt>tv-c-single-global-memory-dump-sub-view</tt>:

![singleglobalmemorydumpsubview hierarchy 1](https://cloud.githubusercontent.com/assets/2546601/7252252/2b27622e-e82b-11e4-971f-e47657af92bb.png)

**Comment by natduca** [comment]
Love this

**Comment by petrcermak** [comment]
Here's a screenshot summarising where we're at right now:

![aggregated_memory_screenshot](https://cloud.githubusercontent.com/assets/2546601/7324180/d768947c-eaab-11e4-9710-2408703428ff.png)

**Comment by petrcermak** [comment]
Next step: **process tracks** showing **allocated memory** (per allocator)

![process_allocator_tracks](https://cloud.githubusercontent.com/assets/2546601/7416420/2325beee-ef57-11e4-8c78-0b5303f4f8ef.png)
(The red and blue lines are *malloc* and *v8* outer sizes respectively)

**Comment by petrcermak** [comment]
It is currently *difficult* to tell which *row* in the single global memory dump analysis sub-view corresponds to which *series* on the "Used memory (per process)" track. That should change when **color legends** are added to the "Overview" table (https://codereview.appspot.com/232290043):

![color_legend](https://cloud.githubusercontent.com/assets/2546601/7563768/1fd9c6f2-f7d8-11e4-9ced-deeea4eb25e0.png)

**Comment by petrcermak** [comment]
The same problem (as in my previous comment) also applies to the allocator *columns* in the single memory dump analysis sub-views and the *series* on the "Allocated memory (per allocator)" track. The solution is the same as well (https://codereview.appspot.com/233330043/):

![allocator_column_legend](https://cloud.githubusercontent.com/assets/2546601/7583601/b69795c2-f88e-11e4-956c-a35a616699f4.png)

**Comment by petrcermak** [comment]
The vertical stacking of per-process series in the "Used memory (per process)" is currently **simulated** by drawing the series over each other, which *negatively impacts the visual experience*:

![stacking_before](https://cloud.githubusercontent.com/assets/2546601/7608465/bbab3cde-f961-11e4-86f3-de77f443bd5c.png)

It's easier to distinguish between the individual series (the colors don't blend together) when **proper** stacking is implemented (https://codereview.appspot.com/235510043/):

![stacking_after](https://cloud.githubusercontent.com/assets/2546601/7608466/bbaf948c-f961-11e4-916f-b75745811134.png)

**Comment by petrcermak** [comment]
The next patch adds a **memory maps pane** to single process and global memory dump analysis sub-views (https://codereview.appspot.com/233520043):

![mmaps_pane](https://cloud.githubusercontent.com/assets/2546601/7656878/703bcbd6-fb25-11e4-83aa-35dae7e28b9b.png)

**Comment by petrcermak** [comment]
Instead of showing **memory maps** as a flat list, we will show them as a **classified tree** like [Memory Inspector](https://code.google.com/p/chromium/codesearch#chromium/src/tools/memory_inspector/) in the Chromium tree (https://codereview.appspot.com/238700044):

![screenshot from 2015-06-04 15 55 54](https://cloud.githubusercontent.com/assets/2546601/7986899/374b6a04-0ad2-11e5-9b67-b8a7c09ba163.png)

**Comment by natduca** [comment]
Yuhssssssssss!

**Comment by petrcermak** [comment]
There have been no updates (except for patches) to this tracking bug recently, so here's a brief overview of what *is* and *will be* happening...

<h3>Current State</h3>

  1. **Memory profiling in chrome://tracing went public** 
  
  Public wiki: https://www.chromium.org/developers/how-tos/trace-event-profiling-tool/memory

  2. **Many UI changes since last update** (mmap classification like in <tt>dumpsys meminfo</tt>, sorting columns by importance, automatic row expansion, 'tracing' discounting, 'Total' row on the 'Overview' pane, and row highlighting)

  Latest screenshot:
  ![current_state](https://cloud.githubusercontent.com/assets/2546601/8235470/16a15aa8-15da-11e5-8e0d-fbae6c05e8d4.png)

<h3>Plans for the Near Future</h3>

  1. **Memory Dump Graph Metric Calculation** (namely *subsystem size* and *effective size*)

  Design document: https://docs.google.com/document/d/1GvzDP-tTLmJ0myRhUAfTYWs3ZUFilUICg8psNHyccwQ/
  Additional examples: https://docs.google.com/document/d/1lep61tPukPOGtZkjMWO_5dmWP7Zvh6ZUhdy84nFY0MQ/
  Patch adding subsystem size: https://codereview.appspot.com/246240043/

  2. **Memory Dump _Multi_-Selection Analysis Sub-Views**

  Mock UI:
  ![diff_mock](https://cloud.githubusercontent.com/assets/2546601/8235880/8d4f5fa4-15dc-11e5-8d84-347c24cc6c8e.png)

**Comment by natduca** [comment]
Would it make sense to mark this fixed and start a fresh bug for the
followons? I don't have strong preference just thinking out lodu :)

**Comment by petrcermak** [comment]
Even though memory-infra has gone public, I still consider this *work in progress* (will stay this way for a couple more months probably), so I'd prefer keeping all of this within one issue. From a more practical point of view, having one tracking bug allows us to easily keep track of what we have done so far.
