### ISSUE TITLE
Unable to sort homogenous events

### ISSUE THREAD

**Issue by benshayden** [google/trace-viewer#850]
Collect a trace, search for [performLayout] so that there's only one matching event type but many matching events. There should be two tables in the lower frame: the top table summarizes the various event types and is sortable with up/down triangles(ironically, since there's only one event type); the bottom table lists all of the matching events and is not sortable, with no up/down triangles.
Repros from tip of tree but not dev channel.

**Comment by dj2** [comment]
I believe these are sorted in chronological order. Can't reverse the sort order at the moment.

**Comment by benshayden** [comment]
It doesn't look like it's always in chronological order. Sorting by cpu duration is more useful to me, anyway.

Title: FrameView::performLayout
Category: blink,benchmark
Start	Wall Duration (ms)	CPU Duration (ms)	Self Time (ms)	Args
988.897 ms	0.301 ms	0.306 ms	0.291 ms	
989.301 ms	0.158 ms	0.164 ms	0.149 ms	
990.864 ms	0.15 ms	0.154 ms	0.141 ms	
1,042.134 ms	7.045 ms	2.071 ms	7.033 ms	
1,053.706 ms	0.152 ms	0.159 ms	0.141 ms	
2,631.32 ms	0.539 ms	0.545 ms	0.528 ms	
1,049.403 ms	0.518 ms	0.523 ms	0.508 ms	
31.303 ms

**Comment by natduca** [comment]
We're in the mist of a rewrite of how we do the lower tables #796 so we can try to make this more sane in that context. @Apeliotes is working on the lower table in that bug, so there's hope... question is, do you need us to fix this in ToT or can we wait a bit for the rewrite?

**Comment by benshayden** [comment]
How long will the rewrite take?
It'll just be a bit harder to classify layouts without it.
I sort by time in order to find slow layouts that aren't explained by the analyzer counters as I have them now. When I find such a layout, I can look for clues in the page to see what other types of layout objects I should count. I can still find slow layouts without sorting, but it takes a lot longer.

**Comment by natduca** [comment]
I'm cutting over to the new implementation tonight. Maybe you can check your use case when you come in Monday?

**Comment by benshayden** [comment]
Error occured at /json/begin_recording?omitted   at
chrome://tracing/tracing.js:302:255

Line 302 reads:
throw new Error('Non-POST should have data==null');req.open(method,
path,true);req.onreadystatechange=function(e){if(req.readyState==4){window.
setTimeout(function(){if(req.status==200&&req.responseText!
='##ERROR##'){resolve(req.responseText);}else{reject(new Error('Error
occured at '+path));}},0);}};req.send(data);});}

cat third_party/trace-viewer/.git/refs/heads/master
0602207b3fe2c903b92ab18dbf90bbf42de2a40f

**Comment by natduca** [comment]
sounds like #885 ... @nedn wdyt?

**Comment by nedn** [comment]
Hi Ben, when you roll the DEPs, you also need to apply these change to tracing_ui.cc since we change how recording mode works in trace-viewer.
https://codereview.chromium.org/1033223008/diff/1/content/browser/tracing/tracing_ui.cc

Sorry for the inconvenience!

**Comment by benshayden** [comment]
Looks like sorting is working again. Thanks!
