### ISSUE TITLE
Unify rendering tracks behavior

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#859]
The rendering tracks (<tt>ChartTrack</tt>, <tt>RectTrack</tt>, and <tt>LetterDotTrack</tt>) currently differ in the way they handle **event selection**. More specifically, they suffer from the following issues:

* Keyboard navigation (selecting the previous/next event when pressing the left/right arrow) is completely broken on the <tt>AlertTrack</tt> (subclass of <tt>LetterDotTrack</tt>).
* Selection state propagation (from the model object to the corresponding displayed item) is either explicit (see <tt>AlertTrack</tt> which proxies <tt>selected</tt> but not <tt>selectionState</tt>), or works only because the model object and the corresponding displayed item are identical (see <tt>SampleTrack</tt> which extends <tt>RectTrack</tt>).

To address these issues, I think that we should add an abstract subclass **<tt>RenderingTrack</tt>** of <tt>HeadingTrack</tt> which would unify this functionality:

```
// Abstract method.
getModelEventFromItem: function(item) {
  throw new Error('Not implemented.');
},

// Proxy selectionState property from the model object to the item.
getModelEventSelectionState: function(item) {
  var event = this.getModelEventFromItem(item);
  if (!event)
    return SelectionState.NONE;
  return event.selectionState;
},

// Proxy selected property from the model object to the item.
getModelEventSelected: function(item) {
  var event = this.getModelEventFromItem(item);
  if (!event)
    return false;
  return event.selected;
},

// Helper function to find the offset of the item corresponding to a given event.
// This method would be used in addItemNearToProvidedEventToSelection().
getModelEventOffset: function(items, event) {
  return items.map(this.getModelEventFromItem.bind(this)).indexOf(event);
}
```

Here's the resulting class hierarchy:

![renderingtrack](https://cloud.githubusercontent.com/assets/2546601/6873222/0ea0c0e6-d46c-11e4-8180-324f5845ab47.png)

@natduca, what do you think?

**Comment by natduca** [comment]
Hmm!

getModelEventSelected I'd prefer not to have --- that value is accessed in a tight inner loop so I would prefer that the selected state be provided on the event objects directly [via a getter there but theoretically optimizable down the road].

Otherwise, I think this is great.

**Comment by petrcermak** [comment]
**getModelEventSelected Performance Concern**

When you say "on the event objects directly", do you mean directly on the *items* (e.g. dots) rather than the corresponding *model events* (e.g. alerts)?

I see the performance concern, but on the other hand this (not providing the <tt>getModelEventSelected</tt> method) means that we effectively need to implement <tt>getModelEventFromItem</tt> twice for every model track because <tt>item.selected</tt> will almost always proxy <tt>corresponding_model_object.selected</tt>.

Also, if we add <tt>getModelEventSelectionState</tt> but not <tt>getModelEventSelected</tt>, there will be a risk of inconsistent behavior because <tt>selected</tt> is currently defined inside event.html as <tt>item.selected === true</tt> iff <tt>item.selectionState === SelectionState.SELECTED</tt>. In this case, it might be easier to make the item provide both <tt>selected</tt> and <tt>selectionState</tt> (i.e. implement neither <tt>getModelEventSelected</tt> nor <tt>getModelEventSelectionState</tt>). The automatic definition of <tt>selected</tt> could be preserved by splitting <tt>Event</tt> into <tt>Event</tt> and <tt>ModelEvent</tt>. All rendering events (e.g. dots, chart bars, rects, ...) could then derive from an abstract <tt>RenderingEvent</tt> superclass whose constructor would have a <tt>ModelEvent</tt> argument:

![rendering events 1](https://cloud.githubusercontent.com/assets/2546601/6896435/3c7bf408-d6e3-11e4-8a9f-fef09f4854a1.png)

**Model Events Setters**

The setters for <tt>rects</tt>, <tt>series</tt>, and <tt>dots</tt> are currently *not* shared.

**ObjectInstanceTrack**

Yes, I think that all heading tracks should ideally be separated between *model* tracks and *rendering* tracks.

**Comment by natduca** [comment]
I am not supportive of getModelEventSelectionState. Please proxy.

The reason is because for the common case --- tracks showing model content --- it is fast. I would prefer slow down the non-common case for now.

Thanks!

**Comment by petrcermak** [comment]
Here's the design of the <tt>SelectableItem</tt> and <tt>RenderingItem</tt> classes as discussed with @natduca yesterday:

![selectable renderingitem design](https://cloud.githubusercontent.com/assets/2546601/7048070/7ee339d8-de08-11e4-96fa-b2f1c37e90fe.png)
