### ISSUE TITLE
Our use of Chai assertions are using wrong expected/actual order

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#869]
chai assertions are of form assert.x(actual, expected)

That way when an assertion fails you get something like
AssertionError: expected [] to deeply equal [ Array(2) ]

But most of the assertions written in the code are the reverse, that is expected, actual. This makes errors confusing.

@qeny @eakuefner

**Comment by anniesullie** [comment]
I took a first pass at this in https://codereview.appspot.com/217510043/

**Comment by anniesullie** [comment]
Updated 2015 assertions. There are still some multi-line ones left, but we'll fix those as we hit them.

**Comment by dj2** [comment]
Awesome, thanks.
