### ISSUE TITLE
Should interval_tree ever update Node.lowValue?

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#870]
As far as I can tell, the low value is never updated. Is this intentional?

I would have expected the balancing operations to update low...
https://github.com/google/trace-viewer/blob/master/trace_viewer/base/interval_tree.html#L335

**Comment by natduca** [comment]
(Back story: I really don't get how to extend this tree to do inclusive searches. If you want to make this test case pass and ignore this specific bug, be my guest:
  test('findIntersection_zeroDurationA', function() {
    var tree = new SimpleIntervalTree();
    var v1 = tree.insert({start: 0, end: 2});
    var v2 = tree.insert({start: 2, end: 2});
    var v3 = tree.insert({start: 2, end: 4});
    debugger;
    var intersection = tree.findIntersection(2, 2);
    sortSimpleResults(intersection);

    var expected = [v1, v2];
    assert.deepEqual(intersection, expected);
  });

)

**Comment by natduca** [comment]
@dj2 any ideas?

**Comment by dj2** [comment]
Honestly, I have no idea at the moment. I'd need to go back and re-read the paper describing interval trees to figure out why it's that way. I should hopefully have some time next week to look into it.
