### ISSUE TITLE
Make table builder rows selectable

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#872]
As discussed in #808, the selected row should be blue as in devtools:

![image](https://cloud.githubusercontent.com/assets/2546601/6895951/bb0ecbfc-d6dd-11e4-92b8-00d6f7776ae3.png)

**Comment by natduca** [comment]
I need this for mssv transition so taking...

**Comment by natduca** [comment]
This is fixed, I think. Feel free to reopen a new bug if you want specific features, yea?
