### ISSUE TITLE
Add hotkey for selecting all events

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#874]
I think it would be a nice feature to have **Ctrl+A** select all events on the timeline. It would be useful in connection with **f** (zoom into selection).

**Comment by dj2** [comment]
So, this is basically a way to reset the zoom? Would it be easier to just have a hotkey that resets to the timeline filling the window? (Similar to cmd-0 to reset zoom on mac?)

**Comment by petrcermak** [comment]
Oh, I didn't realise we already had that functionality. It turns out that **0** (zero) does precisely what I had in mind.

Anyway, why does the help say "<tt>z/0</tt> Reset zoom and pan"? **z** doesn't seem to do anything.

**Comment by randomascii** [comment]
Ctrl+A is sufficiently standard that we should consider implementing it just for completeness, unless there is some complexity or confusion in doing so.

**Comment by petrcermak** [comment]
I completely agree with @randomascii. That is actually how I came up with the idea - I subconsciously tried using Ctrl+A and it didn't work :disappointed: 

Another standard hotkey is **Esc** for "deselect everything". I think that such *standardization* would make Trace Viewer more intuitive for our users.

**Comment by natduca** [comment]
Seems fine. Patchify us and we can lg. :)
