### ISSUE TITLE
Tracing inserts noise into browser UI traces

### ISSUE THREAD

**Issue by danakj** [google/trace-viewer#877]
The tracing code constantly changes the tab's title with a blinking square, and % updates. This makes it very noisy for profiling the browser process, as I can't tell what is tracing's updates and what are the things I want to measure.

I hacked out changing document.title and everything was lovely. Can this be optional maybe or something?

**Comment by natduca** [comment]
I think this is a great point. I wonder what we should do... @dj2 ideas?

**Comment by dj2** [comment]
I say kill it with fire. Does anyone ever use that feature anyway?

**Comment by natduca** [comment]
Let's do it. It's the only way to be sure.

**Comment by kphanee** [comment]
Can we make it optional as @danakj suggested?

**Comment by natduca** [comment]
I'm not really into more options, honestly. I think "it just works" is a
good model to follow here.

**Comment by dj2** [comment]
Fixed with f0c88f29ead40897b4743bf7deb0808ff96fbbd3
