### ISSUE TITLE
Scrollbar occluded by tracks on Mac

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#879]
The following problem happens on Mac:

![scrollbar_bug](https://cloud.githubusercontent.com/assets/2546601/6946173/6f476e8a-d896-11e4-8e63-804876fba2f7.png)

Not sure if it's a Chrome or Trace Viewer issue.

**Comment by dj2** [comment]
Scrollbars shouldn't be able to go under anything, this seems like a chrome bug. Can you file a crbug, cc vollick and skobes

**Comment by petrcermak** [comment]
Filed in Chrome: https://code.google.com/p/chromium/issues/detail?id=473009. Closing this issue.
