### ISSUE TITLE
findLowIndexInSortedIntervals docs and impl/tests are inconsistent

### ISSUE THREAD

**Issue by ChrisCraik** [google/trace-viewer#882]
The tests say returning array length is valid if the value doesn't land within an interval:

https://github.com/google/trace-viewer/blob/4b32454f3d9fb04e744985ac103c1f8ff8e35cf8/trace_viewer/base/sorted_array_utils_test.html#L100

The implementation agrees, but the documentation for the method says:

"Finds an index in an array of intervals that either intersects the provided loVal, or **if no intersection is found, the index of the first interval whose start is > loVal.**"

Could change doc to agree with impl/tests, but should probably remove 'low' from the name in that case.

**Comment by ChrisCraik** [comment]
If it's a matter of changing the doc, should also remove the word 'low' from the name for clarity.

**Comment by natduca** [comment]
This function is an abomination. I hacked and hacked on it until I stopped seeing bugs in the rendering. But its a piece of code that I often look at and think is beyond-repair....

Not sure what we should do, though! I like your idea of just making the documentation not lie...

**Comment by ChrisCraik** [comment]
Fixed with https://github.com/google/trace-viewer/commit/ef4d043769f7a6c3f48b3804705bbcb71a87b322

(I think I messed up the link in the description)
