### ISSUE TITLE
about:tracing record button throws exception using ToT

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#885]
This is rumored in #880. We need to fix to roll DEPS.

**Comment by natduca** [comment]
@dj2 @nedn if you have a stack lemme know and I can dig in. I don't have a build locally right now

**Comment by nedn** [comment]
I will take charge of fixing this.

**Comment by nedn** [comment]
I am able to run record button without any problem. I think you probably forgot to apply the change to tracing_ui.cc as in https://codereview.chromium.org/1033223008 ?

**Comment by natduca** [comment]
I assume this is fixed?

**Comment by nedn** [comment]
I would close this after I land the DEP roll and have https://code.google.com/p/chromium/issues/detail?id=469646 verified.

**Comment by anniesullie** [comment]
I am likely the original reporter, I did not apply the change to tracing_ui.cc as @nedn mentioned in an above comment. So there's likely no issue here. Sorry for the noise!

**Comment by nedn** [comment]
Ah, this is mostly my fault for being cowboy about not maintaining backward compatibility in the update window :P
