### ISSUE TITLE
Get rid of analysis_results in favor of tv-b-ui-table

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#887]
A few subviews still use them:
- CounterSample*
- MultiGlobalMemoryDump
- MultiObjectSubView
- SingleObject*
- SingleSample
- RasterTaskView

**Comment by natduca** [comment]
@zeptonaut this'd be a really good code health activity if you were up for it. The remaining class that needs converting is counter_sample_sub_view.html...

**Comment by zeptonaut** [comment]
Yea, I'd be happy to take this on!

**Comment by philippebeaudoin** [comment]
Once this is closed this should allow us to close #1115.
