### ISSUE TITLE
trace_viewer's size is big

### ISSUE THREAD

**Issue by nedn** [google/trace-viewer#891]
With the latest build, size of trace_viewer_chrome is 1365048 bytes.
stat -c%s bin/trace_viewer_chrome.html
1365048

(https://travis-ci.org/google/trace-viewer/builds/57314715)

In the last deps roll of trace-viewer in chromium/src/, the size of trace_viewer_chrome was 1049724 bytes. So the diff is about 315 KB, which is still too big.

**Comment by nedn** [comment]
@natduca 
I found out that the old vulcanize_trace_viewer actually used closure-compiler.appspot.com hence able to reduce its js size from 1471225 bytes -> 810136 bytes.

With the tracing hackathon + Annie's change to use rjsmin, the js size is 1594005 bytes and the minified version's size is 1120968 bytes.

To summary, with vulcanize_trace_viewer script on local desktop:
+Old trace_viewer_chrome.html:
   _polymer: 112740 bytes
   _js: 810136 bytes (minified with closure, non-minified size is 1471225 bytes)

+Latest  trace_viewer_chrome.html:
   _polymer: 124014 bytes
   _js: 1120968 bytes (minified with rjsmin, non-minified size is 1594005 bytes)

Hence if we diff the trace_viewer_chrome.html's size, the bytes dif is 1120968 + 124014 - 810136 - 112740 = 322106 bytes.

But this diff may not be the same as the diff of trace viewer in chrome, depending whether Chrome is using the closure minified version or not.

**Comment by natduca** [comment]
Ah, this is really useful! Chrome uses ./trace_viewer/build/generate_about_Tracing_contents.py if its useful ... that doesn't using any minification [or didn't]. So, assuming thats been updated to do minifciation, we should be going from the old nonminified = ~1.5ishmb to the new minified, ~1.3ishmb?

**Comment by anniesullie** [comment]
My understanding matches Nat's; before my changes minification in Chrome was off by default, so we should be going from 1.5->1.3.

If we are going to further optimize trace-viewer's size in Chrome, we should first ensure that the sizes test is giving us good numbers by switching it to test official builds. Then we should check if resources like trace-viewer are gzipped.

**Comment by nedn** [comment]
I verified that the size goes down with this (https://codereview.chromium.org/1066903002/).
