### ISSUE TITLE
Compute slice cpuDuration from ThreadTimeSlices when present

### ISSUE THREAD

**Issue by ChrisCraik** [google/trace-viewer#892]
When writing alerts, (especially analyzing those slices which are pure CPU work), would be useful to separate the scheduling concerns from those where too much work is being done.

Currently I'm writing a lot of "alert if duration > 3ms", where I'd prefer to say "alert if cpuDuration > 3ms".

Maybe this could be part of the createSubSlices() post processing of slices.

**Comment by natduca** [comment]
!!! YESSS !!!

ALL OF THIS PROPOSAL IS <3

**Comment by martijncoenen** [comment]
I can work on this as it's related to the stuff I've been doing. One tricky thing could be how to define "too much work being done on CPU". For example, we could be running at different frequencies, and with newer devices even on different capacity cores (A53 vs A57). So this potentially introduces one new type of "scheduling bug": if rendering would have completed fine on an A57, but not on an A53.

Would be cool if we could somehow represent this as well, but for the first iteration let's keep it simple.

**Comment by martijncoenen** [comment]
Fixed.

**Comment by ChrisCraik** [comment]
Now in use for a few Android alerts: https://github.com/google/trace-viewer/commit/0c6bc796fa9ccb35212bc70987bb3573f72ca931
