### ISSUE TITLE
Trace Viewer fails to load because of duplicate ready() method in tracing-analysis-tab-view

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#893]
I get the following **module loading failure** when accessing the dev server:

```
Error: Uncaught SyntaxError: Duplicate data property in object literal not allowed in strict mode
http://localhost:8003/core/analysis/tab_view.html:171
    at Object.<anonymous> (http://localhost:8003/base/unittest/suite_loader.html:152:13)
```

The problem is caused by duplicate <tt>ready()</tt> method in core/analysis/tab_view.html. It was introduced in e813c643.

I'm surprised that this issue did not show up on Travis CI, which is still green.

**Comment by petrcermak** [comment]
This (the fact that the issue did not show up on Travis CI) turns out to be a **bug in Chrome dev**: http://crbug.com/474526.

**Comment by petrcermak** [comment]
It turns out that this is **working as intended** in ES6. In that case, do we want to keep the duplicate <tt>ready()</tt> method (even though it will now make Trace Viewer not work on Chrome stable)?

**Comment by natduca** [comment]
Sorry about that, thanks for debugging!
