### ISSUE TITLE
No Frame and FrameTrack tests

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#898]
There are currently **no tests** for either <tt>Frame</tt> or <tt>FrameTrack</tt>. This makes it difficult to refactor the code.

**Comment by petrcermak** [comment]
For the track, I think you should test *instantiation* and *model mapping* (see alert_track_test.html for an example). The frame might not need any tests at this point.

**Comment by ChrisCraik** [comment]
FrameTrack tests added. Happy to add frame tests as well if there's useful behavior to test.
