### ISSUE TITLE
Thread Time Slice analysis table background stripes issue when state not 'Running'

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#899]
The following visual issue occurs when the thread is *not* in a "Running" state:

![screenshot from 2015-04-08 16 51 40](https://cloud.githubusercontent.com/assets/2546601/7049251/0b4fe9dc-de10-11e4-9096-a3876e508f79.png)

The reason for this is that the "On CPU:" row has only one cell.

This is probably a *low-priority* issue given that it doesn't have any impact on Trace Viewer functionality and we are replacing tables with <tt>TableBuilder</tt> anyway.

**Comment by natduca** [comment]
@ChrisCraik fyi

**Comment by natduca** [comment]
@zeptonaut wanna take a crack at this? The idea would be to move this over to base/ui/table...
