### ISSUE TITLE
Filtering architecture is confused

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#900]
When you enter anything into the search box while displaying Android Systrace, **nothing happens**:

![screenshot from 2015-04-09 17 26 24](https://cloud.githubusercontent.com/assets/2546601/7071512/b617cf10-dedd-11e4-93c2-2e2c15183e4b.png)

The filtering is currently broken because of an exception thrown in the "Interactions" <tt>RectTrack</tt>:

```
TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.TitleOrCategoryFilter.matchSlice (filter.html:61)
    at f.RectTrack.addAllObjectsMatchingFilterToSelection (rect_track.html:189)
    at f.ContainerTrack.addAllObjectsMatchingFilterToSelection (container_track.html:86)
    at f.<anonymous> (container_track.html:94)
    at Object.Task.run (task.html:65)
    at runAnother (task.html:112)
    at runTask (raf.html:51)
    at processRequests (raf.html:79)
```

There currently are two problems with filtering on the <tt>RectTrack</tt>:

1. the track incorrectly tries to match the filter against the *proxy item* (<tt>rect</tt>) rather than the associated *model item* (<tt>rect.modelItem</tt>)
2. the track incorrectly assumes that the item it's showing is a <tt>Slice</tt> (it calls <tt>filter.matchSlice(rect)</tt>) even though that is not always the case ← **this is what's causing the exception**

**Comment by petrcermak** [comment]
We discussed this with @skyostil and identified two things that we think should be changed:

1. The ***tracks* currently decide which filtering method to call on the model items** (e.g. <tt>filter.matchSlice(item)</tt>). This is not a good design because a track is essentially just a container that should have as little knowledge about the model items it's displaying as possible. Moreover, some tracks (namely <tt>RectTrack</tt>, <tt>LetterDotTrack</tt>, and <tt>ChartTrack</tt> in the near future) were refactored to display *proxy* items (e.g. a letter dot) instead of  *model* items (e.g. an alert) so they do not have any simple way to determine which matching method to call (because filtering is done on model items).
2. Given that all filtering is done on *model* items, there is **no need to perform filtering by traversing tracks**. Instead, we could simply traverse the **model** itself instead. This could have a performance benefit because the model doesn't contain *duplicates* (there might be multiple tracks showing the same model item). On the other hand, this would have two potential drawbacks:
    1. We wouldn't be able to filter on *non-model things* (e.g. track name) easily if we wanted.
    2. There would be a larger "gap" between the search box and the new *console* (which inherently depends on the tracks because of predicates like <tt>hasParent</tt>).

The first issue could be addressed as follows:

- Rather than the track (e.g. <tt>RectTrack</tt>), the **model items** (e.g. <tt>*Slice*</tt>) **should be responsible for calling the correct filtering method** (e.g. <tt>match*Slice*</tt>) themselves. Together with proxy items, this would lead to the following call chain: <tt>*track*.addAllObjectsMatchingFilterToSelection</tt> → [<tt>*proxyItem*.addToSelectionIfMatchingFilter</tt>] → <tt>*modelItem*.addToSelectionIfMatchingFilter</tt> → <tt>filter.matchSlice</tt>. It does add at least one extra layer of indirection, which might have a small performance impact. However, this change (or a similar one) seems inevitable.

Arguably, model items (e.g. <tt>Slice</tt>) *should not be aware of filtering*. Therefore, a cleaner approach would be to define a **visitor pattern** over the model items (e.g. <tt>modelItem.visit(visitor,opt_ arg)</tt> → <tt>visitor.visitSlice(modelItem, opt_arg</tt>), which the filtering mechanism could hook into. The drawbacks of this approach are potential *over-engineering* and worse performance (due to yet another layer of indirection).

Note that having a visitor pattern over the *whole* model (including containers) would allow us to implement the second change (filtering through model rather than tracks) easily.

@natduca, @dj2: What are your thoughts on this?

**Comment by natduca** [comment]
Suppose we implement a feature where some model items arent visible in the ui? Then you say "find".

It would be surprising to see the things that are hidden.

Therefore, we need a way to make finding work for things that are visible.

BUT!!!! The find feature predates the Viewports eventToContainerMap. If an event is not in the e2cmap then it isn't visible. So we could have the find functionality be on the view, but be driven primarily by an iteration of all model events, checked purely by the e2cmap

**Comment by natduca** [comment]
one other note: not every model event has a category filter, so title&cat filter is busted too... mabye it should but category is not on the base event for some unknown reason.

**Comment by natduca** [comment]
We should totally clean this up here, but this was blocking rolling updated versions into Android and Chrome so Chris and I came up with a not horrifying short term fix that unblocks things. Lets keep chatting about the proper arch here and when we have it I'd be happy to help make it happen.
