### ISSUE TITLE
Multi-line string event args need white-space: pre styling.

### ISSUE THREAD

**Issue by benshayden** [google/trace-viewer#915]
LayoutTreeAsText without white-space: pre:
![string-arg-no-pre](https://cloud.githubusercontent.com/assets/1566089/7191068/a0f5b644-e43f-11e4-8ae4-e80b42e8e2f1.png)

With white-space: pre:

![string-arg-pre](https://cloud.githubusercontent.com/assets/1566089/7191009/1fedf868-e43f-11e4-9756-7ab6b9f499a8.png)

**Comment by natduca** [comment]
On it

**Comment by natduca** [comment]
Should be fixed. Marking closed but feel free to reopen? We'll need to dep roll for ToT to take effect, though... if you're up for a learning experience, I could use help rolling deps... https://github.com/google/trace-viewer/wiki/Contributing#updating-chromiums-abouttracing
