### ISSUE TITLE
Remove frame prioritization code, once frame selection/highlight is reworked

### ISSUE THREAD

**Issue by ChrisCraik** [google/trace-viewer#916]
Should revert: https://github.com/google/trace-viewer/commit/f153060e5b5c062a0c405ff1cfc36973d975abd0

**Comment by petrcermak** [comment]
Selecting events of two or more different types (e.g. Counter Samples & Slices) has been **broken** since f153060.

```
Uncaught TypeError: Cannot read property 'localeCompare' of undefined
    (anonymous function) @ analysis_view.html:150
    selection @ analysis_view.html:144
    TimelineView.onSelectionChanged_ @ timeline_view.html:604
    dispatchSimpleEvent @ events.html:46
    TimelineTrackView.setSelectionAndHighlight @ timeline_track_view.html:771
    selection @ timeline_track_view.html:675
    TimelineView.onRequestSelectionChange_ @ timeline_view.html:618
    TimelineTrackView.onEndSelection_ @ timeline_track_view.html:1054
    MouseModeSelector.onMouseUp_ @ mouse_mode_selector.html:393
    cleanupAndDispatchToMouseUp @ mouse_tracker.html:98
```

Is it a known issue that will be fixed soon?

**Comment by natduca** [comment]
https://github.com/google/trace-viewer/commit/40cfb5830639a87960b1d1acfaebbf5d46a24d94 fixes this maybe?

**Comment by petrcermak** [comment]
Yes, I can confirm that the issue is now **fixed**. Thanks!

**Comment by ChrisCraik** [comment]
Fixed with https://github.com/google/trace-viewer/commit/b4cd47900f49e8a383b19414b876060b13739e1f
