### ISSUE TITLE
CounterTrack has highdpi issues

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#918]
It moves around when i zoom

**Comment by petrcermak** [comment]
As I suspected, the problem is caused by the fact that I ***incorrectly* assumed that <tt>viewport.currentDisplayTransform</tt> is *not* pre-multiplied by <tt>pixelRatio</tt>**. I will upload a fix shortly.

**Comment by petrcermak** [comment]
This should now be **fixed**.
