### ISSUE TITLE
RAILIRFinder needs to provide associatedEvents for all gestures & e60rs it finds

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#919]
@paulirish fyi

**Comment by yuhao** [comment]
gestures is already provided with associatedEvents, isn't it?

ir.associatedEvents.push.apply(
  ir.associatedEvents,
  gesture.latencyEvents);

Or you actually meant sth different?

**Comment by natduca** [comment]
First, gesture.latencyEvents isn't computed correctly. It should be all slices that the input affected, on all threads. That's not what it is now.

Second, e60rs  don't have associated events being computed.

**Comment by natduca** [comment]
Yuhao is going to drive this.
