### ISSUE TITLE
Left and right arrow keys work in a weird way if multiple slices are selected

### ISSUE THREAD

**Issue by skyostil** [google/trace-viewer#925]
1. Select multiple slices in vertically different tracks.
2. Press the left or right arrow a few times.

=> The selection gradually breaks up into vertically separate chunks depending on the trace layout. This seems to be because each selected slice is "moved" indepedently.

**Comment by petrcermak** [comment]
As I said offline, I don't see a simple solution to this issue (except for another major redesign of selection) and it's **not restricting usage** of Trace Viewer in any way so I'd ignore this for the time being.

**Comment by skyostil** [comment]
Yeah, it's not really P1, more of a minor annoyance. I wonder though if it suggests some disconnect in how we're modeling selections and how the user is seeing them.
