### ISSUE TITLE
Add cell selection support to table builder

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#928]
Per discussions with @petrcermak

**Comment by natduca** [comment]
I'm finally making headway https://codereview.appspot.com/236840043

**Comment by petrcermak** [comment]
I have quickly read through the code and here are some of my thoughts/questions:

So there will be two boolean flags <tt>supportsSelection</tt> and <tt>cellSelectionSupported</tt>? What if <tt>supportsSelection == false</tt> and <tt>cellSelectionSupported == true</tt>?

Is there any reason to expose a <tt>selectedColumnIndex</tt> setter when we don't do the same for the selected row? Shouldn't we hide it inside the on click handler as well?

**Comment by natduca** [comment]
For the first, its allowed. The supportsSelection turns selection on and off. The cellSelectionSupported is more of a toggle between selection modes.

We have a setter for selectedRow.
