### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of undefined", source: chrome://tracing/tracing.js (428)

### ISSUE THREAD

**Issue by wjmaclean** [google/trace-viewer#930]
Cannot read property 'getBoundingClientRect' of undefined", source: chrome://tracing/tracing.js (428)

This is the error I get every time I attempt to navigate in Tracing right now, either via mouse or keyboard.

**Comment by wjmaclean** [comment]
@natduca @dj2

**Comment by natduca** [comment]
Try finding the chrome://tracing process and expanding it. Does it break? Or uncheck flow events...

**Comment by natduca** [comment]
I think if you cd third_party/trace-viewer && git fetch --all && git checkout origin/master things should work again... lmk if not?

**Comment by seumasmcx** [comment]
Yes, that seems to do the trick, thanks!
