### ISSUE TITLE
Change pre-commit hooks to pre-submit hooks

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#932]
I've just had a look at this and it seems to me that the classes in hooks/pre_commit.py very closely mirror the ones in **depot_tools**  (https://code.google.com/p/chromium/codesearch#chromium/tools/depot_tools/presubmit_support.py). Therefore, I think that the best approach would be to change our classes to have the same interface. Modifying PRESUBMIT.py (which uses the depot_tools classes) should then be very easy.

@natduca: WDYT?

**Comment by natduca** [comment]
They mirror it because they used to be it. But there is a fair amount of complexity here --- if you look at logs on the precommit hook, you'll find that I actually switched us from precommit once upon a time and because I was lazy, made some api incompatible changes to simplify the de-hooking.

I'd suggest we go back to presubmit first, using our input api. Then maybe we can revert back to the depot tools input api as a second step?

**Comment by petrcermak** [comment]
OK, but for that we will need to implement the *diff base* approach, I think.

**Comment by natduca** [comment]
Is this stalled?

**Comment by petrcermak** [comment]
I'd like to do this at some point in the near future, but there were more important things until now.

**Comment by dj2** [comment]
I've reverted 35c48d0 due to breaking other workflows. See #946 for details.

**Comment by natduca** [comment]
@anniesullie this blocks movign to catapult and we need to fix it asap

**Comment by petrcermak** [comment]
The move to Catapult should now be **unblocked**. The only thing that remains now (to finish the migration from pre-commit to pre-submit hooks) is to get rid of the wrapper classes (<tt>\_InputAPI</tt> and <tt>\_AffectedFile</tt> in hooks/pre_commit.py).

Note that everyone who ran the dev server before my last patch (0a629c4) will have a *dangling pre-commit hook* in their git repository, which can be removed by running <tt>rm .git/hooks/pre-commit</tt>. Should we add code to hooks/install.py which automatically removes it?

**Comment by natduca** [comment]
Yeah let's remove the old hook synlink or make the hook itself a no op

**Comment by anniesullie** [comment]
Not sure if I got this right: https://codereview.appspot.com/240910043/
