### ISSUE TITLE
Reintroduce statistics in multi-event-sub-view

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#933]
They were dropped in the conversion to mesv.

**Comment by benshayden** [comment]
https://www.wolframalpha.com/input/?i=%5B1%2C2%2C3%2C4%2C9%2C8%2C7%5D

**Comment by dj2** [comment]
Was the plan to put them back as tooltips? The discoverability of them was always pretty bad and you could never compare them to each other.

Would it work with the current table to have a subrow for the stats for each row?

**Comment by natduca** [comment]
I think a rollover element on mouse over might do the trick. I think we
want something compact by default because dense Display is also important,
hence the suggestion.

**Comment by dj2** [comment]
What about expandable rows? Collapse by default and expand to see statistics? This way you could expand multiple rows at the same time to compare. It's hard to compare different rows with tooltips.

**Comment by natduca** [comment]
I'd like to keep it to a single div, e.g not the full row, so its a more-reusable component... we have a lot of places in the ui that show a single number that is an average of many numbers, and it'd be good if we could get this functionality into all those places.

Perhaps we could have a click-to-expand widget, that might work. I bet we could get it to look like an expandable row but implementation-wise, it'd be a SpanThatDisplaysAListOfNumbers

**Comment by dj2** [comment]
Can the table builder do colspan? If so, make it a div, use an expand row and colspan the div into the expanded row. If not, we should make table builder understand colspan.

**Comment by benshayden** [comment]
Here's one way to arrange one or two abspos summary panels above a table so you can compare two columns at once. If you want to see summary stats for three or more columns, you could use a simple layout algorithm, but it might be easier to use a different UI and just do all of the columns at once.
Placing the panels above the table allows you to avoid relaying out the table, and they won't obscure any part of the table or require scrolling. They might obscure part of the timeline, but the timeline is so flexible that you should be able to work around that.
We can make it pop in when you mouse over any part of the column, and let you click to pin/unpin the panel.
We can make it big enough for summary stats, visualizations, tooltip descriptions, and just about anything else you might want.
Carets point to the context column, like chrome's extension popups and butter bars.
This picture of a whiteboard doesn't have to be the be-all-end-all or all-or-nothing. We can draw as many variations of these ideas as you want. For more about paper prototyping, here's a description of the basic idea and a link to the book that we used in college:
http://www.paperprototyping.com/what.html 

![15 - 1](https://cloud.githubusercontent.com/assets/1566089/7924479/6137f3d2-0870-11e5-954e-42d07d8fbf46.jpg)
