### ISSUE TITLE
Figure out workflow for bulk-testing RAIL traces

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#934]
Right now we have a separate github repo storing our test data for our RAIL prototype. I then have dirty hacks in trace-viewer to find that other repo and then use its test files when we want to study RAIL scores for a bunch of traces at once.

Ideally, this would be just be a matter of pushing a deep query at the deep reports server? Or maybe it'd be a matter of asking the deep reports server for a list of available reports, then individually xhr'ing them at runtime.

@fmeawad maybe you and I can brainstorm options here next week...

**Comment by fmeawad** [comment]
Scheduled a meeting on Tuesday.

**Comment by dj2** [comment]
As an aside, I put in a --data-dir option to run_dev_server. You can provide the path to your repo files and trace-viewer will use that directory to populate the drop down.
