### ISSUE TITLE
Misalignment of the 'Monitoring' text observed in chrome://tracing.

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#937]
![screenshot_tracing](https://cloud.githubusercontent.com/assets/412396/7360755/90ba3b2a-ed03-11e4-8aa9-9127f2a396c2.png)

**Comment by anniesullie** [comment]
https://codereview.appspot.com/231230043

**Comment by anniesullie** [comment]
This is submitted, should now be fixed.
