### ISSUE TITLE
Some usability improvemetns to chrome_*_helper

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#944]
@benshayden these bit us when you were getting used to the code. Wanna clean it up?

A few things that could be easy single patches:
- helper.renderers is a dict, but helper.renderProcesses is an array. could this be rational and predictable? renderers are actually helpers, too. Would be nice if there was helper.chromeRendererHelpers and renderProcesses and browserProcesses where the suffixes told you what you were getting ahold of?

- browser.renderers doesn't exist. you have to go to the helper to find the renderers. Seems wonky. helper.browsers[0].rendererHelpers 

DONE - tons of ad-hoc iteration code. Should we have actual methods on event_container.html for getting things by range and name and predicate? Should helper be an event container?

**Comment by natduca** [comment]
@yuhao a patch that fixes the first items mentioned above might be good first bugs.

**Comment by yuhao** [comment]
between a dict and an array, which one is preferred? I saw in some of the tests, the dict is explicitly used to hard code some pid.

**Comment by dj2** [comment]
The question would be, how do we use them? Do we always iterate from start to end, access specific processes or renderers? The use should dictate the types.

**Comment by natduca** [comment]
I figure we should go for dict as the common approach. And if there are cases that need an array, make a helper getter renderProcessesAsArray() {}.
