### ISSUE TITLE
Make all SliceGroups be constructed with a parent

### ISSUE THREAD

**Issue by martijncoenen** [google/trace-viewer#951]
See https://codereview.appspot.com/224270043/ for context.

**Comment by yuhao** [comment]
In extras/chrome/chrome_auditor_test.html:      rm1Slices.pushSlices(newImplRenderingStatsEvent(113));

Do we really want to use pushSlices even when we are just pushing one slice?

If we can make sure that we only push an array of slice, it is going to make the logic of pushSlices simpler. Comments?

**Comment by natduca** [comment]
oh wow i think thats a bug... pushSlices should only accept an array. if that is pushing a single slice, its probably a bug.

**Comment by yuhao** [comment]
alright i will try fix that and get reviewed.
