### ISSUE TITLE
vulcanized file has JavaScript errors

### ISSUE THREAD

**Issue by johnmccutchan** [google/trace-viewer#955]
$TRACE_VIEWER/vulcanize_trace_viewer --config=lean results in an html file with javascript syntax errors.

**Comment by natduca** [comment]
Can you check ToT? I suspect this was fixed in faedb69b9594562653d9f572e293a35ee31ffc06 and i just checked now and didn't see anythign...

**Comment by natduca** [comment]
Or, the errors you're seeing would be helpful.

**Comment by johnmccutchan** [comment]
--- /Users/johnmccutchan/workspace/trace-viewer/bin/trace_viewer_full.html	2015-05-18 06:48:04.000000000 -0700
+++ trace_viewer_full.html	2015-05-17 13:22:22.000000000 -0700
@@ -16148,7 +16148,7 @@
         node.setAttribute('selected', true);
       },

-      doesColumnIndexSupportSelection(columnIndex) {
+      doesColumnIndexSupportSelection: function(columnIndex) {
         var columnInfo = this.tableColumns_[columnIndex];
         var scs = columnInfo.supportsCellSelection;
         if (scs === false)

**Comment by johnmccutchan** [comment]
eh, that pasted weird.

**Comment by natduca** [comment]
Did you forget to put the encoding meta tag at the top of your html file? Check out index.html's metas...
