### ISSUE TITLE
Async trace markers performance regression

### ISSUE THREAD

**Issue by DavidYen** [google/trace-viewer#957]
There has been a big performance regression when using asynchronous trace markers. To reproduce simply go to about://tracing on the top of tree, and trace with gpu.service, gpu.device, gpu.decoder on any page. Even a few seconds of tracing makes the trace-viewer extremely slow.

Note that this was first reported here: https://code.google.com/p/chromium/issues/detail?id=478923

I am moving the issue here since it is trace-viewer specific.

**Comment by fmeawad** [comment]
My investigation so far: this started from trace-viewer shipped with chrome 43+
The issue is in trace-viewer and not in chrome (I tried ToT trace-viewer in chrome 42 and it was still slow)
The main issue is that we are spending more time in drawSlices (draw_helpers.html:141:22)
As you zoom in, the experience gets smoother, which verifies that it is related to drawing.

I suspect that we might no longer be concatenating slices into bigger FastRectRenderer when zoomed out, but I have not verified that yet.

**Comment by fmeawad** [comment]
I don't think this is specific to async slices, as the code that seems to be bottle-necked is for all slices.

**Comment by natduca** [comment]
@petrcermak any ideas?

**Comment by natduca** [comment]
David can you attach a reference trace?

**Comment by DavidYen** [comment]
Here's a simple trace, it' sjust

**Comment by DavidYen** [comment]
I'm not sure how to attach files here, but I wrote this simple python script to create a trace that is snappy on chrome stable (43) but unusable on TOT:
```
with open('test.json', 'wt') as f:
  f.write('{"traceEvents":[\n')

  for n in xrange(1000):
    for i in xrange(10):
      if n != 0 or i != 0:
        f.write(',\n')
      f.write('{"pid":1,"tid":2,"ts":%d,"ph":"b","cat":"test%d","name":"test%d","args":{},"id":"%s"},\n' % (n * 100, i, i, hex(n)))
      f.write('{"pid":1,"tid":2,"ts":%d,"ph":"e","cat":"test%d","name":"test%d","args":{},"id":"%s"}' % (n * 100 + 90, i, i, hex(n)))

  f.write('\n]}\n')
```

**Comment by natduca** [comment]
I figured it out. Its how we implemented #725

**Comment by natduca** [comment]
I believe this to be fixed. @DavidYen the test file you provided is smooth as silk now during interaction. I'd appreciate it if you pulled the trace-viewer into a local build of yours though and verified that it feels better on a fresh build, just to be sure. Marking closed, assuming I got this right, but like I said, totally cool to reopen if needed.

**Comment by DavidYen** [comment]
Just tested this using top of tree of trace-viewer, looks great now thanks!

**Comment by natduca** [comment]
@anniesullie fyi
