### ISSUE TITLE
could we have a "complete async event" like with complete duration event?

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#960]
A few folks have tracers that issue tons of async begin/end events. But, the async b and e end up duplicating a ton of data so the file gets le-big. The request from them is that we support a way to create an async event with a single event that contains a ts and a duration, like with 'X'

@xunjieli wdyt? Doable? We woudln't need to expose to chromium trace_event.h, just support it in the importer and update the format docs...

**Comment by dj2** [comment]
You'd also have to output the process/thread that each of those things started on, otherwise, why not just use an X event?

Something like:

{ph:'Y', stid:5, etid:6, spid:1, epid:2, name:'blah', ts:123, dur:24, ...}

Is there anything else that would be needed?

**Comment by xunjieli** [comment]
Yes, it is doable. I can help with modifying the importer code if you decided to go with this route.
What's the difference between tts and ts?  "tts" is not explained in the [docs](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/edit#heading=h.yr4qxyxotyw), and it isn't very clear on what it does in the code either. Anyone knows?

**Comment by DavidYen** [comment]
I believe ts is "timestamp" while tts is "thread timestamp". You can use
tts to figure out how much time was actually spent running that thread.

**Comment by xunjieli** [comment]
Makes sense. Thanks for the clarification!
