### ISSUE TITLE
How can I embed a TimeLineView inside of a div?

### ISSUE THREAD

**Issue by johnmccutchan** [google/trace-viewer#965]
Is it possible to embed a TimeLineView inside of a div (rather than the whole window)? I have something working but it has some issues:

1) The background color of the parent div leaks through into the tracks.

2) When I click on a slice the TimeLineView expands to be the full width of the window, unselecting the slice restores the original size.

I guess I'm wondering if this is supposed to work?

Thanks

**Comment by natduca** [comment]
It definitely should work, and I totally welcome patches to make it work. I'm a bit low on free time for a few weeks but if you ping me in a few weeks I could fix... if you're willing to poke...

#1 is probably fixable by patching timeline_view.css to have something like x-timeline-view { background-color: white}

#2 sounds like a bug in our use of flexbox. We have to set min-width: 0 on most items in a flexbox layout, but we often forget. When you do that, then you get the behavior you're describing. If you wanted to debug, get a selection in your timeline, then start display-none-ing children of the timeline view in inspector until the size returns to normal. Once you've found the "Deepest" item that when hideen makes this go away, you could ping this bug and discuss further. Probably, we need min-width: 0 on that item, or on one of its parents.

**Comment by johnmccutchan** [comment]
Because of some (unrelated to this bug) Polymer.js / Polymer.dart conflicts, I ended up embedding it inside an iframe.

**Comment by natduca** [comment]
I think its still a bug right? I think I'd like to leave this open since its clearly a real issue...
