### ISSUE TITLE
Move rail_.html to extras/rail

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#966]
We have rail in extras/auditor. Lets move it to extras/rail.

**Comment by natduca** [comment]
@yuhao wanna take this bug?

**Comment by natduca** [comment]
I'd suggest making extras/rail, and extras/chrome. Then move extras/audits/rail* to rail, and extras/chrome* to chrome.

I'd also suggest a separate patch that takes extras/audits/utils.html and moves it to rail/merge_events.html.

**Comment by natduca** [comment]
If you're feeling ambitious, once you've done those two pieces, a third patch that moves the remaining audit code to android/ would be very appreciated by @chriscraik

**Comment by natduca** [comment]
super bonus brownie points for updating go/railscore to explain where our code lives once this patch lands. :)

**Comment by ChrisCraik** [comment]
@natduca Just did the move for the android dir, but didn't touch the merging code since it's shared between rail and android.

**Comment by natduca** [comment]
Lets move it into core/analysis?
