### ISSUE TITLE
Flow event "next slice" binding is trace buffer dependent

### ISSUE THREAD

**Issue by scheibo** [google/trace-viewer#968]
See https://gist.github.com/scheibo/ba2ff1e603a1f09a4236 - if I open this in the trace viewer I get the error "event id 2147483649 does not end at an actual slice, so cannot be created.", when the flow event does in fact end at ts=9000 and "Link End 2" begins at ts=9000. The offending code is in 'findNextSliceAfter' which does a > check https://github.com/google/trace-viewer/blob/master/trace_viewer/core/trace_model/slice_group.html#L329 despite https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/edit#heading=h.4qqub5rv9ybk saying "A bit of detail on "next slice" binding rules: Next slice is defined as the next slice to begin >= the timestamp of the flow. That is, the order in the trace buffer is NOT used. This is because trace buffers are not required to be in ts-sorted order."

The order of the buffer *is* in fact used, as moving "Link End 2" to the bottom of the trace events will fix the issue (because the guid is now greater).

**Comment by dj2** [comment]
@natduca

**Comment by natduca** [comment]
Hmm! Definitely the text was wrong, I updated the text, is that better.

The core issue here is that we use trace buffer position when timestamps are the same. That is, if we see a flow that ends at ts=9000 and two slices at ts=9000 , we're supposed to use the position to resolve which of those slices is the bound slice.

I think possibly the current implementation is a bit over-conservative though: we don't even consider slices that are < the flow events guid, it sounds like? If you leave that event where it is but bump its ts to be 9001, does it parse?

**Comment by scheibo** [comment]
Yes, bumping the ts and leaving it where it is causes it to parse correctly. 

I'm fine with the requirement that trace buffer position is used when timestamps are equal, it just wasn't conveyed well in the documentation. The change to the text makes this clear, thanks. :)
