### ISSUE TITLE
centralize chrome specific extras in extras/chrome folder

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#970]
@benshayden maybe you can help

@yuhao you're doing some of this. you two should collaborate.

 this patch should be fixed when we have extras/chrome/cc/, extras/chrome/blink/, extras/chrome/gpu.

auditors can go in the toplevel extras/chrome folder.

**Comment by yuhao** [comment]
I moved cc and gpu. We can move blink when it is ready from @benshayden's side.

**Comment by natduca** [comment]
Sounds good I think we can mark this fixed.

**Comment by natduca** [comment]
Probably wanna move audits/utils.html to chrome though....

**Comment by natduca** [comment]
Yuhao, should we do the utils fix so we can close this?
