### ISSUE TITLE
Mysterious error when going to ToT trace viewer in canary

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#977]
Google Chrome	45.0.2408.0 (Official Build) canary (64-bit)
Revision	4394f60e3737bb334202a369e09d49e9d0c675eb-refs/heads/master@{#330848}
OS	Mac OS X 

![image](https://cloud.githubusercontent.com/assets/412396/7847878/84a97b18-047b-11e5-9ccb-4704040f8957.png)

:309 is
XhrBasedTracingControllerClient.prototype={__proto__:tv.e.about_tracing.TracingControllerClient.prototype,beginMonitoring:function(monitoringOptions){var monitoringOptionsB64=btoa(JSON.stringify(monitoringOptions));return beginXhr('GET','/json/begin_monitoring?'+monitoringOptionsB64);},endMonitoring:function(){return beginXhr('GET','/json/end_monitoring');},captureMonitoring:function(){return beginXhr('GET','/json/capture_monitoring');},getMonitoringStatus:function(){return beginXhr('GET','/json/get_monitoring_status').then(function(monitoringOptionsB64){return JSON.parse(atob(monitoringOptionsB64));});},getCategories:function(){return beginXhr('GET','/json/categories').then(function(json){return JSON.parse(json);});},beginRecording:function(recordingOptions){var recordingOptionsB64=btoa(JSON.stringify(recordingOptions));return beginXhr('GET','/json/begin_recording?'+

**Comment by natduca** [comment]
@dj2

**Comment by dj2** [comment]
Looks like one of the JSON parses is failing. Can you see the JSON requests in the network panel? If you can pull out the body from there we can see where the issue is. I'd guess we have ... something ... with a character that breaks JSON.

**Comment by natduca** [comment]
Hmmm haven't been able to repro this yet. Maybe close?
