### ISSUE TITLE
Upgrade beautiful soup from version 3 to 4.

### ISSUE THREAD

**Issue by qeny** [google/trace-viewer#978]
Perf dashboard (indirectly) depends on bs4; it would be best to only have one copy of beautiful soup in catapult, therefore we want to change tvcm to depend on bs4 instead of bs3.

However, this is actually non-trivial because in tvcm there is a subclass of BeautifulSoup called PolymerSoup, and bs4 makes changes to BeautifulSoup so that subclasses can't inherit/change properties in the same way.

(Some context about why "PolymerSoup" was added: #630 #631)

**Comment by natduca** [comment]
@petrcermak may be able to advise. We do need to fix this somehow, right?

**Comment by petrcermak** [comment]
I've looked at the bs4 source code and the *(non)nestable tags* (which were causing #630) seem to be gone completely. Could you try replacing bs3 with bs4 and getting rid of <tt>PolymerSoup</tt> (replacing it with <tt>BeautifulSoup</tt>)?

**Comment by qeny** [comment]
That apparently didn't work -- after doing that and running the tests, a bunch of the tests fail, so it looks like either the behavior of bs4.BeautifulSoup is different from PolymerSoup and/or it's different from bs3.BeautifulSoup.

**Comment by anniesullie** [comment]
Do you have a log of the errors?

**Comment by qeny** [comment]
Logs of the errors:

After just adding bs4 and using everywhere except for where polymer_soup is used: http://pastebin.com/raw.php?i=qpFvqUab

After adding bs4 and using it everywhere AND replacing polymer_soup with BeautifulSoup: http://pastebin.com/raw.php?i=kMnxyibf
