### ISSUE TITLE
chrome:tracing in content_shell: "Cannot set property 'checked' of null"

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#980]
(moved from https://code.google.com/p/chromium/issues/detail?id=492597)

If trying to edit categories in chrome://tracing opened in content_shell you get an error in the log and nothing happens.

**STEPS TO REPRODUCE**
 1. Open content_shell
 2. open chrome:tracing
 3. Click Record
 4. Click the triangle to the right of "Edit categories".

**EXPECTED**
The chance to enable memory-infra

**ACTUAL**
Nothing happens in the window. In the console there is 
"Uncaught TypeError: Cannot set property 'checked' of null", source: chrome://tracing/tracing.js (209)

**Comment by petrcermak** [comment]
I triaged the bug and the problem is as follows...

The exception is thrown in <tt>RecordSelectionDialog.onClickEditCategories</tt>. The reason is that some category filters in <tt>DEFAULT_PRESETS</tt> are *not supported* by the browser (and thus do not have a corresponding checkbox). The method tries to tick them (<tt>categoryEl.checked = true</tt>), which causes the exception.

```
...
for (var i = 0; i < this.currentlyChosenPreset_.length; ++i) {
  var categoryEl = document.getElementById(
      this.currentlyChosenPreset_[i]);  // Returns null if the category is not supported.
  categoryEl.checked = true;  // Throws the exception.
}
...
```

The simple **solution** is to skip checkboxes which don't exist:

```
...
for (var i = 0; i < this.currentlyChosenPreset_.length; ++i) {
  var categoryEl = document.getElementById(
      this.currentlyChosenPreset_[i]);
  if (!categoryEl)
    continue;
  categoryEl.checked = true;
}
...
```

This is probably the first thing that we should do. However, even when we do this, there will still be a subtle *inconsistency*: The category description div on the dialog (screenshot below), which shows a list of categories enabled by the preset (in small grey font under "Edit categories"), might contain categories which are not supported by the browser (and hence would have no corresponding checkboxes and wouldn't be traced).

![screenshot from 2015-05-28 11 11 01](https://cloud.githubusercontent.com/assets/2546601/7857678/456e4604-052a-11e5-9dd5-753f7972e331.png)

We should probably filter the list of displayed preset categories (or at least strike them out or something). An alternative (and possibly better) solution to the whole issue would be to filter out unsupported categories from <tt>DEFAULT_PRESETS</tt> before constructing the dialog.

@natduca, @anniesullie WDYT?

**Comment by anniesullie** [comment]
I'm fine with either solution above.

But I looked into issues #705 and #684 a while back, and it felt like the whole record dialog could really use a rewrite--any time we make changes it feels like we are playing jenga. If you think you can make a fix without the whole thing falling down, I'm okay to punt the refactor a little further down the road.

**Comment by natduca** [comment]
Good god this code is... I don't even. Petr it's amazing that you were able
to figure this out. I'm happy to fix this any way we can short term. Annie
is very right that the whole code needs a rewrite.

**Comment by dj2** [comment]
Let's put in the simple fix so we don't try to check a non-existent category. Don't worry about the inconsistency of the text at this point, I don't think it's a huge deal.

We can clean that bit up later when we take a longer look at the dialog.

**Comment by petrcermak** [comment]
OK. This should now be **fixed**, but I agree the record dialog should be redesigned (both from a software and a UI perspective).
