### ISSUE TITLE
When a latency info causes rendering, have LatencyInfo.associatedEvents include the slices up to the commit on that frame

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#981]
Yuhao is going to try to pursue this.

**Comment by yuhao** [comment]
Design sketch: https://docs.google.com/document/d/1cOgxbI9vjjO6p5ojD_DZpK25Lep27VB-Vol4xNR54PI/edit

**Comment by yuhao** [comment]
Close this because of this CL: https://codereview.appspot.com/244540043/
