### ISSUE TITLE
Automatically update trace-viewer drive app on new changes

### ISSUE THREAD

**Issue by anniesullie** [google/trace-viewer#987]
Every time a new change is committed to trace-viewer repository, the app engine app for drive integration should automatically be updated. Otherwise it will get stale pretty fast.

**Comment by anniesullie** [comment]
Official support for github push-to-deploy via jenkins: https://cloud.google.com/tools/repo/push-to-deploy

**Comment by nedn** [comment]
Can we make it update on all tests pass only?

**Comment by vinterstum** [comment]
nedn: Yeap.
