### ISSUE TITLE
Filtering no longer works as expected in Canary (45)

### ISSUE THREAD

**Issue by tkadlec** [google/trace-viewer#990]
In Canary, filtering no longer brings up the timing slices in the bottom frame. In Chrome, if I record a trace, complete it, and then start typing in the text box in the upper right, the bottom portion of the screen starts to display the different tasks (and the timing of each) that match what I'm typing.

In Canary, doing the same thing, the bottom frame remains empty until hitting return.

**Steps to reproduce:**
1. Capture a trace using chrome://tracing in Canary.
2. Click inside of the text box in the upper right and start typing 'Render' to filter the tasks. 

**Result:**
While the selected charts appear to change, the bottom frame will not update with timings and matching tasks.

**Comment by natduca** [comment]
I think this will fix it but would appreciate someone testing it out:
(239550043) ~/Local/chrome/src/third_party/trace-viewer $ git diff
diff --git a/trace_viewer/core/selection_controller.html b/trace_viewer/core/selection_controller.html
index 4122f96..80196e0 100644
--- a/trace_viewer/core/selection_controller.html
+++ b/trace_viewer/core/selection_controller.html
@@ -174,6 +174,7 @@ tv.exportTo('tv.c', function() {
     findTextChangedTo: function(allPossibleMatches) {
       var newBrushingState = this.currentBrushingState_.clone();
       newBrushingState.findMatches = allPossibleMatches;
+      newBrushingState.selection = currentFocus;
       this.currentBrushingState = newBrushingState;
     },

**Comment by dj2** [comment]
Pasting patches in github you need to put ``` before and after with a blank line before and after that. Otherwise ..... not so useful, heh.

**Comment by natduca** [comment]
Guhh thats what I get for rushing! sorry :)
