### ISSUE TITLE
Table selection not working in Chromium ToT

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#992]
The following exception is thrown upon clicking a selectable cell:

```
Uncaught TypeError: Failed to construct 'Event': parameter 2 ('eventInitDict') is not an object.
  Polymer.prepareToChangeSelection_   @ table.html:926
  selectedTableRow                    @ table.html:882
  Polymer.didTableRowInfoGetClicked_  @ table.html:861
  (anonymous function)                @ table.html:607
```

**Comment by petrcermak** [comment]
The problem is that we use **unsupported <tt>Event</tt> constructor syntax**:

<tt>new Event('selection-changed', false, false)</tt>

instead of the correct one (https://developer.mozilla.org/en-US/docs/Web/API/Event/Event):

<tt>new Event('selection-changed', {'bubbles': false, 'cancelable': false})</tt>

We do this in a couple of places. It should be very simple to fix.

**Comment by petrcermak** [comment]
Here's a fix: https://codereview.appspot.com/236400044/. It turns out that the arguments can be completely dropped in most cases because both <tt>bubbles</tt> and <tt>cancelable</tt> default to <tt>false</tt>.

**Comment by petrcermak** [comment]
This should now be **fixed**.

**Comment by natduca** [comment]
An alternative Is tv.b.Event which does wrapping of the crazy Dom event API

**Comment by petrcermak** [comment]
I decided not to use <tt>tv.b.Event</tt> because it relies on <tt>event.initEvent()</tt>, which is apparently *deprecated*: https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent. We should probably modify it (<tt>tv.b.Event</tt>) to use the <tt>Event</tt> constructor instead of <tt>event.initEvent()</tt>.
