### ISSUE TITLE
LoadInteractionRecord for canceled loads

### ISSUE THREAD

**Issue by benshayden** [google/trace-viewer#993]
RAILIRFinder should make a Load IR when there aren't any frames but there is a CANCELED netlog event.
Should that Load IR take a score penalty? The user might not have canceled out of pain, they might have just realized that they clicked the wrong link, so maybe the usual timing-based pain calculation should apply?
Not sure what to do when there's a frame and a CANCELED netlog event, or neither a frame nor a CANCELED.

**Comment by natduca** [comment]
Maybe stop relative to first paint matters.
And maybe we should see if there's a main resource failure signal that we
could use. Both might let us pick differing pain thresholds...

**Comment by benshayden** [comment]
A first draft of failed load IRs is done.
https://codereview.appspot.com/248740043/
https://github.com/google/trace-viewer/blob/master/tracing/tracing/extras/rail/rail_ir_finder.html

Looking at the netlog events sounds like part of #1078.
LoadIR.normalizedUserPain still needs to be implemented: #1144

Close this issue?

**Comment by natduca** [comment]
Sure thing.
