### ISSUE TITLE
Checklicense failure blocking DEPS roll

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#994]
The following error is thrown when we try to roll Chromium DEPS (https://codereview.chromium.org/1156613003/):

```
'third_party/trace-viewer/third_party/devscripts/licensecheck.pl' has non-whitelisted license 'GPL (v2 or later)'

FAILED

Please read http://www.chromium.org/developers/adding-3rd-party-libraries
for more info how to handle the failure.

Please respect OWNERS of checklicenses.py. Changes violating
this requirement may be reverted.
```

**Comment by petrcermak** [comment]
The problem is that 3543bc5019b49ca1f8e61395824a1451e2e01bdf **added third_party/devscripts/licensecheck.pl to _Trace Viewer_** which has a "GPL (v2 or later)" licence, which is not whitelisted in Chrome. Ironically, the error is **thrown by third_party/devscripts/licensecheck.pl in _Chromium_** (identical file!), which also has the licence and is whitelisted here: https://code.google.com/p/chromium/codesearch#chromium/src/tools/checklicenses/checklicenses.py&l=187.

I uploaded a fix for this issue to Chromium: https://codereview.chromium.org/1147903005/ (currently in review)

@nedn, @natduca, @dj2: FYI

**Comment by nedn** [comment]
Since you fix is landed, we can revert the revert now?

**Comment by petrcermak** [comment]
This should now be **fixed**.

**Comment by dj2** [comment]
Awesome, thanks Petr.
