### ISSUE TITLE
Display flow arrows when selected or highlighted

### ISSUE THREAD

**Issue by philippebeaudoin** [google/trace-viewer#995]
The current trace viewer allows selecting a flow arrow, for example via the analysis view by clicking on incoming/outgoing flows. However the selected flow arrow is invisible unless the user has selected "show all flow arrows" which typically clutters the display.

This proposes to systematically display selected/highlighted arrows. See the following screenshot for the difference between showing all flows and showing only selected flow arrows.

At the moment the UI doesn't allow selecting or highlighting multiple flow arrows and the UI never gets cluttered. If we ever allow selecting multiple flow arrows we might consider adding a view option for hiding/showing selected flow arrows, but I would personally prefer not to do this given that having an invisible selection is unintuitive.

With all flow events, the display can get cluttered:
![screen shot 2015-06-04 at 9 09 35 am](https://cloud.githubusercontent.com/assets/11399419/7984864/2ec5c7b8-0a9a-11e5-9e59-bd5b3030ab6f.png)

Turning flow events off, selecting a flow arrow leads to an "invisible selection", only the analysis view reflects the selection. With this proposal, the selected flow arrow would become visible:
![screen shot 2015-06-04 at 9 11 03 am](https://cloud.githubusercontent.com/assets/11399419/7984865/2ec814aa-0a9a-11e5-9d89-ae26d01083d7.png)

**Comment by dj2** [comment]
That seems like a good idea. I'd go one step further as well and, if you select a slice with terminates or starts a flow arrow we should show all of the arrows in that flow chain. So, you haven't selected the arrow itself just clicked on the slice.

That way, you can have flow arrows off, click on the input latency event and have all the arrows in the chain appear.

**Comment by natduca** [comment]
Yeah, I like all this thinking. Keep on being awesome!

Philippe, does this still all fit within the
selecitoncontroller-drives-related-flow-events design we discussed before?

**Comment by philippebeaudoin** [comment]
Yup, I think this is very similar to the selectallrelatedstuff patch I'm currently working on. Something else I want to add is that hovering on these links should highlight (and not select) the corresponding events. It's all coming, stay tuned!

**Comment by philippebeaudoin** [comment]
Closing now that analysis link highlighting landed.
