### ISSUE TITLE
Power information should be pulled out of the kernel track and into its own track

### ISSUE THREAD

**Issue by zeptonaut** [google/trace-viewer#996]
Right now, power information in trace viewer is displayed under the "Kernel" track, like this:

![image](https://cloud.githubusercontent.com/assets/1407397/7985207/0da0a532-0a9d-11e5-9b05-b381ca955b68.png)

Because we expect that in the future developers will be interested in viewing power graphs independently of detailed kernel traces, we should pull these power graphs out into their own track.

**Comment by natduca** [comment]
I would support adding Device class to trace_model, and hanging it off of Model, next to kernel. Device would contain a PowerCounter. Then we'd also have a DeviceTrack that ModelTrack creates. Make sense?

**Comment by zeptonaut** [comment]
Sounds good. This is basically what I did, except s/Device/Power. I like your terminology better, though.

**Comment by zeptonaut** [comment]
This bug is closed now that 80e778d is in.
