### ISSUE TITLE
Filtering not showing statistics of matching events.

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#997]
Instead of showing a *summary table* of matching events (like in multi-selection), the analysis shows *individual matching events* upon clicking the arrow buttons next to the filter input. The only available filtering statistic is the number of matching events, which is almost invisible (due to being light gray).

I think that we should provide both views (single- and multi-event) for filtering. How about we add a "select" button next to the filter input which would convert the highlight to selection?

@natduca, @dj2: WDYT?

**Comment by dj2** [comment]
I think this is a bug. When you're using the find box it used to populate the multi-selection like summary. Something broke and it stopped working.

We should just fix it so as you type find does the right thing to populate the lower panel.

**Comment by dj2** [comment]
See https://github.com/google/trace-viewer/issues/990
