### ISSUE TITLE
PRESUBMIT complain about copyright on an unmodified file

### ISSUE THREAD

**Issue by nedn** [google/trace-viewer#998]
In https://codereview.appspot.com/246720043/, if I don't make change to trace_viewer/extras/__ init__.py, the PRESUBMIT will complain about the file's copyright.

**Comment by dj2** [comment]
@natduca

**Comment by nedn** [comment]
Looks like this is caused by 2 things:
1) input_api include trace_viewer/extras/__init__.py in its AffectedFiles() list.
2) trace_viewer/extras/__ init__.py doesn't have newline after the copyright.

**Comment by dj2** [comment]
Ah, so if we put in the newline, we don't need to change the date? Let's just do that and then we can close this. I think the newline after the copyright is a valid requirement.

**Comment by nedn** [comment]
Yeah, I did put the newline only.
