### ISSUE TITLE
Prepare for catapultization.

### ISSUE THREAD

**Issue by dj2** [google/trace-viewer#999]
When we move to catapult we'll have a different directory structure. We're going to move trace-viewer to mirror what will be the catapult structure ahead of time.

This means trace-viewer structure will be a bit weird for a while.

Specifically, everything in in trace-viewer will move into trace-viewer/tracing. We'll then move what is currently trace-viewer/trace_viewer to trace-viewer/tracing/tracing. This will match where we end up in catapult.

In order to do this we need to:

 * move the source code and fix all includes
 * Roll deps (this has some extra magic to it)
    * update telemetry to have correct paths
    * update .gn to have new path to trace-viewer/BUILD.gn
    * update content/browser/tracing/BUILD.gn
    * update content/browser/tracing/tracing_resources.gyp
    * update tools/profile_chrome/trace_packager.py
 * notify Android systrace folks and adb_profile_chrome folks about new source layout.

**Comment by dj2** [comment]
@natduca @nedn

**Comment by nedn** [comment]
Doc: https://docs.google.com/document/d/1s2JyHPEZK7efQDapoUxutG4hh_0CYMrXBSB01a0tBG4/edit?usp=sharing

**Comment by dj2** [comment]
This is now fixed. Everything that can be moved around should now be in place for catapult. We've rolled deps and things on the Chrome side seem to be happy.
